// Generated by scripts/export-source-world-layers.py.
export const SOURCE_WORLD_LAYERS_RECEIPT = {
  "file": "manifest-native-alpha.json",
  "bytes": 171594,
  "sha256": "a7f8e617ca36cbbf30913f40ebef3c58af54ff45b131620799ab430758e779ba"
} as const;
