/** The original Dust2 buy zones, generated from the shipped map data.
 *
 * Generated by `scripts/probe-source-buy-zones.ts` from the collision artifact's
 * `func_buyzone` sensor brushes and the map's own entity list, matched by hammer id.
 * Each is a box in the collision artifact's own frame; the test that covers them reads both
 * files back and compares, so this table cannot drift from them silently.
 *
 * Source hashes at generation:
 *   collision.json  55184f994bc852dc229bbed0cb772cb843b1bc662054013c5076df98ce2a43cb
 *   entities.json   f0fd42a47dd4dd9f1eb8c79130b084475cf0f4402e1e6f21dfc70b65a55caf30
 */
import type { SourceBuyZone } from './source-buy-zone.js';

export const SOURCE_BUY_ZONES: readonly SourceBuyZone[] = [
  { hammerId: '2568320', team: 2, min: [-30.3784, 0, 16.0528], max: [-7.9248, 7.3152, 25.8064] },
  { hammerId: '2568324', team: 3, min: [-4.8768, -3.2512, -65.024], max: [15.0368, -0.8128, -50.3936] },
];

export const SOURCE_BUY_ZONE_SOURCES = {
  collisionJsonSha256: '55184f994bc852dc229bbed0cb772cb843b1bc662054013c5076df98ce2a43cb', entitiesJsonSha256: 'f0fd42a47dd4dd9f1eb8c79130b084475cf0f4402e1e6f21dfc70b65a55caf30',
} as const;
