/**
 * The original decal fog fade, generated from the shipped build and materials.
 *
 * Generated by `scripts/stage-source-decal-fog-fade.py` from `research/source-decal-fog-fade.json`,
 * which `scripts/probe-source-decal-fog-fade.py` produced by reading the shipped `DecalModulate`'s
 * own parameter declarations, its `ps_2_b` combos and the decal materials this map's impacts reach.
 * `tests/source-decal-fog-fade.test.ts` reads the report back and compares, so this table cannot
 * drift from the measurement silently.
 *
 * Source hashes at generation:
 *   stdshader_dx9_client.so  0383c51766a4681b5de26aa79b67ade5d3a867a8622185abe8a090877bac7c2e
 *   decalmodulate_ps20b.vcs  b18ce521ec30446b4747c500e8caf85b0bf0061868f7002108fe74fbd662fb98
 */
export const SOURCE_DECAL_FOG_FADE_DATA: unknown = {
  "format": "source-decal-fog-fade-v1",
  "shaderSha256": "0383c51766a4681b5de26aa79b67ade5d3a867a8622185abe8a090877bac7c2e",
  "declared": {
    "exponent": "0.4",
    "scale": "1.0",
    "fadeStart": null,
    "fadeEnd": null
  },
  "neutral": 0.5,
  "programs": {
    "fade": {
      "static": 2,
      "dynamic": 0,
      "sha256": "f59dbbb84e4e1b0202241ba9b0520cbcd83ee3aeb4803740515e3f08dc783be9",
      "instructions": [
        "def c1.xyzw (0.5, 0.0, 0.0, 0.0)",
        "dcl usage=0 index=0 a0.xy",
        "dcl usage=0 index=0 a1.xyz",
        "dcl usage=0 index=0 s0.xyzw",
        "texld r0.xyzw, a0.xyzw, s0.xyzw",
        "add r1.xyz, -a1.xyzw, c11.xyzw",
        "dp3 r1.x, r1.xyzw, r1.xyzw",
        "rsq r1.x, r1.xxxx",
        "rcp r1.x, r1.xxxx",
        "mad r1.x_sat, r1.xxxx, c12.wwww, c12.xxxx",
        "min r2.w, r1.xxxx, c12.zzzz",
        "mul r1.x_sat, r2.wwww, c0.yyyy",
        "add r1.y, r2.wwww, -c0.zzzz",
        "pow r2.x, r1.xxxx, c0.xxxx",
        "mul r1.x, r2.xxxx, r2.xxxx",
        "add r1.z, -c0.zzzz, c0.wwww",
        "rcp r1.z, r1.zzzz",
        "mul r1.y_sat, r1.zzzz, r1.yyyy",
        "lrp r2.xyz, r1.yyyy, c1.xxxx, r0.xyzw",
        "lrp r0.xyz, r1.xxxx, c29.xyzw, r2.xyzw",
        "mov oc0.xyzw, r0.xyzw"
      ]
    },
    "plain": {
      "static": 0,
      "dynamic": 0,
      "sha256": "e273590c0b6907d902b199f9f066f241addf4b5ad24973ec39e60971d6fbc889",
      "instructions": [
        "dcl usage=0 index=0 a0.xy",
        "dcl usage=0 index=0 a1.xyz",
        "dcl usage=0 index=0 s0.xyzw",
        "texld r0.xyzw, a0.xyzw, s0.xyzw",
        "add r1.xyz, -a1.xyzw, c11.xyzw",
        "dp3 r1.x, r1.xyzw, r1.xyzw",
        "rsq r1.x, r1.xxxx",
        "rcp r1.x, r1.xxxx",
        "mad r1.x_sat, r1.xxxx, c12.wwww, c12.xxxx",
        "min r2.w, r1.xxxx, c12.zzzz",
        "mul r1.x_sat, r2.wwww, c0.yyyy",
        "pow r2.x, r1.xxxx, c0.xxxx",
        "mul r1.x, r2.xxxx, r2.xxxx",
        "lrp r2.xyz, r1.xxxx, c29.xyzw, r0.xyzw",
        "mov r2.w, r0.wwww",
        "mov oc0.xyzw, r2.xyzw"
      ]
    },
    "vertexAlpha": {
      "static": 1,
      "dynamic": 1,
      "sha256": "3fd39be33dc18db43b61b4bd941962ccba8adf5643bb48e97afd695ad59dfc0e",
      "instructions": [
        "def c0.xyzw (-0.5, 0.5, 0.0, 0.0)",
        "dcl usage=0 index=0 a0.xy",
        "dcl usage=0 index=0 v1.xyzw",
        "dcl usage=0 index=0 s0.xyzw",
        "texld r0.xyzw, a0.xyzw, s0.xyzw",
        "add r1.xyz, r0.xyzw, c0.xxxx",
        "mad r0.xyz, v1.wwww, r1.xyzw, c0.yyyy",
        "mov oc0.xyzw, r0.xyzw"
      ]
    }
  },
  "fadeAtlases": {
    "decals/decals_bulletsheet": {
      "fadeStart": 0.0,
      "fadeEnd": 0.5,
      "scale": 1.0,
      "exponent": 0.4
    },
    "decals/decals_mod2x": null
  },
  "limitations": [
    "The shader's own `VERTEXALPHA` variant scales the decal texel toward its neutral by the vertex alpha; this renderer's decal quads carry no vertex colour, so that factor is one and the variant is not drawn separately.",
    "The shipped `$nofog` dynamic combo - the same decal with no fog arithmetic at all - is not asked for by either sheet this map draws from, so this renderer always computes the fog.",
    "The engine's static combo key was not read: the port keys the fade off the material's own stated bound, which is the value the arithmetic requires and which every shipped material that uses the fade states.",
    "The sheet carries the sRGB flag, and the port samples it as stored: DX9 has no sRGB sampler decode for the DXT formats these sheets ship as, and the shipped program carries no conversion of its own, so the texel it multiplies is the stored one and the port must multiply in the same encoding the framebuffer holds."
  ]
};

export const SOURCE_DECAL_FOG_FADE_SOURCES = {
  shaderSha256: '0383c51766a4681b5de26aa79b67ade5d3a867a8622185abe8a090877bac7c2e',
  containerSha256: 'b18ce521ec30446b4747c500e8caf85b0bf0061868f7002108fe74fbd662fb98',
  fadeProgramSha256: 'f59dbbb84e4e1b0202241ba9b0520cbcd83ee3aeb4803740515e3f08dc783be9',
} as const;
