/** Generated by scripts/stage-source-gamemode.py - do not edit by hand. */
export const SOURCE_GAMEMODE_COMPETITIVE_STAGED = {
 "format": "source-gamemode-competitive-v1",
 "build": 12426148,
 "application": 740,
 "sourceApp": 740,
 "keys": [
  "cash_player_bomb_defused",
  "cash_player_bomb_planted",
  "cash_player_killed_enemy_default",
  "cash_player_killed_enemy_factor",
  "cash_player_killed_teammate",
  "ff_damage_reduction_bullets",
  "ff_damage_reduction_grenade",
  "ff_damage_reduction_grenade_self",
  "ff_damage_reduction_other",
  "cash_team_elimination_bomb_map",
  "cash_team_terrorist_win_bomb",
  "cash_team_win_by_defusing_bomb",
  "cash_team_win_by_time_running_out_bomb",
  "cash_team_planted_bomb_but_defused",
  "cash_team_loser_bonus",
  "cash_team_loser_bonus_consecutive_rounds",
  "mp_starting_losses",
  "cash_team_bonus_shorthanded",
  "mp_startmoney",
  "mp_maxmoney",
  "mp_afterroundmoney",
  "mp_freezetime",
  "mp_friendlyfire",
  "mp_forcecamera",
  "mp_buytime",
  "mp_roundtime_defuse",
  "mp_win_panel_display_time",
  "mp_maxrounds",
  "mp_halftime",
  "mp_match_can_clinch"
 ],
 "base": {
  "mode": "competitive",
  "source": "gamemode_competitive.cfg",
  "bytes": 4542,
  "sha256": "f76ccb9f1eee99a66a6ee0a9e1debf2b31d7d0bc3f4516b4b52f1b7985912fd5",
  "lineCount": 117,
  "values": {
   "cash_player_bomb_defused": {
    "value": "300",
    "line": 9
   },
   "cash_player_bomb_planted": {
    "value": "300",
    "line": 10
   },
   "cash_player_killed_enemy_default": {
    "value": "300",
    "line": 13
   },
   "cash_player_killed_enemy_factor": {
    "value": "1",
    "line": 14
   },
   "cash_player_killed_teammate": {
    "value": "-300",
    "line": 16
   },
   "ff_damage_reduction_bullets": {
    "value": "0.33",
    "line": 34
   },
   "ff_damage_reduction_grenade": {
    "value": "0.85",
    "line": 35
   },
   "ff_damage_reduction_grenade_self": {
    "value": "1",
    "line": 36
   },
   "ff_damage_reduction_other": {
    "value": "0.4",
    "line": 37
   },
   "cash_team_elimination_bomb_map": {
    "value": "3250",
    "line": 18
   },
   "cash_team_terrorist_win_bomb": {
    "value": "3500",
    "line": 29
   },
   "cash_team_win_by_defusing_bomb": {
    "value": "3500",
    "line": 30
   },
   "cash_team_win_by_time_running_out_bomb": {
    "value": "3250",
    "line": 33
   },
   "cash_team_planted_bomb_but_defused": {
    "value": "800",
    "line": 27
   },
   "cash_team_loser_bonus": {
    "value": "1400",
    "line": 23
   },
   "cash_team_loser_bonus_consecutive_rounds": {
    "value": "500",
    "line": 26
   },
   "mp_starting_losses": {
    "value": "1",
    "line": 25
   },
   "cash_team_bonus_shorthanded": {
    "value": "1000",
    "line": 24
   },
   "mp_startmoney": {
    "value": "800",
    "line": 74
   },
   "mp_maxmoney": {
    "value": "16000",
    "line": 66
   },
   "mp_afterroundmoney": {
    "value": "0",
    "line": 38
   },
   "mp_freezetime": {
    "value": "15",
    "line": 49
   },
   "mp_friendlyfire": {
    "value": "1",
    "line": 50
   },
   "mp_forcecamera": {
    "value": "1",
    "line": 47
   },
   "mp_buytime": {
    "value": "20",
    "line": 39
   },
   "mp_roundtime_defuse": {
    "value": "1.92",
    "line": 72
   },
   "mp_win_panel_display_time": {
    "value": "3",
    "line": 51
   },
   "mp_maxrounds": {
    "value": "30",
    "line": 67
   },
   "mp_halftime": {
    "value": "1",
    "line": 64
   },
   "mp_match_can_clinch": {
    "value": "1",
    "line": 65
   }
  },
  "absent": []
 },
 "short": {
  "mode": "competitiveShort",
  "source": "gamemode_competitive_short.cfg",
  "bytes": 116,
  "sha256": "e7bb7fd3f35ae3b3fb1ad34fffd9ec53c16fbdd6acd56ddebff60d52311d28ad",
  "lineCount": 3,
  "values": {
   "mp_starting_losses": {
    "value": "2",
    "line": 3
   },
   "mp_maxrounds": {
    "value": "16",
    "line": 2
   }
  },
  "absent": [
   "cash_player_bomb_defused",
   "cash_player_bomb_planted",
   "cash_player_killed_enemy_default",
   "cash_player_killed_enemy_factor",
   "cash_player_killed_teammate",
   "ff_damage_reduction_bullets",
   "ff_damage_reduction_grenade",
   "ff_damage_reduction_grenade_self",
   "ff_damage_reduction_other",
   "cash_team_elimination_bomb_map",
   "cash_team_terrorist_win_bomb",
   "cash_team_win_by_defusing_bomb",
   "cash_team_win_by_time_running_out_bomb",
   "cash_team_planted_bomb_but_defused",
   "cash_team_loser_bonus",
   "cash_team_loser_bonus_consecutive_rounds",
   "cash_team_bonus_shorthanded",
   "mp_startmoney",
   "mp_maxmoney",
   "mp_afterroundmoney",
   "mp_freezetime",
   "mp_friendlyfire",
   "mp_forcecamera",
   "mp_buytime",
   "mp_roundtime_defuse",
   "mp_win_panel_display_time",
   "mp_halftime",
   "mp_match_can_clinch"
  ]
 },
 "shortOverrides": {
  "mp_starting_losses": {
   "value": "2",
   "line": 3
  },
  "mp_maxrounds": {
   "value": "16",
   "line": 2
  }
 },
 "absent": {
  "mp_consecutive_loss_max": {
   "absentIn": [
    "gamemode_competitive.cfg",
    "gamemode_competitive_short.cfg"
   ],
   "reason": "not present in the shipped mode configs; the runtime declares this adapter"
  }
 },
 "boundaries": [
  "Values are the strings the original config ships, with the line they came from.",
  "The short mode is this file plus the keys its own config overrides.",
  "Per-weapon kill awards, the consecutive-loss cap and the hostage-map cash are not defined by these files and are declared absent rather than guessed."
 ]
} as const;
