// Generated by scripts/stage-source-environment-probes.py from the original Dust II BSP.
export const SOURCE_ENVIRONMENT_PROBES_MANIFEST_SHA256 = "58dc7e31adf0a7c2a76f3948e1020271d6ec7066f081a83dd95c653b9cc28706";
