import {applySourceCharacterRagdoll,loadSourceCharacterRagdoll} from './source-character-ragdoll.js';
import type {SourceRagdollIndex,SourceRagdollState} from './source-ragdoll.js';
import * as T from'three';
import {GLTFLoader,type GLTF}from'three/addons/loaders/GLTFLoader.js';
import {clone}from'three/addons/utils/SkeletonUtils.js';
import {prepareSourceAWPWorldPose}from'./source-awp-world-pose';
import {prepareSourceCharacterPose}from'./source-character-pose';
import {prepareSourceAWPCharacterPose,sampleSourceAWPCharacterPose,type SourceAWPCharacterPoseIndex,type SourceAWPCharacterPoseInput}from'./source-awp-character-pose';
import {applySourceAWPCharacterSurfaces}from'./source-awp-character-surfaces';
import {SOURCE_AWP_CHARACTERS,type SourceAWPCharacterManifest}from'./source-awp-character-contracts.js';
import {sourceSha256}from'./source-sha256';
import {sourceMagazineDropFromMesh,type SourceMagazineDropSource}from'./source-magazine-drop';
export type {SourceAWPCharacterManifest} from './source-awp-character-contracts.js';
type Joint={bone:number;sourceName:string;gltfNode:number;skinJoint:number};
export type SourceAWPCharacterRig={format:'source-awp-character-rig-v1';team:'t'|'ct';weaponId:'awp';bodyBoneCount:71|74;worldBoneCount:94;mappings:Record<'body'|'world',{skinIndex:number;skinName:string;joints:Joint[]}>;boneMerge:{weaponBone:number;characterBone:number;name:string}[];bodygroupNodes:{magazine:number[];silencer:number[]};attachments:{name:string;parent_bone:number;matrix:number[]}[]};
export type SourceAWPCharacterAuthority={x:number;y:number;z:number;yaw:number;sourceContract?:string;sourcePoseVersion?:string;sourceAWPPose?:SourceAWPCharacterPoseInput;grounded?:boolean;sourceGroundY?:number;sourceRagdoll?:SourceRagdollState};
export type SourceAWPCharacterActor={root:T.Group;model:T.Object3D;bodyBones:T.Bone[];worldBones:T.Bone[];bodygroups:{magazine:T.Object3D[];silencer:T.Object3D[]};lastPose:ReturnType<typeof sampleSourceAWPCharacterPose>|null;status:'awaiting-authority'|'ready'|'invalid-authority'|'disposed';
 /** Original magazine display state of the last sampled pose; null until the
  * first authoritative pose so a mid-reload first sight never fakes a drop. */
 magazineVisible:boolean|null;magazineGroundY:number;magazineSeed:number;pendingMagazineDrop:SourceMagazineDropSource|null};
function check(v:unknown,m:string):asserts v{if(!v)throw Error(m);}
const C=new T.Matrix4().set(1,0,0,0,0,0,1,0,0,-1,0,0,0,0,0,1);
/** Exact-rig actor constructor, independently testable without network/images.
 * Geometry/materials belong to glTF's owner; each instance owns its skeletons.
 */
export function createSourceAWPCharacterActors(gltf:GLTF,index:SourceAWPCharacterPoseIndex,rig:SourceAWPCharacterRig,manifest:SourceAWPCharacterManifest,ragdollIndex?:SourceRagdollIndex){
 const {team,weapon}=index,frozen=SOURCE_AWP_CHARACTERS[`${team}-${weapon}`],count=team==='t'?71:74,worldCount=94;
 check(manifest.format==='source-awp-character-stage-v1'&&manifest.sourceApp===740&&manifest.build===12426148&&manifest.team===team&&manifest.weaponId===weapon&&manifest.poseVersion===frozen.poseVersion&&manifest.files.find(f=>f.path===manifest.model)?.sha256===frozen.modelSha256&&manifest.bodyBoneCount===count&&manifest.worldBoneCount===worldCount&&manifest.animationBoneCount===index.body.boneCount&&manifest.characterProfile===(team==='t'?'tm_leet_varianta':'ctm_idf')&&manifest.sourceCharacter===index.body.data.mainModel&&manifest.sourceAnimation===index.body.data.animationModel&&manifest.sourceWorldWeapon===index.world.data.sourceModel&&manifest.metersPerSourceUnit===.0254&&Math.abs(manifest.actorYawOffsetRadians-Math.PI/2)<1e-12,'Frozen original AWP actor identity differs');
 check(rig.format==='source-awp-character-rig-v1'&&rig.team===team&&rig.weaponId===weapon&&rig.bodyBoneCount===count&&rig.worldBoneCount===worldCount&&rig.boneMerge.length===3,'Original AWP actor rig differs');
 for(const m of rig.boneMerge)check(index.boneMerge.get(m.weaponBone)===m.characterBone&&index.world.data.bones[m.weaponBone].name===m.name,'Original AWP bone merge differs');
 const byNode=new Map<number,T.Object3D>();for(const[o,a]of gltf.parser.associations)if(a.nodes!==undefined)byNode.set(a.nodes,o as T.Object3D);
 check(gltf.parser.json.skins?.length===2&&gltf.animations.length===0,'Original AWP actor must retain two independent skins and no baked clips');
 for(const role of ['body','world']as const){const defs=role==='body'?index.body.data.mainBones:index.world.data.bones,r=rig.mappings[role],ids=new Set<number>(),slots=new Set<number>();check(r.joints.length===defs.length&&gltf.parser.json.skins[r.skinIndex]?.name===r.skinName,'Original AWP render mapping differs');for(const j of r.joints){const bone=byNode.get(j.gltfNode);check(bone instanceof T.Bone&&Number.isInteger(j.bone)&&j.bone>=0&&j.bone<defs.length&&defs[j.bone].name===j.sourceName&&!ids.has(j.bone)&&!slots.has(j.skinJoint)&&gltf.parser.json.skins[r.skinIndex].joints[j.skinJoint]===j.gltfNode,'Original AWP render bone differs');ids.add(j.bone);slots.add(j.skinJoint);bone.userData.sourceAWPActorRole=role;bone.userData.sourceAWPActorBone=j.bone;}}
 const skinRoles=new Set<string>();gltf.scene.traverse(o=>{if(!(o instanceof T.SkinnedMesh))return;const role=(['body','world']as const).find(role=>rig.mappings[role].joints.every(j=>o.skeleton.bones[j.skinJoint]===byNode.get(j.gltfNode)));check(role,'Unknown original AWP actor skin');skinRoles.add(role);const defs=role==='body'?index.body.data.mainBones:index.world.data.bones;for(const j of rig.mappings[role].joints)check(o.skeleton.boneInverses[j.skinJoint].elements.every((v,k)=>v===defs[j.bone].inverseBindGltf[k]),'Original AWP actor inverse bind differs');});check(skinRoles.size===2,'Missing original AWP actor skin');
 for(const kind of ['magazine','silencer']as const){check(rig.bodygroupNodes[kind].length===(kind==='magazine'?1:0),'Original AWP bodygroup count differs');for(const id of rig.bodygroupNodes[kind]){const o=byNode.get(id);check(o&&gltf.parser.json.nodes[id]?.skin===rig.mappings.world.skinIndex,'Original AWP bodygroup node differs');o.userData.sourceAWPActorBodygroup=kind;}}
 const actors=new Set<SourceAWPCharacterActor>(),keys=new WeakMap<SourceAWPCharacterActor,string>();let disposed=false;
 function createActor(){check(!disposed,'AWP character owner disposed');const root=new T.Group(),model=clone(gltf.scene),bodyBones:T.Bone[]=[],worldBones:T.Bone[]=[],bodygroups={magazine:[]as T.Object3D[],silencer:[]as T.Object3D[]};root.name=`Source_${team}_${weapon}_Actor`;root.userData.sourceWeaponId=weapon;root.userData.sourceCharacterProfile=manifest.characterProfile;root.userData.sourcePoseVersion=manifest.poseVersion;model.scale.setScalar(.0254);root.add(model);root.visible=false;
 model.traverse(o=>{if(o instanceof T.Bone){const id=o.userData.sourceAWPActorBone,role=o.userData.sourceAWPActorRole;if(role==='body')bodyBones[id]=o;else if(role==='world')worldBones[id]=o;}const kind:unknown=o.userData.sourceAWPActorBodygroup;if(kind==='magazine'||kind==='silencer')bodygroups[kind].push(o);if(o instanceof T.SkinnedMesh){o.skeleton.boneInverses=o.skeleton.boneInverses.map(m=>m.clone());o.frustumCulled=false;}});check(bodyBones.filter(Boolean).length===count&&worldBones.filter(Boolean).length===worldCount,'Cloned original AWP actor missing bones');const actor:SourceAWPCharacterActor={root,model,bodyBones,worldBones,bodygroups,lastPose:null,status:'awaiting-authority',magazineVisible:null,magazineGroundY:NaN,magazineSeed:0,pendingMagazineDrop:null};actors.add(actor);return actor;
 }
 function updateActor(actor:SourceAWPCharacterActor,state:SourceAWPCharacterAuthority){check(!disposed&&actors.has(actor),'Unknown/disposed AWP actor');const invalidate=()=>{actor.root.visible=false;actor.status='invalid-authority';actor.lastPose=null;keys.delete(actor);return null;};if(state.sourceContract!=='csgo-player-12426148'||state.sourcePoseVersion!==manifest.poseVersion||!state.sourceAWPPose||![state.x,state.y,state.z,state.yaw].every(Number.isFinite))return invalidate();
 if(state.grounded!==false||!Number.isFinite(actor.magazineGroundY))actor.magazineGroundY=state.sourceGroundY??state.y;let ejected=false;
 try{const key=JSON.stringify([state.sourceAWPPose,state.sourceRagdoll]);if(keys.get(actor)!==key){const p=sampleSourceAWPCharacterPose(index,state.sourceAWPPose);if(state.sourceRagdoll&&ragdollIndex)applySourceCharacterRagdoll(index,ragdollIndex,p,state.sourceRagdoll);for(let i=0;i<count;i++){actor.bodyBones[i].position.fromArray(p.body.renderLocalPositions,i*3);actor.bodyBones[i].quaternion.fromArray(p.body.renderLocalQuaternions,i*4);actor.bodyBones[i].scale.set(1,1,1);}for(let i=0;i<worldCount;i++){const b=actor.worldBones[i];b.matrixAutoUpdate=false;b.matrix.fromArray(p.weaponRenderLocalMatrices,i*16);b.matrixWorldNeedsUpdate=true;}for(const o of actor.bodygroups.magazine)o.visible=p.magazineVisible;actor.lastPose=p;keys.set(actor,key);
  // The magazine that just left the weapon at AE_CL_EJECT_MAG becomes its own prop.
  ejected=actor.magazineVisible===true&&!p.magazineVisible;actor.magazineVisible=p.magazineVisible;}
 actor.root.position.set(state.x,state.y,state.z);actor.root.rotation.set(0,state.yaw+Math.PI/2,0);actor.root.visible=true;actor.status='ready';actor.root.updateMatrixWorld(true);
 if(ejected)actor.pendingMagazineDrop=magazineDrop(actor,state);return actor.lastPose;
 }catch(error){invalidate();throw error;}}
 function magazineDrop(actor:SourceAWPCharacterActor,state:SourceAWPCharacterAuthority){const mesh=actor.bodygroups.magazine.find(o=>o instanceof T.Mesh)as T.Mesh|undefined;return mesh?sourceMagazineDropFromMesh({key:weapon,mesh,root:actor.root,origin:{x:state.x,y:state.y,z:state.z},floorY:actor.magazineGroundY,seed:actor.magazineSeed++}):null;}
 function attachment(actor:SourceAWPCharacterActor,name:string){check(actors.has(actor),'Unknown AWP actor attachment');if(actor.status!=='ready'||!actor.lastPose)return null;const a=rig.attachments.find(a=>a.name===name);if(!a||a.matrix.length!==12)return null;actor.root.updateWorldMatrix(true,false);const m=new T.Matrix4().set(...[...a.matrix.slice(0,4),...a.matrix.slice(4,8),...a.matrix.slice(8,12),0,0,0,1]as Parameters<T.Matrix4['set']>);return actor.root.matrixWorld.clone().multiply(new T.Matrix4().makeScale(.0254,.0254,.0254)).multiply(C).multiply(new T.Matrix4().fromArray(actor.lastPose.sourceWeaponWorldMatrices,a.parent_bone*16)).multiply(m);}
 function disposeActor(actor:SourceAWPCharacterActor){if(!actors.delete(actor))return;actor.root.removeFromParent();actor.root.visible=false;actor.status='disposed';actor.lastPose=null;keys.delete(actor);const skeletons=new Set<T.Skeleton>();actor.model.traverse(o=>{if(o instanceof T.SkinnedMesh)skeletons.add(o.skeleton);});skeletons.forEach(s=>s.dispose());}
 function dispose(){if(disposed)return;for(const a of [...actors])disposeActor(a);disposed=true;}
 /** Hands over the original magazine prop that left the weapon on the last
  * authoritative pose, and clears it. Exactly one consumer per drop. */
 function takeMagazineDrop(actor:SourceAWPCharacterActor){check(actors.has(actor),'Unknown AWP actor magazine drop');const drop=actor.pendingMagazineDrop;actor.pendingMagazineDrop=null;return drop;}
 return{createActor,updateActor,attachment,takeMagazineDrop,disposeActor,dispose};
}
export type SourceAWPCharacterLoadOptions={team:'t'|'ct';baseUrl?:string;signal?:AbortSignal;loadingManager?:T.LoadingManager};
/** Explicit original AWP character owner with its own sniper animation graph. */
export async function loadSourceAWPCharacter(options:SourceAWPCharacterLoadOptions){
 const{team,signal}=options,weapon='awp' as const,frozen=SOURCE_AWP_CHARACTERS[`${team}-${weapon}`];check(frozen,'Unknown original AWP character profile');const base=(options.baseUrl??`/source/csgo-12426148/character-${team}-${weapon}`).replace(/\/$/,'');const response=await fetch(base+'/manifest.json',{signal,cache:'no-cache'});check(response.ok,'AWP character manifest HTTP '+response.status);const raw=new Uint8Array(await response.arrayBuffer());check(await sourceSha256(raw,signal)===frozen.manifestSha256,'AWP character manifest SHA mismatch');const manifest=JSON.parse(new TextDecoder().decode(raw))as SourceAWPCharacterManifest;check(manifest.team===team&&manifest.weaponId===weapon&&manifest.poseVersion===frozen.poseVersion,'AWP character requested identity mismatch');
 const files=new Map(manifest.files.map(f=>[f.path,f]));check(files.size===manifest.files.length&&manifest.files.every(f=>/^[\w./-]+$/.test(f.path)&&!f.path.startsWith('/')&&f.path.split('/').every(p=>p!=='.'&&p!=='..')&&Number.isSafeInteger(f.bytes)&&f.bytes>0&&/^[a-f0-9]{64}$/.test(f.sha256))&&files.get(manifest.model)?.sha256===frozen.modelSha256&&files.get(manifest.rig)?.sha256===frozen.rigSha256,'AWP character frozen file set differs');
 const textures=new Map<string,T.Texture>(),hashVerified:Record<string,boolean>={'manifest.json':true};let gltf:GLTF|undefined,surfaces:ReturnType<typeof applySourceAWPCharacterSurfaces>|undefined,actors:ReturnType<typeof createSourceAWPCharacterActors>|undefined,disposed=false;
 async function bytes(path:string){check(!disposed,'AWP character owner disposed');const row=files.get(path);check(row,'AWP character file absent');const r=await fetch(base+'/'+path,{signal,cache:'no-cache'});check(r.ok,'AWP character HTTP '+r.status+' '+path);const b=new Uint8Array(await r.arrayBuffer());check(b.byteLength===row.bytes&&await sourceSha256(b,signal)===row.sha256,'AWP character SHA mismatch: '+path);hashVerified[path]=true;return b;}
 const textureLoader=new T.TextureLoader(options.loadingManager);async function texture(path:string){const b=await bytes(path),url=URL.createObjectURL(new Blob([b as Uint8Array<ArrayBuffer>],{type:'image/png'}));try{const t=await textureLoader.loadAsync(url);textures.set(path,t);signal?.throwIfAborted();t.flipY=false;t.colorSpace=/normal|exponent/.test(path)?T.NoColorSpace:T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=8;t.needsUpdate=true;}finally{URL.revokeObjectURL(url);}}
 function dispose(){if(disposed)return;disposed=true;actors?.dispose();surfaces?.dispose();const geometry=new Set<T.BufferGeometry>(),materials=new Set<T.Material>(),images=new Set<ImageBitmap>(),ownedTextures=new Set(textures.values()),skeletons=new Set<T.Skeleton>();gltf?.scene.traverse(o=>{if(o instanceof T.Mesh){geometry.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);for(const v of Object.values(m))if(v instanceof T.Texture)ownedTextures.add(v);}}if(o instanceof T.SkinnedMesh)skeletons.add(o.skeleton);});skeletons.forEach(s=>s.dispose());geometry.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());ownedTextures.forEach(t=>{if(typeof ImageBitmap!=='undefined'&&t.image instanceof ImageBitmap)images.add(t.image);t.dispose();});images.forEach(i=>i.close());gltf?.scene.removeFromParent();}
 try{const sourceNames=[manifest.rig,manifest.bodyPose,manifest.bodyFrames,manifest.worldPose,manifest.worldFrames],values=new Map<string,Uint8Array>();const pending=await Promise.allSettled([bytes(manifest.model).then(async b=>gltf=await new GLTFLoader(options.loadingManager).parseAsync(b.buffer as ArrayBuffer,base+'/')),...sourceNames.map(async path=>values.set(path,await bytes(path))),...manifest.files.filter(f=>f.path.startsWith('textures/')&&f.path.endsWith('.png')).map(f=>texture(f.path))]);for(const r of pending)if(r.status==='rejected')throw r.reason;signal?.throwIfAborted();const read=(p:string)=>JSON.parse(new TextDecoder().decode(values.get(p)!)),body=read(manifest.bodyPose),world=read(manifest.worldPose);check(body.frames.sha256===files.get(manifest.bodyFrames)!.sha256&&world.frames.sha256===files.get(manifest.worldFrames)!.sha256&&body.worldPoseSHA256===files.get(manifest.worldPose)!.sha256&&manifest.poseVersion===`csgo-${team}-${weapon}-12426148:`+files.get(manifest.bodyPose)!.sha256.slice(0,16),'AWP character pose files disagree');
 const poseIndex=prepareSourceAWPCharacterPose(prepareSourceCharacterPose(body,values.get(manifest.bodyFrames)!),prepareSourceAWPWorldPose(world,values.get(manifest.worldFrames)!));check(poseIndex.team===team&&poseIndex.weapon===weapon,'AWP character data identity differs');surfaces=applySourceAWPCharacterSurfaces(gltf!,team,weapon,textures);const ragdollIndex=await loadSourceCharacterRagdoll(base,poseIndex.body,signal);actors=createSourceAWPCharacterActors(gltf!,poseIndex,read(manifest.rig),manifest,ragdollIndex);return{gltf:gltf!,poseIndex,manifest,surfaces,hashVerified,createActor:actors.createActor,updateActor:actors.updateActor,attachment:actors.attachment,takeMagazineDrop:actors.takeMagazineDrop,disposeActor:actors.disposeActor,dispose};
 }catch(error){dispose();throw error;}
}
