/**
 * The original Dust2 environment, generated from the shipped map and build.
 *
 * Generated by `scripts/stage-source-environment.py` from `research/source-environment.json`,
 * which `scripts/probe-source-environment.py` produced by reading the frozen BSP's own entity
 * lump twice (here and in the reviewed SourceIO export) and the shipped build's own key tables.
 * `tests/source-environment.test.ts` reads the report back and compares, so this table cannot
 * drift from the measurement silently.
 *
 * Source hashes at generation:
 *   de_dust2.bsp     b91be410539fbbfc16300423f1e19c024f12addf1429c8cb2f72b53fe0fd6bcc
 *   entities.json    f0fd42a47dd4dd9f1eb8c79130b084475cf0f4402e1e6f21dfc70b65a55caf30
 *   server.dll       699757bb5c8ddb71193f68daba22f59f697491ddbd768bc8656ac2ce435c4db8
 *   server_client.so e2d7cab6059f8bb3346796795b46831621fdb0015ce6aa28a7e5747ec7fc463b
 *   client.dll       183d42fac8a4ecc24dc02edf5f09122f37fe9e7533ca093a867718b25cfdeb03
 *   cc_dust2.raw     cb7d3a3ab21cb20231ee34b20790f851f06bf9675136f89c339556e9d4371a85
 */
export const SOURCE_DUST2_ENVIRONMENT_DATA: unknown = {
  "id": "de_dust2",
  "sourceBspSha256": "b91be410539fbbfc16300423f1e19c024f12addf1429c8cb2f72b53fe0fd6bcc",
  "metersPerSourceUnit": 0.0254,
  "fog": {
    "enabled": true,
    "color": [
      213,
      203,
      172
    ],
    "sourceStart": 512.0,
    "sourceEnd": 9000.0,
    "maxDensity": 0.4,
    "nearMetres": 13.0048,
    "farMetres": 228.6
  },
  "light": {
    "sunColor": [
      254,
      230,
      197
    ],
    "sunBrightness": 575.0,
    "ambientColor": [
      211,
      226,
      248
    ],
    "ambientBrightness": 245.0,
    "lightScaleHDR": 1.0,
    "sunSourceAngles": [
      0.0,
      43.0,
      0.0
    ],
    "sunSourcePitch": -50.0,
    "sunSpreadAngle": 0.0,
    "sunSourceDirection": [
      0.470105098,
      0.438380096,
      0.766044443
    ]
  },
  "tonemap": {
    "targetname": "AutoInstance1-tonemap_global",
    "percentTarget": 80.0,
    "percentBrightPixels": 3.0,
    "rate": 0.2,
    "bloomScale": 0.0,
    "autoExposureMin": 0.5,
    "autoExposureMax": 1.25
  },
  "sun": {
    "material": "sprites/light_glow02_add_noz",
    "size": 32.0,
    "renderColor": [
      255,
      245,
      217
    ],
    "overlayMaterial": "sprites/light_glow02_add_noz",
    "overlaySize": -1.0,
    "overlayColor": [
      0,
      0,
      0
    ],
    "sourceAngles": [
      0.0,
      47.0,
      0.0
    ],
    "sourcePitch": -43.0,
    "hdrColorScale": 1.0,
    "glowDistanceScaleAsWritten": 0.1,
    "members": {
      "material": {
        "member": "m_strMaterial",
        "offset": 1248
      },
      "overlaymaterial": {
        "member": "m_strOverlayMaterial",
        "offset": 1256
      },
      "use_angles": {
        "member": "m_bUseAngles",
        "offset": 1264
      },
      "pitch": {
        "member": "m_flPitch",
        "offset": 1268
      },
      "angle": {
        "member": "m_flYaw",
        "offset": 1272
      },
      "size": {
        "member": "m_nSize",
        "offset": 1276
      },
      "overlaysize": {
        "member": "m_nOverlaySize",
        "offset": 1280
      },
      "overlaycolor": {
        "member": "m_clrOverlay",
        "offset": 1284
      }
    },
    "membersFrom": "csgo/bin/linux64/server_client.so",
    "note": "`glowdistancescale` is carried by none of the shipped binaries, so the build cannot match that key and the value above is authoring metadata, not a number this port can act on. `use_angles 1` means the direction is the entity's own `angles` with `m_flPitch` replacing the pitch."
  },
  "shadow": {
    "color": [
      128,
      128,
      128
    ],
    "distance": 72.0,
    "disableAllShadows": false,
    "sourceAngles": [
      90.0,
      43.0,
      0.0
    ]
  },
  "colorCorrection": {
    "filename": "materials/correction/cc_dust2.raw",
    "maxWeight": 1.0,
    "maxChannelDeltaVsNeutral": 1,
    "channelsMovedVsNeutral": 12837,
    "lutSha256": "cb7d3a3ab21cb20231ee34b20790f851f06bf9675136f89c339556e9d4371a85"
  },
  "postProcess": {
    "targetname": "pp_dust",
    "allStrengthsZero": true
  },
  "declaredButUnapplied": [
    "The original auto-exposes from a frame histogram: the client carries `mat_dynamic_tonemapping`, `mat_autoexposure_min`, `mat_autoexposure_max`, `mat_exposure_center_region_x`/`_y` and `mat_show_histogram`, and the map pushes the operating range into that system on spawn. The port renders with a fixed exposure, so the map's range is recorded and not applied.",
    "The original draws the sun sprite `env_sun` names and the port draws none. What is read is the map's own entity, the build's member table for it (`m_strMaterial` 0x4e0 through `m_clrOverlay` 0x504) and the fact that `glowdistancescale` is a key no shipped binary carries. What is not read is the client's draw arithmetic - how `m_nSize` becomes a screen size, when the `m_nOverlaySize -1` overlay is skipped - and `sprites/light_glow02_add_noz` is not exported, so nothing is drawn rather than something approximated.",
    "The original fades a projected shadow with the receiver's height above the shadow's own plane and lets the viewmodel project its own shadow; the port draws each actor's silhouette on the first surface below it and neither fades with height nor draws the viewmodel's shadow.",
    "The original grades the finished frame through the colour-correction lookup; the port applies none, which costs at most one step of 255 on 13% of the cube (measured in the report)."
  ]
};

export const SOURCE_DUST2_ENVIRONMENT_SOURCES = {
  sourceBspSha256: 'b91be410539fbbfc16300423f1e19c024f12addf1429c8cb2f72b53fe0fd6bcc',
  entitiesJsonSha256: 'f0fd42a47dd4dd9f1eb8c79130b084475cf0f4402e1e6f21dfc70b65a55caf30',
  serverDllSha256: '699757bb5c8ddb71193f68daba22f59f697491ddbd768bc8656ac2ce435c4db8',
  serverClientSoSha256: 'e2d7cab6059f8bb3346796795b46831621fdb0015ce6aa28a7e5747ec7fc463b',
  clientDllSha256: '183d42fac8a4ecc24dc02edf5f09122f37fe9e7533ca093a867718b25cfdeb03',
  colorCorrectionLutSha256: 'cb7d3a3ab21cb20231ee34b20790f851f06bf9675136f89c339556e9d4371a85',
  environmentJsonSha256: '08f5d249727d25165a77a08164b9c253afb796c3588dea1c04d8d63a544f37ef',
} as const;
