/** Generated by scripts/build-source-treesway-glsl.py; original App740 VS128/dynamic0. */
export const SOURCE_TREESWAY_PROGRAM_SHA256='fd2c99952aeab40ff76657d19bba4140e9bb575061dafc3040b0b688670611e0';
export const SOURCE_TREESWAY_GLSL=`
vec3 sourceTreePosition(vec3 sourcePosition, vec4 c12, vec4 c58, vec4 c59, vec4 c60) {
  // Original zero-wind output is exactly rest (1400 real-vertex oracle cases).
  if (c12.z == 0.0 && c12.w == 0.0) return sourcePosition;
  vec4 v0=vec4(sourcePosition,1.0),v5=vec4(0.0);
  vec4 r0=vec4(0.0),r1=vec4(0.0),r2=vec4(0.0),r3=vec4(0.0),r4=vec4(0.0);
  const vec4 c0=vec4(0.0,1.0,2.0,0.5),c13=vec4(0.0);
  const vec4 c14=vec4(100.0,0.5,200.0,0.0),c15=vec4(0.20000000298023224,0.25,2.0,0.5);
  const vec4 c51=vec4(0.0,3.0,2.0,1.2000000476837158),c52=vec4(200.0,600.0,0.0,0.0);
  const vec4 c1=vec4(9.999999747378752e-05,19.0,-2.0,3.0);
  const vec4 c3=vec4(6.2831854820251465,-3.1415927410125732,-2.5239850742764247e-07,2.476090048730839e-05);
  const vec4 c4=vec4(-0.001388839678838849,0.04166664183139801,0.10000000149011612,0.4000000059604645);
  const vec4 c5=vec4(0.15915493667125702,0.3676479160785675,0.34059157967567444,0.25);
  r0.x=((c58.wwww)).x; // word 338
  r0.y=((c59.wwww)).y; // word 341
  r0.z=((c60.wwww)).z; // word 344
  r0.x=(vec4(dot((r0.xyzw).xyz,(c0.yyyy).xyz))).x; // word 347
  r0.yzw=((c12.xyzw)).yzw; // word 351
  r1.x=((r0.xxxx)*(c1.yyyy)+(r0.yyyy)).x; // word 354
  r1.xy=((r1.xxxx)*(c15.xxxx)).xy; // word 359
  r1.zw=((r1.yyyy)*(c51.xxxx)).zw; // word 363
  r1.xyzw=((r1.xyzw)*(c5.xyxz)+(c5.wwww)).xyzw; // word 367
  r1.xyzw=(fract((r1.xyzw))).xyzw; // word 372
  r1.xyzw=((r1.xyzw)*(c3.xxxx)+(c3.yyyy)).xyzw; // word 375
  r1.xyzw=((r1.xyzw)*(r1.xyzw)).xyzw; // word 380
  r2.xyzw=((r1.xyzw)*(c3.zzzz)+(c3.wwww)).xyzw; // word 384
  r2.xyzw=((r1.xyzw)*(r2.xyzw)+(c4.xxxx)).xyzw; // word 389
  r2.xyzw=((r1.xyzw)*(r2.xyzw)+(c4.yyyy)).xyzw; // word 394
  r2.xyzw=((r1.xyzw)*(r2.xyzw)+(-c0.wwww)).xyzw; // word 399
  r1.xyzw=((r1.xyzw)*(r2.xyzw)+(c0.yyyy)).xyzw; // word 404
  r2.xy=((c12.zwzw)*(c12.zwzw)).xy; // word 409
  r2.x=((r2.yyyy)+(r2.xxxx)).x; // word 413
  r2.x=(vec4(inversesqrt(abs((r2.xxxx).x)))).x; // word 417
  r2.x=(vec4(1.0/(r2.xxxx).x)).x; // word 420
  r2.y=((r2.xxxx)+(-c52.xxxx)).y; // word 423
  r2.z=((-c52.xxxx)+(c52.yyyy)).z; // word 427
  r2.z=(vec4(1.0/(r2.zzzz).x)).z; // word 431
  r2.y=(clamp((r2.zzzz)*(r2.yyyy),0.0,1.0)).y; // word 434
  r2.z=((r2.yyyy)*(c1.zzzz)+(c1.wwww)).z; // word 438
  r2.y=((r2.yyyy)*(r2.yyyy)).y; // word 443
  r2.y=((r2.yyyy)*(r2.zzzz)).y; // word 447
  r3.xy=((r2.yyyy)*(r1.zwzw)+(vec4(1.0)-(r2.yyyy))*(r1.xyzw)).xy; // word 451
  r1.xy=((r3.xyzw)+(c4.zwzw)).xy; // word 456
  r2.yzw=((r0.wwww)*(c59.xxyz)).yzw; // word 460
  r2.yzw=((c58.xxyz)*(r0.zzzz)+(r2.xyzw)).yzw; // word 464
  r0.z=(vec4(dot((r2.yzww).xyz,(r2.yzww).xyz))).z; // word 469
  r0.z=(vec4(inversesqrt(abs((r0.zzzz).x)))).z; // word 473
  r0.z=(vec4(1.0/(r0.zzzz).x)).z; // word 476
  r3.xyz=((v0.xyzw)).xyz; // word 479
  r3.xyz=((v5.xyzw)*(c13.xxxx)+(r3.xyzw)).xyz; // word 482
  r1.zw=((r3.xyxy)*(r3.xyxy)).zw; // word 487
  r0.w=((r1.wwww)+(r1.zzzz)).w; // word 491
  r0.w=(vec4(inversesqrt(abs((r0.wwww).x)))).w; // word 495
  r0.w=(vec4(1.0/(r0.wwww).x)).w; // word 498
  r0.zw=(max((r0.xyzw),(c1.xxxx))).zw; // word 501
  r0.z=((r0.wwww)*(r0.zzzz)).z; // word 505
  r0.z=(vec4(1.0/(r0.zzzz).x)).z; // word 509
  r3.w=((c0.xxxx)).w; // word 512
  r0.w=(vec4(dot((r2.yzww).xyz,(r3.xyww).xyz))).w; // word 515
  r0.z=((r0.zzzz)*(abs(r0.wwww))).z; // word 519
  r0.z=(min((r0.zzzz),(c0.yyyy))).z; // word 523
  r0.z=((-r0.zzzz)+(c0.yyyy)).z; // word 527
  r0.z=((r0.zzzz)*(c15.yyyy)).z; // word 531
  r4.y=((c0.yyyy)).y; // word 535
  r1.zw=((r4.yyyy)+(-c14.xyyw)).zw; // word 538
  r1.zw=((r1.xyzw)*(c14.xyxz)).zw; // word 542
  r0.w=(vec4(1.0/(r1.wwww).x)).w; // word 546
  r1.z=(vec4(1.0/(r1.zzzz).x)).z; // word 549
  r4.xyz=((c14.xzzw)*(-c14.ywww)+(r3.zxyw)).xyz; // word 552
  r4.yz=((r4.xyzw)*(r4.xyzw)).yz; // word 557
  r1.w=((r4.zzzz)+(r4.yyyy)).w; // word 561
  r1.w=(vec4(inversesqrt(abs((r1.wwww).x)))).w; // word 565
  r1.w=(vec4(1.0/(r1.wwww).x)).w; // word 568
  r0.w=(clamp((r0.wwww)*(r1.wwww),0.0,1.0)).w; // word 571
  r0.z=((r0.wwww)*(r0.zzzz)).z; // word 575
  r1.w=(vec4(pow(abs((r0.wwww).x),(c51.yyyy).x))).w; // word 579
  r0.w=((r1.wwww)*(c15.wwww)).w; // word 583
  r1.w=(vec4(greaterThanEqual((r4.xxxx),(c0.xxxx)))).w; // word 587
  r1.z=(clamp((r1.zzzz)*(r4.xxxx),0.0,1.0)).z; // word 591
  r3.w=(vec4(pow(abs((r1.zzzz).x),(c51.zzzz).x))).w; // word 595
  r1.z=((r3.wwww)*(c15.yyyy)).z; // word 599
  r4.xyz=((r1.zzzz)*(r2.yzww)).xyz; // word 603
  r0.zw=((r0.xyzw)*(r1.wwww)).zw; // word 607
  r2.yzw=((r0.zzzz)*(r2.xyzw)).yzw; // word 611
  r1.yzw=((r1.yyyy)*(r2.xyzw)).yzw; // word 615
  r1.xyz=((r4.xyzw)*(r1.xxxx)+(r1.yzww)).xyz; // word 619
  r0.z=(vec4(dot((r3.xyzw).xyz,(r3.xyzw).xyz))).z; // word 624
  r0.z=(vec4(inversesqrt(abs((r0.zzzz).x)))).z; // word 628
  r2.yzw=((r0.zzzz)*(r3.xyzx)).yzw; // word 631
  r2.yzw=((r2.xyzw)*(c15.zzzz)).yzw; // word 635
  r2.yzw=((c51.wwww)*(r0.yyyy)+(r2.xyzw)).yzw; // word 639
  r0.xyz=((r0.xxxx)*(c1.yyyy)+(r2.yzww)).xyz; // word 644
  r0.xyz=((r0.xyzw)*(c5.xxxx)+(c5.wwww)).xyz; // word 649
  r0.xyz=(fract((r0.xyzw))).xyz; // word 654
  r0.xyz=((r0.xyzw)*(c3.xxxx)+(c3.yyyy)).xyz; // word 657
  r0.xyz=((r0.xyzw)*(r0.xyzw)).xyz; // word 662
  r2.yzw=((r0.xxyz)*(c3.zzzz)+(c3.wwww)).yzw; // word 666
  r2.yzw=((r0.xxyz)*(r2.xyzw)+(c4.xxxx)).yzw; // word 671
  r2.yzw=((r0.xxyz)*(r2.xyzw)+(c4.yyyy)).yzw; // word 676
  r2.yzw=((r0.xxyz)*(r2.xyzw)+(-c0.wwww)).yzw; // word 681
  r0.xyz=((r0.xyzw)*(r2.yzww)+(c0.yyyy)).xyz; // word 686
  r0.xyz=((r0.xyzw)*(r0.wwww)).xyz; // word 691
  r0.xyz=((r2.xxxx)*(r0.xyzw)+(r1.xyzw)).xyz; // word 695
  r0.xyz=((r0.xyzw)+(r3.xyzw)).xyz; // word 700
  return r0.xyz;
}
`;
