/** Generated by `scripts/stage-source-kill-awards.py` from the shipped
 * `scripts/items/items_game.txt`. Do not edit by hand; run the script instead.
 *
 * The original states the cash a kill pays as the `kill award` attribute of a weapon or
 * of a prefab it inherits from. Fifteen prefabs state one of their own; every other
 * weapon inherits `statted_item_base`'s 300, which is also what both shipped
 * competitive configs set `cash_player_killed_enemy_default` to. Each weapon below
 * carries the owner and the chain its award was resolved through, so the value can be
 * traced back to one row of the shipped file.
 */
export const SOURCE_KILL_AWARD_FORMAT = 'source-kill-award-table-v1';
export const SOURCE_KILL_AWARD_SOURCE_SHA256 = '510e09b68a01d88edba2342972960025fd6484aaaa58365fcf47d8513de79623';
export const SOURCE_KILL_AWARD_DEFAULT = 300;
export const SOURCE_KILL_AWARD_DEFAULT_OWNER = 'statted_item_base';

/** The prefabs that state an award of their own, exactly as the file writes them. */
export const SOURCE_KILL_AWARD_PREFABS: Record<string, number> = {
  "melee": 1500,
  "statted_item_base": 300,
  "weapon_awp_prefab": 100,
  "weapon_bizon_prefab": 600,
  "weapon_cz75a_prefab": 100,
  "weapon_mac10_prefab": 600,
  "weapon_mag7_prefab": 900,
  "weapon_mp5sd_prefab": 600,
  "weapon_mp7_prefab": 600,
  "weapon_mp9_prefab": 600,
  "weapon_nova_prefab": 900,
  "weapon_sawedoff_prefab": 900,
  "weapon_taser_prefab": 0,
  "weapon_ump45_prefab": 600,
  "weapon_xm1014_prefab": 900,
};

/** Every weapon the shipped file defines, with the award it resolves to. */
export const SOURCE_KILL_AWARD_ORIGINAL_WEAPONS: Record<string, { award: number; owner: string; chain: readonly string[] }> = {
  "weapon_ak47": { award: 300, owner: "statted_item_base", chain: ["weapon_ak47", "weapon_ak47_prefab", "rifle", "primary", "weapon_base", "statted_item_base"] },
  "weapon_aug": { award: 300, owner: "statted_item_base", chain: ["weapon_aug", "weapon_aug_prefab", "rifle", "primary", "weapon_base", "statted_item_base"] },
  "weapon_awp": { award: 100, owner: "weapon_awp_prefab", chain: ["weapon_awp", "weapon_awp_prefab"] },
  "weapon_axe": { award: 1500, owner: "melee", chain: ["weapon_axe", "weapon_melee_prefab_noncustomizable", "weapon_melee_prefab", "melee"] },
  "weapon_bayonet": { award: 1500, owner: "melee", chain: ["weapon_bayonet", "melee_unusual", "melee"] },
  "weapon_bizon": { award: 600, owner: "weapon_bizon_prefab", chain: ["weapon_bizon", "weapon_bizon_prefab"] },
  "weapon_breachcharge": { award: 300, owner: "statted_item_base", chain: ["weapon_breachcharge", "weapon_breachcharge_prefab", "equipment", "weapon_base", "statted_item_base"] },
  "weapon_bumpmine": { award: 300, owner: "statted_item_base", chain: ["weapon_bumpmine", "weapon_bumpmine_prefab", "equipment", "weapon_base", "statted_item_base"] },
  "weapon_c4": { award: 300, owner: "statted_item_base", chain: ["weapon_c4", "c4", "weapon_base", "statted_item_base"] },
  "weapon_cz75a": { award: 100, owner: "weapon_cz75a_prefab", chain: ["weapon_cz75a", "weapon_cz75a_prefab"] },
  "weapon_deagle": { award: 300, owner: "statted_item_base", chain: ["weapon_deagle", "weapon_deagle_prefab", "secondary", "weapon_base", "statted_item_base"] },
  "weapon_decoy": { award: 300, owner: "statted_item_base", chain: ["weapon_decoy", "weapon_decoy_prefab", "grenade", "weapon_base", "statted_item_base"] },
  "weapon_diversion": { award: 300, owner: "statted_item_base", chain: ["weapon_diversion", "weapon_diversion_prefab", "weapon_decoy_prefab", "grenade", "weapon_base", "statted_item_base"] },
  "weapon_elite": { award: 300, owner: "statted_item_base", chain: ["weapon_elite", "weapon_elite_prefab", "secondary", "weapon_base", "statted_item_base"] },
  "weapon_famas": { award: 300, owner: "statted_item_base", chain: ["weapon_famas", "weapon_famas_prefab", "rifle", "primary", "weapon_base", "statted_item_base"] },
  "weapon_firebomb": { award: 300, owner: "statted_item_base", chain: ["weapon_firebomb", "weapon_firebomb_prefab", "weapon_molotov_prefab", "weapon_fire_grenade_prefab", "grenade", "weapon_base", "statted_item_base"] },
  "weapon_fists": { award: 1500, owner: "melee", chain: ["weapon_fists", "weapon_fists_prefab", "melee"] },
  "weapon_fiveseven": { award: 300, owner: "statted_item_base", chain: ["weapon_fiveseven", "weapon_fiveseven_prefab", "secondary", "weapon_base", "statted_item_base"] },
  "weapon_flashbang": { award: 300, owner: "statted_item_base", chain: ["weapon_flashbang", "weapon_flashbang_prefab", "grenade", "weapon_base", "statted_item_base"] },
  "weapon_frag_grenade": { award: 300, owner: "statted_item_base", chain: ["weapon_frag_grenade", "weapon_frag_grenade_prefab", "weapon_hegrenade_prefab", "explosive_grenade", "grenade", "weapon_base", "statted_item_base"] },
  "weapon_g3sg1": { award: 300, owner: "statted_item_base", chain: ["weapon_g3sg1", "weapon_g3sg1_prefab", "sniper_rifle", "primary", "weapon_base", "statted_item_base"] },
  "weapon_galilar": { award: 300, owner: "statted_item_base", chain: ["weapon_galilar", "weapon_galilar_prefab", "rifle", "primary", "weapon_base", "statted_item_base"] },
  "weapon_glock": { award: 300, owner: "statted_item_base", chain: ["weapon_glock", "weapon_glock_prefab", "secondary", "weapon_base", "statted_item_base"] },
  "weapon_hammer": { award: 1500, owner: "melee", chain: ["weapon_hammer", "weapon_melee_prefab_noncustomizable", "weapon_melee_prefab", "melee"] },
  "weapon_healthshot": { award: 300, owner: "statted_item_base", chain: ["weapon_healthshot", "weapon_healthshot_prefab", "equipment", "weapon_base", "statted_item_base"] },
  "weapon_hegrenade": { award: 300, owner: "statted_item_base", chain: ["weapon_hegrenade", "weapon_hegrenade_prefab", "explosive_grenade", "grenade", "weapon_base", "statted_item_base"] },
  "weapon_hkp2000": { award: 300, owner: "statted_item_base", chain: ["weapon_hkp2000", "weapon_hkp2000_prefab", "secondary", "weapon_base", "statted_item_base"] },
  "weapon_incgrenade": { award: 300, owner: "statted_item_base", chain: ["weapon_incgrenade", "weapon_incgrenade_prefab", "weapon_fire_grenade_prefab", "grenade", "weapon_base", "statted_item_base"] },
  "weapon_knife": { award: 1500, owner: "melee", chain: ["weapon_knife", "melee"] },
  "weapon_knife_butterfly": { award: 1500, owner: "melee", chain: ["weapon_knife_butterfly", "melee_unusual", "melee"] },
  "weapon_knife_canis": { award: 1500, owner: "melee", chain: ["weapon_knife_canis", "melee_unusual", "melee"] },
  "weapon_knife_cord": { award: 1500, owner: "melee", chain: ["weapon_knife_cord", "melee_unusual", "melee"] },
  "weapon_knife_css": { award: 1500, owner: "melee", chain: ["weapon_knife_css", "melee_unusual", "melee"] },
  "weapon_knife_falchion": { award: 1500, owner: "melee", chain: ["weapon_knife_falchion", "melee_unusual", "melee"] },
  "weapon_knife_flip": { award: 1500, owner: "melee", chain: ["weapon_knife_flip", "melee_unusual", "melee"] },
  "weapon_knife_ghost": { award: 1500, owner: "melee", chain: ["weapon_knife_ghost", "melee"] },
  "weapon_knife_gut": { award: 1500, owner: "melee", chain: ["weapon_knife_gut", "melee_unusual", "melee"] },
  "weapon_knife_gypsy_jackknife": { award: 1500, owner: "melee", chain: ["weapon_knife_gypsy_jackknife", "melee_unusual", "melee"] },
  "weapon_knife_karambit": { award: 1500, owner: "melee", chain: ["weapon_knife_karambit", "melee_unusual", "melee"] },
  "weapon_knife_m9_bayonet": { award: 1500, owner: "melee", chain: ["weapon_knife_m9_bayonet", "melee_unusual", "melee"] },
  "weapon_knife_outdoor": { award: 1500, owner: "melee", chain: ["weapon_knife_outdoor", "melee_unusual", "melee"] },
  "weapon_knife_push": { award: 1500, owner: "melee", chain: ["weapon_knife_push", "melee_unusual", "melee"] },
  "weapon_knife_skeleton": { award: 1500, owner: "melee", chain: ["weapon_knife_skeleton", "melee_unusual", "melee"] },
  "weapon_knife_stiletto": { award: 1500, owner: "melee", chain: ["weapon_knife_stiletto", "melee_unusual", "melee"] },
  "weapon_knife_survival_bowie": { award: 1500, owner: "melee", chain: ["weapon_knife_survival_bowie", "melee_unusual", "melee"] },
  "weapon_knife_t": { award: 1500, owner: "melee", chain: ["weapon_knife_t", "melee"] },
  "weapon_knife_tactical": { award: 1500, owner: "melee", chain: ["weapon_knife_tactical", "melee_unusual", "melee"] },
  "weapon_knife_ursus": { award: 1500, owner: "melee", chain: ["weapon_knife_ursus", "melee_unusual", "melee"] },
  "weapon_knife_widowmaker": { award: 1500, owner: "melee", chain: ["weapon_knife_widowmaker", "melee_unusual", "melee"] },
  "weapon_knifegg": { award: 1500, owner: "melee", chain: ["weapon_knifegg", "melee"] },
  "weapon_m249": { award: 300, owner: "statted_item_base", chain: ["weapon_m249", "weapon_m249_prefab", "machinegun", "primary", "weapon_base", "statted_item_base"] },
  "weapon_m4a1": { award: 300, owner: "statted_item_base", chain: ["weapon_m4a1", "weapon_m4a1_prefab", "rifle", "primary", "weapon_base", "statted_item_base"] },
  "weapon_m4a1_silencer": { award: 300, owner: "statted_item_base", chain: ["weapon_m4a1_silencer", "weapon_m4a1_silencer_prefab", "rifle", "primary", "weapon_base", "statted_item_base"] },
  "weapon_mac10": { award: 600, owner: "weapon_mac10_prefab", chain: ["weapon_mac10", "weapon_mac10_prefab"] },
  "weapon_mag7": { award: 900, owner: "weapon_mag7_prefab", chain: ["weapon_mag7", "weapon_mag7_prefab"] },
  "weapon_melee": { award: 1500, owner: "melee", chain: ["weapon_melee", "weapon_melee_prefab_noncustomizable", "weapon_melee_prefab", "melee"] },
  "weapon_molotov": { award: 300, owner: "statted_item_base", chain: ["weapon_molotov", "weapon_molotov_prefab", "weapon_fire_grenade_prefab", "grenade", "weapon_base", "statted_item_base"] },
  "weapon_mp5sd": { award: 600, owner: "weapon_mp5sd_prefab", chain: ["weapon_mp5sd", "weapon_mp5sd_prefab"] },
  "weapon_mp7": { award: 600, owner: "weapon_mp7_prefab", chain: ["weapon_mp7", "weapon_mp7_prefab"] },
  "weapon_mp9": { award: 600, owner: "weapon_mp9_prefab", chain: ["weapon_mp9", "weapon_mp9_prefab"] },
  "weapon_negev": { award: 300, owner: "statted_item_base", chain: ["weapon_negev", "weapon_negev_prefab", "machinegun", "primary", "weapon_base", "statted_item_base"] },
  "weapon_nova": { award: 900, owner: "weapon_nova_prefab", chain: ["weapon_nova", "weapon_nova_prefab"] },
  "weapon_p250": { award: 300, owner: "statted_item_base", chain: ["weapon_p250", "weapon_p250_prefab", "secondary", "weapon_base", "statted_item_base"] },
  "weapon_p90": { award: 300, owner: "statted_item_base", chain: ["weapon_p90", "weapon_p90_prefab", "smg", "primary", "weapon_base", "statted_item_base"] },
  "weapon_revolver": { award: 300, owner: "statted_item_base", chain: ["weapon_revolver", "weapon_revolver_prefab", "secondary", "weapon_base", "statted_item_base"] },
  "weapon_sawedoff": { award: 900, owner: "weapon_sawedoff_prefab", chain: ["weapon_sawedoff", "weapon_sawedoff_prefab"] },
  "weapon_scar20": { award: 300, owner: "statted_item_base", chain: ["weapon_scar20", "weapon_scar20_prefab", "sniper_rifle", "primary", "weapon_base", "statted_item_base"] },
  "weapon_sg556": { award: 300, owner: "statted_item_base", chain: ["weapon_sg556", "weapon_sg556_prefab", "rifle", "primary", "weapon_base", "statted_item_base"] },
  "weapon_shield": { award: 300, owner: "statted_item_base", chain: ["weapon_shield", "weapon_shield_prefab", "equipment", "weapon_base", "statted_item_base"] },
  "weapon_smokegrenade": { award: 300, owner: "statted_item_base", chain: ["weapon_smokegrenade", "weapon_smokegrenade_prefab", "grenade", "weapon_base", "statted_item_base"] },
  "weapon_snowball": { award: 300, owner: "statted_item_base", chain: ["weapon_snowball", "weapon_snowball_prefab", "grenade", "weapon_base", "statted_item_base"] },
  "weapon_spanner": { award: 1500, owner: "melee", chain: ["weapon_spanner", "weapon_melee_prefab_noncustomizable", "weapon_melee_prefab", "melee"] },
  "weapon_ssg08": { award: 300, owner: "statted_item_base", chain: ["weapon_ssg08", "weapon_ssg08_prefab", "sniper_rifle", "primary", "weapon_base", "statted_item_base"] },
  "weapon_tablet": { award: 300, owner: "statted_item_base", chain: ["weapon_tablet", "weapon_tablet_prefab", "equipment", "weapon_base", "statted_item_base"] },
  "weapon_tagrenade": { award: 300, owner: "statted_item_base", chain: ["weapon_tagrenade", "weapon_tagrenade_prefab", "grenade", "weapon_base", "statted_item_base"] },
  "weapon_taser": { award: 0, owner: "weapon_taser_prefab", chain: ["weapon_taser", "weapon_taser_prefab"] },
  "weapon_tec9": { award: 300, owner: "statted_item_base", chain: ["weapon_tec9", "weapon_tec9_prefab", "secondary", "weapon_base", "statted_item_base"] },
  "weapon_ump45": { award: 600, owner: "weapon_ump45_prefab", chain: ["weapon_ump45", "weapon_ump45_prefab"] },
  "weapon_usp_silencer": { award: 300, owner: "statted_item_base", chain: ["weapon_usp_silencer", "weapon_usp_silencer_prefab", "secondary", "weapon_base", "statted_item_base"] },
  "weapon_xm1014": { award: 900, owner: "weapon_xm1014_prefab", chain: ["weapon_xm1014", "weapon_xm1014_prefab"] },
  "weapon_zone_repulsor": { award: 300, owner: "statted_item_base", chain: ["weapon_zone_repulsor", "weapon_zone_repulsor_prefab", "equipment", "weapon_base", "statted_item_base"] },
};

/** The weapons this build ships, each with the original item it is. The mapping is
 * the staged weapon-effect map's own `prefabs` block, cross-checked here against the
 * `prefab` the shipped file gives that weapon item. */
export const SOURCE_KILL_AWARD_PORT_WEAPONS: Record<string, { originalWeapon: string; award: number; owner: string }> = {
  "awp": { originalWeapon: "weapon_awp", award: 100, owner: "weapon_awp_prefab" },
  "deagle": { originalWeapon: "weapon_deagle", award: 300, owner: "statted_item_base" },
  "glock": { originalWeapon: "weapon_glock", award: 300, owner: "statted_item_base" },
  "m4a4": { originalWeapon: "weapon_m4a1", award: 300, owner: "statted_item_base" },
  "usp": { originalWeapon: "weapon_usp_silencer", award: 300, owner: "statted_item_base" },
  "vandal": { originalWeapon: "weapon_ak47", award: 300, owner: "statted_item_base" },
};

/** The utilities this build can kill with. */
export const SOURCE_KILL_AWARD_PORT_UTILITIES: Record<string, { originalWeapon: string; award: number; owner: string }> = {
  "flash": { originalWeapon: "weapon_flashbang", award: 300, owner: "statted_item_base" },
  "he": { originalWeapon: "weapon_hegrenade", award: 300, owner: "statted_item_base" },
  "smoke": { originalWeapon: "weapon_smokegrenade", award: 300, owner: "statted_item_base" },
};

/** The staged table as one value, so the reader can validate it and so a test can
 * hand it a broken one and watch it refuse. */
export const SOURCE_KILL_AWARD_TABLE = {
  format: SOURCE_KILL_AWARD_FORMAT,
  sourceSha256: SOURCE_KILL_AWARD_SOURCE_SHA256,
  default: { owner: SOURCE_KILL_AWARD_DEFAULT_OWNER, award: SOURCE_KILL_AWARD_DEFAULT },
  prefabAwards: SOURCE_KILL_AWARD_PREFABS,
  weapons: SOURCE_KILL_AWARD_ORIGINAL_WEAPONS,
  portWeapons: SOURCE_KILL_AWARD_PORT_WEAPONS,
  portUtilities: SOURCE_KILL_AWARD_PORT_UTILITIES,
} as const;

export const SOURCE_KILL_AWARD_LIMITATIONS = [
  'The shipped file gives the weapon\'s own award; the mode config scales it by `cash_player_killed_enemy_factor`, which both shipped competitive formats set to 1. A factor other than 1 is not documented by any shipped file, so this build applies the factor the same way it already applied it to the default award.',
  'A weapon this build ships that is not one of the original\'s own (its own VX-9 / FALCON placeholders) keeps the original base award: the shipped file gives no award for a weapon it does not define, and borrowing another class\'s award would be an invented mapping.',
  'The four weapon classes the file distinguishes beyond the default - melee 1500, SMGs 600, shotguns 900, the AWP and CZ75 100, the taser 0 - are staged whole, so a weapon added later resolves without touching this table.',
  ] as const;
