/** Where an original bullet impact lands and what the surface it landed on says.
 *
 * The table this module reads is generated by `scripts/export-source-surface-props.py`
 * from the shipped `scripts/surfaceproperties_cs.txt`, `scripts/decals_subrect.txt`, the
 * `_subrect` decal materials and the map's own faces, and staged by
 * `scripts/stage-source-impact.py`. Nothing here invents a surface, a decal or a sound:
 * a face whose material declares no `$surfaceprop`, a brush whose declared sides
 * disagree, and a surface whose game-material letter the shipped decal table leaves out
 * all resolve to nothing, and the caller draws nothing.
 *
 * This module holds the rules only, so the Node server can share it without importing JSON;
 * the staged table itself is loaded by whoever owns it (the browser bundle and the web root
 * both ship the same bytes, and a test asserts they are identical).
 */

export type SourceImpactAtlas = {
  url: string; width: number; height: number; bytes: number; sha256: string; source: string;
};
export type SourceImpactDecalMaterial = {
  atlas: string; pos: [number, number]; size: [number, number];
  scale: number; scaleVariation: number | null; modelMaterial: string; shader: string;
};
export type SourceImpactDecal = { material: string; weight: number };
export type SourceImpactRow = {
  gameMaterial: string | null; decalGroup: string | null; decals: readonly SourceImpactDecal[];
  bulletImpact: string | null;
};
export type SourceImpactSurfaceSource = 'brushes' | 'displacementChunks' | 'props';
export type SourceImpactTable = {
  build: number; sourceBspSha256: string; atlasBaseUrl: string; soundBaseUrl: string;
  atlases: Record<string, SourceImpactAtlas>;
  decalMaterials: Record<string, SourceImpactDecalMaterial>;
  impact: Record<string, SourceImpactRow>;
  surfaces: Record<SourceImpactSurfaceSource, Record<string, string>>;
  limitations: readonly string[];
};

const SURFACE_SOURCES: readonly SourceImpactSurfaceSource[] = ['brushes', 'displacementChunks', 'props'];
const ATLAS_URL = /^atlas\/[A-Za-z0-9_.-]+\.png$/;

const block = (value: unknown, label: string): Record<string, unknown> => {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw Error(`Original impact ${label} is not a block`);
  return value as Record<string, unknown>;
};
const finite = (value: unknown, label: string): number => {
  if (typeof value !== 'number' || !Number.isFinite(value)) throw Error(`Original impact ${label} is not a number`);
  return value;
};

/** Validates the staged table against the map it is claimed to describe.
 * Every decal an impact row can reach must have a material, and every material must
 * have an atlas whose rectangle fits, so a drawing path can never read past the sheet.
 */
export function loadSourceImpactTable(value: unknown, expected: { build: number; sourceBspSha256: string }): SourceImpactTable {
  const root = block(value, 'table');
  if (root.format !== 'source-impact-table-v1') throw Error('Unsupported original impact table format');
  if (root.build !== expected.build) throw Error('Original impact table build differs');
  if (root.sourceBspSha256 !== expected.sourceBspSha256) throw Error('Original impact table belongs to another map');
  const atlases: SourceImpactTable['atlases'] = {};
  for (const [name, entry] of Object.entries(block(root.atlases, 'atlases'))) {
    const row = block(entry, `atlas ${name}`);
    const url = String(row.url);
    if (!ATLAS_URL.test(url)) throw Error(`Original impact atlas url is not a staged sheet: ${url}`);
    const width = finite(row.width, 'atlas width');
    const height = finite(row.height, 'atlas height');
    if (!(width > 0) || !(height > 0)) throw Error(`Original impact atlas ${name} has no size`);
    atlases[name] = { url, width, height, bytes: finite(row.bytes, 'atlas bytes'),
      sha256: String(row.sha256), source: String(row.source) };
  }
  if (!Object.keys(atlases).length) throw Error('Original impact table ships no atlas');
  const decalMaterials: SourceImpactTable['decalMaterials'] = {};
  for (const [name, entry] of Object.entries(block(root.decalMaterials, 'decalMaterials'))) {
    const row = block(entry, `decal ${name}`);
    const atlas = String(row.atlas);
    const sheet = atlases[atlas];
    if (!sheet) throw Error(`Original impact decal ${name} names an atlas that is not staged`);
    const pos = row.pos as unknown[]; const size = row.size as unknown[];
    if (!Array.isArray(pos) || pos.length !== 2 || !Array.isArray(size) || size.length !== 2)
      throw Error(`Original impact decal ${name} has no rectangle`);
    const [x, y] = pos.map(entry => finite(entry, 'decal rectangle'));
    const [w, h] = size.map(entry => finite(entry, 'decal rectangle'));
    if (!(w > 0) || !(h > 0) || x < 0 || y < 0 || x + w > sheet.width || y + h > sheet.height)
      throw Error(`Original impact decal ${name} sits outside its atlas`);
    const scale = finite(row.scale, 'decal scale');
    if (!(scale > 0)) throw Error(`Original impact decal ${name} has no scale`);
    decalMaterials[name] = { atlas, pos: [x, y], size: [w, h], scale,
      scaleVariation: row.scaleVariation === null ? null : finite(row.scaleVariation, 'decal scale variation'),
      modelMaterial: String(row.modelMaterial), shader: String(row.shader) };
  }
  const impact: SourceImpactTable['impact'] = {};
  for (const [surface, entry] of Object.entries(block(root.impact, 'impact'))) {
    const row = block(entry, `impact ${surface}`);
    const entries = Array.isArray(row.decals) ? row.decals : null;
    if (!entries) throw Error(`Original impact ${surface} has no decal list`);
    const decals = entries.map(entry => {
      const decal = block(entry, `impact ${surface} decal`);
      const material = String(decal.material);
      if (!decalMaterials[material]) throw Error(`Original impact ${surface} names an unstage decal ${material}`);
      const weight = finite(decal.weight, 'decal weight');
      if (!(weight > 0)) throw Error(`Original impact ${surface} decal ${material} has no weight`);
      return { material, weight };
    });
    impact[surface] = { gameMaterial: row.gameMaterial === null ? null : String(row.gameMaterial),
      decalGroup: row.decalGroup === null ? null : String(row.decalGroup), decals,
      bulletImpact: row.bulletImpact === null ? null : String(row.bulletImpact) };
  }
  const surfacesBlock = block(root.surfaces, 'surfaces');
  const surfaces = {} as SourceImpactTable['surfaces'];
  for (const kind of SURFACE_SOURCES) {
    const rows = block(surfacesBlock[kind], `surfaces.${kind}`);
    for (const [key, value] of Object.entries(rows)) {
      if (!impact[String(value)]) throw Error(`Original impact ${kind} ${key} has no impact row`);
    }
    surfaces[kind] = Object.fromEntries(Object.entries(rows).map(([key, value]) => [key, String(value)]));
  }
  if (!Object.keys(surfaces.brushes).length || !Object.keys(surfaces.props).length)
    throw Error('Original impact table is missing one of its surface sources');
  return { build: root.build, sourceBspSha256: String(root.sourceBspSha256), atlasBaseUrl: String(root.atlasBaseUrl),
    soundBaseUrl: String(root.soundBaseUrl), atlases, decalMaterials, impact, surfaces,
    limitations: Array.isArray(root.limitations) ? root.limitations.map(String) : [] };
}

/** The build the staged table was cut from. */
export const SOURCE_IMPACT_BUILD = 12426148;

export const sourceImpactDecalCount = (table: SourceImpactTable, surface: string): number =>
  table.impact[surface]?.decals.length ?? 0;

/** Which face of the map a collision instance is, in the shipped tables' own terms.
 * Each key is the exact field the collision exporter wrote, so a table entry is a
 * statement about one exported instance and never about a neighbouring one.
 */
export function sourceImpactSurfaceKey(source: Record<string, unknown> | null | undefined): { kind: SourceImpactSurfaceSource; key: string } | null {
  if (!source || typeof source !== 'object') return null;
  const layer = source.layer;
  if (layer === 'brush' && Number.isInteger(source.brush)) return { kind: 'brushes', key: String(source.brush) };
  if (layer === 'propPhy' && typeof source.model === 'string') return { kind: 'props', key: source.model };
  if (layer === 'displacement' && Array.isArray(source.grid) && source.grid.length === 3)
    return { kind: 'displacementChunks', key: [...source.grid.map(part => String(part)), String(source.contents)].join(',') };
  return null;
}

/** The original surface property of a collision instance, or null when this build
 * cannot name it. A null here means the impact draws nothing rather than a default.
 */
export function sourceImpactSurfaceFor(table: SourceImpactTable, source: Record<string, unknown> | null | undefined): string | null {
  const found = sourceImpactSurfaceKey(source);
  if (!found) return null;
  return table.surfaces[found.kind][found.key] ?? null;
}

/** The world size of a decal in metres.
 *
 * The shipped set states the size as the decal's own texel extent times its own
 * `$decalscale`, and that reading is not assumed: the same decal also ships as a standalone
 * material for models (`$modelmaterial`), and for 52 of the 76 decals that have both forms
 * the two products are exactly equal while the rest stay within a small factor, which is
 * what an author choosing slightly different numbers for the model variant looks like and
 * what no other reading of the parameter could produce. The original's random draw inside
 * `$decalScaleVariation` is applied as a symmetric range; the shipped data fixes the
 * parameter but not the shape of that draw.
 */
export function sourceImpactDecalSize(material: SourceImpactDecalMaterial, metresPerUnit: number, draw: number): number {
  const variation = material.scaleVariation ?? 0;
  const factor = 1 + variation * (Math.max(0, Math.min(1, draw)) * 2 - 1);
  return material.size[0] * material.scale * factor * metresPerUnit;
}

/** Which decal a shot draws, by the shipped group's weights.
 *
 * Source's emitter picks inside a decal group by the weights `scripts/decals_subrect.txt`
 * carries. The draw is the caller's so both ends and any replay can share one value.
 */
export function sourceImpactDecalPick(row: SourceImpactRow, draw: number): string | null {
  if (!row.decals.length) return null;
  const total = row.decals.reduce((sum, entry) => sum + entry.weight, 0);
  let cursor = Math.max(0, Math.min(1 - Number.EPSILON, draw)) * total;
  for (const entry of row.decals) {
    cursor -= entry.weight;
    if (cursor < 0) return entry.material;
  }
  return row.decals[row.decals.length - 1].material;
}

/** The three draws one shot makes: which decal of the group, how large inside its own
 * `$decalScaleVariation`, and how it is rotated around the normal. Derived from the shot's
 * own identity so every client that receives the same shot draws the same mark, and so an
 * acceptance run can reproduce a mark it saw.
 */
export function sourceImpactDraws(by: string, seq: number): { decal: number; scale: number; roll: number } {
  let seed = 0x811c9dc5 ^ (seq | 0);
  for (let index = 0; index < by.length; index++) {
    seed ^= by.charCodeAt(index);
    seed = Math.imul(seed, 0x01000193);
  }
  const unit = (value: number) => ((value >>> 0) % 1_000_003) / 1_000_003;
  const step = (value: number) => Math.imul(value ^ (value >>> 15), 0x2545f491) + 0x9e3779b9;
  const first = step(seed);
  const second = step(first);
  const third = step(second);
  return { decal: unit(first), scale: unit(second), roll: unit(third) * Math.PI * 2 };
}
