/** Original sidecar receipt; generated by export-source-prop-mips.py. */
export const SOURCE_PROP_MIPS_RECEIPT = {"file": "manifest.json", "bytes": 23259, "sha256": "bc4af131a28acdfe7e11ecebbb6b9e0ffe9c4923e9dda02f50f12c34a28735f1"} as const;
