/** Generated by `scripts/probe-source-weapon-activities.py` from the original
 * view models. Do not edit by hand; run the script instead.
 *
 * A weapon model can carry several sequences for one activity, and a shot chooses
 * between them by the model's own `actweight`: these are those sequences, named as
 * the model names them, for the port to resolve against its own sequence tables.
 */
export const SOURCE_WEAPON_FIRE_VARIANTS = {
  vandal: [
    Object.freeze({ name: "ak47_fire1", weight: 1 }),
    Object.freeze({ name: "ak47_fire2", weight: 1 }),
    Object.freeze({ name: "ak47_fire3", weight: 1 }),
  ],
  m4a4: [
    Object.freeze({ name: "shoot1", weight: 1 }),
    Object.freeze({ name: "shoot2", weight: 1 }),
    Object.freeze({ name: "shoot3", weight: 1 }),
  ],
  glock: [
    Object.freeze({ name: "glock_firesingle", weight: 1 }),
  ],
  usp: [
    Object.freeze({ name: "shoot1", weight: 1 }),
    Object.freeze({ name: "shoot2", weight: 1 }),
    Object.freeze({ name: "shoot3", weight: 1 }),
  ],
  deagle: [
    Object.freeze({ name: "shoot1", weight: 1 }),
    Object.freeze({ name: "shoot2", weight: 1 }),
    Object.freeze({ name: "shoot3", weight: 1 }),
  ],
  awp: [
    Object.freeze({ name: "awp_fire", weight: 1 }),
  ],
} as const;
