/** Generated by scripts/export-source-glock-animation-data.py from original MDL and ELF registration. */
export const SOURCE_GLOCK_ANIMATION_DATA = [
  {
    "sequence": 0,
    "name": "glock_idle",
    "duration": 0.03333333507180214,
    "fadeOut": 0.20000000298023224,
    "flags": 2,
    "events": []
  },
  {
    "sequence": 1,
    "name": "glock_firesingle",
    "duration": 0.4000000059604645,
    "fadeOut": 0.20000000298023224,
    "flags": 2,
    "events": [
      {
        "record": 0,
        "recordEvent": 5001,
        "type": 0,
        "cycle": 0.0,
        "options": "1",
        "name": ""
      },
      {
        "record": 1,
        "recordEvent": 71,
        "type": 1040,
        "cycle": 0.0,
        "options": "",
        "name": "AE_CLIENT_EJECT_BRASS"
      }
    ]
  },
  {
    "sequence": 2,
    "name": "glock_firelast",
    "duration": 0.4000000059604645,
    "fadeOut": 0.20000000298023224,
    "flags": 2,
    "events": [
      {
        "record": 0,
        "recordEvent": 5001,
        "type": 0,
        "cycle": 0.0,
        "options": "21",
        "name": ""
      }
    ]
  },
  {
    "sequence": 3,
    "name": "glock_draw",
    "duration": 1.100000023841858,
    "fadeOut": 0.20000000298023224,
    "flags": 2,
    "events": [
      {
        "record": 0,
        "recordEvent": 5004,
        "type": 0,
        "cycle": 0.0,
        "options": "Weapon_Glock.Draw",
        "name": ""
      },
      {
        "record": 1,
        "recordEvent": 5004,
        "type": 0,
        "cycle": 0.3636363744735718,
        "options": "Weapon_Glock.Slideback",
        "name": ""
      },
      {
        "record": 2,
        "recordEvent": 5004,
        "type": 0,
        "cycle": 0.5151515007019043,
        "options": "Weapon_Glock.Sliderelease",
        "name": ""
      }
    ]
  },
  {
    "sequence": 4,
    "name": "glock_reload",
    "duration": 2.2666666507720947,
    "fadeOut": 0.20000000298023224,
    "flags": 2,
    "events": [
      {
        "record": 0,
        "recordEvent": 5004,
        "type": 0,
        "cycle": 0.1764705926179886,
        "options": "Weapon_Glock.Clipout",
        "name": ""
      },
      {
        "record": 1,
        "recordEvent": 5004,
        "type": 0,
        "cycle": 0.36764705181121826,
        "options": "Weapon_Glock.Clipin",
        "name": ""
      },
      {
        "record": 2,
        "recordEvent": 5004,
        "type": 0,
        "cycle": 0.6470588445663452,
        "options": "Weapon_Glock.Slideback",
        "name": ""
      },
      {
        "record": 3,
        "recordEvent": 5004,
        "type": 0,
        "cycle": 0.7352941036224365,
        "options": "Weapon_Glock.Sliderelease",
        "name": ""
      },
      {
        "record": 4,
        "recordEvent": 54,
        "type": 1041,
        "cycle": 0.4117647111415863,
        "options": "",
        "name": "AE_WPN_COMPLETE_RELOAD"
      }
    ]
  },
  {
    "sequence": 5,
    "name": "lookat01",
    "duration": 6.433333396911621,
    "fadeOut": 0.30000001192092896,
    "flags": 0,
    "events": [
      {
        "record": 0,
        "recordEvent": 73,
        "type": 1040,
        "cycle": 0.0,
        "options": "1",
        "name": "AE_CL_SET_STATTRAK_GLOW"
      },
      {
        "record": 1,
        "recordEvent": 73,
        "type": 1040,
        "cycle": 0.47668394446372986,
        "options": "0",
        "name": "AE_CL_SET_STATTRAK_GLOW"
      },
      {
        "record": 2,
        "recordEvent": 72,
        "type": 1041,
        "cycle": 0.4715026021003723,
        "options": "0.23834",
        "name": "AE_BEGIN_TAUNT_LOOP"
      },
      {
        "record": 3,
        "recordEvent": 5004,
        "type": 0,
        "cycle": 0.010362694039940834,
        "options": "Weapon.WeaponMove1",
        "name": ""
      },
      {
        "record": 4,
        "recordEvent": 5004,
        "type": 0,
        "cycle": 0.9067357778549194,
        "options": "Weapon.WeaponMove3",
        "name": ""
      }
    ]
  }
] as const;
