// Generated by scripts/export-source-overlays.py; original base assets are unchanged.
export const SOURCE_OVERLAYS_RECEIPT = {
  "file": "manifest.json",
  "bytes": 13764,
  "sha256": "bfedb93287aecd0fd3cff952ef60fbf3526523cdc1e680472c1a5fbe87e54738"
} as const;
