import type { Smoke } from './tactics.js';
import type {SourceRuleSetId} from './source-gamemode.js';
import type {SourceWeaponFinish} from './source-weapon-finish.js';
import type {SourceCharacterPoseInput} from './source-character-pose.js';
import type {SourceRifleHandlingState,sourceRifleHandlingShot} from './source-rifle-handling.js';
import type {SourceGlockRuntimeState,SourceGlockBullet} from './source-glock-runtime.js';
import type {SourceDeagleRuntimeState,SourceDeagleBullet} from './source-deagle-runtime.js';
import type {SourceUSPRuntimeState} from './source-usp-runtime.js';
import type {SourcePistolCharacterPoseInput} from './source-pistol-character-pose.js';
import type {SourceAWPRuntimeState,SourceAWPBullet} from './source-awp-runtime.js';
import type {SourceAWPRuntimePose} from './source-awp-runtime-pose.js';
import type {SourceRagdollState} from './source-ragdoll.js';
export type Utility = 'he' | 'smoke' | 'flash';
/** Projectile pose is generated by server physics; older snapshots omit it. */
export type GrenadeSnapshot = {id:number; x:number; y:number; z:number; kind?:Utility;
  rotation?:{x:number;y:number;z:number;w:number}};
export type Team = 'amber' | 'blue';
export type Mode = 'training' | 'demolition';
export type WeaponId = 'vandal' | 'm4a4' | 'glock' | 'usp' | 'deagle' | 'awp' | 'spectre' | 'marshal' | 'sidearm' | 'knife';
export const WEAPONS: Record<
  WeaponId,
  {
    name: string;
    label: string;
    damage: number;
    head: number;
    rate: number;
    mag: number;
    reserve: number;
    reload: number;
    cost: number;
    spread: number;
    recoil: number;
    range: number;
    sourceMaxSpeedUnits?:number;
  }
> = {
  vandal: {
    name: 'AK-47',
    label: '突击步枪',
    damage: 36,
    head: 4,
    rate: 0.1,
    mag: 30,
    reserve: 90,
    reload: 73 / 30,
    cost: 2700,
    spread: 0.008,
    recoil: 0.019,
    range: 8192 * .0254,
    sourceMaxSpeedUnits:215,
  },
  m4a4: {
    name:'M4A4',label:'突击步枪',damage:33,head:4,rate:.09,mag:30,reserve:90,
    reload:92/30,cost:3100,range:8192*.0254,sourceMaxSpeedUnits:225,
    // Legacy scene approximation only. Source uses the separate native accuracy,
    // recoil, punch and authority-owned seed state in source-rifle-handling.
    spread:.0049,recoil:.019,
  },
  glock: {
    name:'Glock-18',label:'半自动 / 三连发手枪',damage:30,head:4,rate:.15,mag:20,reserve:120,
    reload:68/30,cost:200,range:4096*.0254,sourceMaxSpeedUnits:240,
    // Display metadata only; Source command/handling owns actual mode math.
    spread:.002,recoil:0,
  },
  usp: {name:'USP-S',label:'可拆消音器手枪',damage:35,head:4,rate:.17,mag:12,reserve:24,reload:65/30,cost:200,range:4096*.0254,sourceMaxSpeedUnits:240,spread:.0025,recoil:0},
  deagle:{name:'Desert Eagle',label:'半自动大口径手枪',damage:53,head:3.9,rate:.225,mag:7,reserve:35,reload:66/30,cost:700,range:4096*.0254,sourceMaxSpeedUnits:230,spread:.002,recoil:0},
  awp:{name:'AWP',label:'栓动狙击步枪',damage:115,head:4,rate:1.455,mag:5,reserve:30,reload:110/30,cost:4750,range:8192*.0254,sourceMaxSpeedUnits:200,spread:.0002,recoil:0},
  spectre: {
    name: 'VX-9',
    label: '冲锋枪',
    damage: 23,
    head: 2.7,
    rate: 0.075,
    mag: 32,
    reserve: 96,
    reload: 1.7,
    cost: 1400,
    spread: 0.014,
    recoil: 0.014,
    range: 30,
  },
  marshal: {
    name: 'FALCON DMR',
    label: '精确步枪',
    damage: 76,
    head: 2,
    rate: 0.85,
    mag: 8,
    reserve: 32,
    reload: 2.8,
    cost: 3200,
    spread: 0.0015,
    recoil: 0.06,
    range: 100,
  },
  sidearm: {
    name: 'FALCON P12',
    label: '制式手枪',
    damage: 25,
    head: 3,
    rate: 0.23,
    mag: 12,
    reserve: 48,
    reload: 1.4,
    cost: 0,
    spread: 0.011,
    recoil: 0.025,
    range: 35,
  },
  knife: {
    name: '战术刀',
    label: '近战武器',
    damage: 40,
    head: 1,
    rate: 0.45,
    mag: 0,
    reserve: 0,
    reload: 0,
    cost: 0,
    spread: 0,
    recoil: 0,
    range: 2.2,
    sourceMaxSpeedUnits: 250,
  },
};
export type Input = {
  seq: number;
  mx: number;
  mz: number;
  yaw: number;
  pitch: number;
  jump: boolean;
  crouch: boolean;
  /** Source IN_SPEED request; actual walking state is authority-derived. */
  walk?: boolean;
  fire: boolean;
  reload: boolean;
  use: boolean;
  aim: boolean;
  slot: 0 | 1 | 2;
  /** Optional one-shot weapon-selection edge. Undefined preserves older clients. */
  slotSelect?: boolean;
  time: number;
  grenade: boolean;
  /** One-shot Source weapon drop request (bound to X in the browser). */
  drop?: boolean;
  /** Throw-key held state. Inputs that define it use the original hold
   * semantics: the press edge arms the pin-pull preparation and the release
   * edge performs the throw (secondary fire held selects the underhand
   * release, primary+secondary the medium one). Undefined keeps the legacy
   * press-edge instant overhand throw for older clients, bots and fixtures. */
  grenadeHold?: boolean;
  utility: Utility;
};
export const EMPTY_INPUT: Input = {
  seq: 0,
  mx: 0,
  mz: 0,
  yaw: 0,
  pitch: 0,
  jump: false,
  crouch: false,
  walk: false,
  fire: false,
  reload: false,
  use: false,
  aim: false,
  slot: 0,
  time: 0,
  grenade: false,
  drop: false,
  utility: 'he',
};
export type Player = {
  /** Source authority marker and replay state; never accepted from client Input. */
  sourceContract?: 'csgo-player-12426148';
  sourceJumpHeld?: boolean;
  sourceFallVelocity?:number;
  /** Player-owned index0 viewmodel clock, shared across active Source weapons. */
  sourceViewmodelTime?:{animTime:number;previousAnimTime:number};
  sourceWalking?:boolean;
  /** Server-authoritative grenade throw-key hold; true from the press edge
   * until the release edge, driving the original pin-pull preparation layer. */
  sourceGrenadeHold?:boolean;
  sourcePose?: SourceCharacterPoseInput;
  sourcePoseVersion?: string;
  /** Server-authoritative original VPhysics corpse: 16 part positions in
   * actor-local Source units plus the settled flag; absent means the corpse
   * still renders through the clamped Death1 final frame. */
  sourceRagdoll?: SourceRagdollState;
  sourceRifleHandling?:SourceRifleHandlingState;
  sourceGlock?:SourceGlockRuntimeState;
  sourceUSP?:SourceUSPRuntimeState;
  sourceDeagle?:SourceDeagleRuntimeState;
  sourceAWP?:SourceAWPRuntimeState;
  sourceAWPPose?:SourceAWPRuntimePose;
  sourcePistolPose?:SourcePistolCharacterPoseInput;
  skin?: string;
  /** Finish carried by the current primary slot. Kept separate from the
   * player's loadout preference: a picked-up rifle carries its own finish. */
  primaryFinish?: SourceWeaponFinish;
  primaryFinishPicked?: boolean;
  /** Finish carried by the current secondary slot. */
  secondaryFinish?: SourceWeaponFinish;
  secondaryFinishPicked?: boolean;
  sourceWeaponFinish?:SourceWeaponFinish;
  id: string;
  name: string;
  team: Team;
  bot: boolean;
  x: number;
  y: number;
  z: number;
  yaw: number;
  pitch: number;
  vy: number;
  vx: number;
  vz: number;
  shotHeat: number;
  shotIdle: number;
  grounded: boolean;
  /** Authority-traced height of the original map surface under this player while
   * an original reload has the magazine out of the weapon. The ejected magazine
   * is its own prop on every client, and where it lands is a property of the
   * map, so the surface is authoritative instead of a plane through the feet. */
  sourceGroundY?: number;
  crouch: boolean;
  stancePhase: number;
  stanceRate: number;
  stanceTarget: boolean;
  // Optional for pre-locomotion fixtures; authority snapshots always include all five.
  stridePhase?: number;
  strideWeight?: number;
  strideSpeed?: number;
  strideX?: number;
  strideZ?: number;
  hp: number;
  armor: number;
  helmet?:boolean;
  /** Purchased CT equipment, retained only while this combat life survives. */
  defuseKit?:boolean;
  alive: boolean;
  weapon: WeaponId;
  primary: WeaponId | null;
  secondary?:WeaponId;
  /** Every Source player carries a knife; it is not a purchasable firearm. */
  knife?: boolean;
  slot: 0 | 1 | 2;
  ammo: number;
  reserve: number;
  primaryAmmo: number;
  primaryReserve: number;
  pistolAmmo: number;
  pistolReserve: number;
  reload: number;
  cooldown: number;
  kills: number;
  deaths: number;
  money: number;
  ack: number;
  respawn: number;
  use: number;
  grenades: number;
  smokes: number;
  flashes: number;
  flash: number;
  reveal: number;
};
type EventFields = {
  id: number;
  time?: number;
  by?: string;
  target?: string;
  head?: boolean;
  x?: number;
  y?: number;
  z?: number;
  dx?: number;
  dy?: number;
  dz?: number;
  text?: string;
  team?: Team;
  /** The original round cash each side was awarded when this round ended. */
  cash?: { amber: number; blue: number };
  damage?: number;
  seq?: number;
  sourceRifleShot?:ReturnType<typeof sourceRifleHandlingShot>['shot']&{browserAim?:[number,number]};
  sourcePistolShot?:(SourceGlockBullet|SourceDeagleBullet)&{browserAim?:[number,number]};
  sourceAWPShot?:SourceAWPBullet&{browserAim?:[number,number]};
  /** Authoritative Source shot endpoint in world metres, including actor hits and
   * range exhaustion. This is separate from impact, which describes a map face. */
  sourceTracer?:{end:[number,number,number]};
  sourcePistolSoundMode?:0|1;
  sourceWeaponSound?:{weapon:'glock'|'usp'|'deagle'|'awp';event:string};
  /** Where the shot stopped on the original collision, when it stopped there instead of
   * in an actor: the point, the surface normal, and the original surface property of the
   * face that was hit (null when this build has no surface for that face). */
  impact?:{x:number;y:number;z:number;nx:number;ny:number;nz:number;surface:string|null};
};
/** Only a death notice may identify a utility as its weapon. Shot consumers
 * retain their firearm-only contract after narrowing on the event type. */
type EventPayload = {type:'kill';weapon?:WeaponId|Utility} | {
  type:'throw'|'shot'|'weaponSound'|'report'|'smoke'|'flash'|'hit'|'round'|'plant'|'defuse'|'explode'|'step'|'grenade';
  weapon?:WeaponId;
};
export type Event = EventFields & EventPayload;
export type EventDraft = Omit<EventFields,'id'> & EventPayload;
export type Snapshot = {
  droppedWeapons?:import('./source-dropped-weapons.js').SourceDroppedWeaponState[];
  mapId?:string;
  sourceBspSha256?:string;
  simulationVersion?:string;
  tick: number;
  time: number;
  mode: Mode;
  /** The original rule set this match plays; absent or null in the practice mode. */
  rules?: SourceRuleSetId | null;
  phase: 'buy' | 'live' | 'ended' | 'match';
  remaining: number;
  round: number;
  score: { amber: number; blue: number };
  players: Player[];
  events: Event[];
  grenades: GrenadeSnapshot[];
  smokes: Smoke[];
  bomb: {
    planted: boolean;
    /** Unplanted C4 is lying in the world and must be collected by an amber player. */
    dropped?: boolean;
    x: number;
    y: number;
    z: number;
    timer: number;
    site: string;
    carrier: string | null;
  };
  winner: Team | null;
  reason: string;
  you?: string;
  /** Whether the authority would let the player this snapshot is for buy where they stand:
   * the original window *and* the original `func_buyzone` volume. */
  canBuy?: boolean;

};
export function validateInput(value: unknown, lastSeq = -1): Input | null {
  if (!value || typeof value !== 'object') return null;
  const v = value as Record<string, unknown>;
  if(v.walk!==undefined&&typeof v.walk!=='boolean')return null;
  if(v.grenadeHold!==undefined&&typeof v.grenadeHold!=='boolean')return null;
  if(v.drop!==undefined&&typeof v.drop!=='boolean')return null;
  if(v.slotSelect!==undefined&&typeof v.slotSelect!=='boolean')return null;
  for (const k of ['seq', 'mx', 'mz', 'yaw', 'pitch', 'time'])
    if (typeof v[k] !== 'number' || !Number.isFinite(v[k])) return null;
  if (
    !Number.isSafeInteger(v.seq) ||
    Number(v.seq) <= lastSeq ||
    Number(v.seq) > 1e9
  )
    return null;
  if (
    Math.abs(Number(v.mx)) > 1 ||
    Math.abs(Number(v.mz)) > 1 ||
    Math.abs(Number(v.yaw)) > 1e6 ||
    Math.abs(Number(v.pitch)) > Math.PI / 2 + 0.01 ||
    (v.utility !== undefined &&
      v.utility !== 'he' &&
      v.utility !== 'smoke' &&
      v.utility !== 'flash')
  )
    return null;
  return {
    seq: Number(v.seq),
    mx: Number(v.mx),
    mz: Number(v.mz),
    yaw: Number(v.yaw) % (Math.PI * 2),
    pitch: Math.max(-1.5, Math.min(1.5, Number(v.pitch))),
    time: Number(v.time),
    jump: v.jump === true,
    crouch: v.crouch === true,
    walk: v.walk === true,
    fire: v.fire === true,
    reload: v.reload === true,
    use: v.use === true,
    aim: v.aim === true,
    slot: v.slot === 2 ? 2 : v.slot === 1 ? 1 : 0,
    slotSelect: typeof v.slotSelect === 'boolean' ? v.slotSelect : undefined,
    grenade: v.grenade === true,
    drop: v.drop === true,
    grenadeHold: typeof v.grenadeHold === 'boolean' ? v.grenadeHold : undefined,
    utility: v.utility === 'smoke' || v.utility === 'flash' ? v.utility : 'he',
  };
}
export function cleanName(s: unknown) {
  return (
    (typeof s === 'string' ? s : '行动员')
      .replace(/[\p{C}<>]/gu, '')
      .trim()
      .slice(0, 16) || '行动员'
  );
}
