import {describe,it,expect}from'vitest';
import {readFileSync,writeFileSync}from'node:fs';import {resolve}from'node:path';import {createHash}from'node:crypto';
import * as T from'three';import {GLTFLoader}from'three/addons/loaders/GLTFLoader.js';
import {prepareSourceCharacterPose}from'../game/source-character-pose';
import {prepareSourceAWPCharacterPose,sampleSourceAWPCharacterPose,type SourceAWPCharacterPoseInput}from'../game/source-awp-character-pose';
import {prepareSourceAWPWorldPose} from '../game/source-awp-world-pose';
const profiles=[['t','awp'],['ct','awp']]as const;
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),sha=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
export async function awpCharacterFixture(team:'t'|'ct',weapon:'awp'){
 const folder=resolve(`.reference-assets/source-exports/awp-character-candidates/character-${team}-${weapon}`),body=read(folder+'/body-pose-data.json'),world=read(folder+'/world-pose-data.json'),rig=read(folder+'/rig.json'),index=prepareSourceAWPCharacterPose(prepareSourceCharacterPose(body,readFileSync(folder+'/body-frames.f64.bin')),prepareSourceAWPWorldPose(world,readFileSync(folder+'/world-frames.f64.bin'))),reference=read(folder+'/python-reference.json');
 expect(sha(readFileSync(folder+'/body-pose-data.json'))).toBe(reference.bodyDataSHA256);expect(sha(readFileSync(folder+'/world-pose-data.json'))).toBe(reference.worldDataSHA256);
 const bytes=readFileSync(folder+'/character.glb'),size=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(12,true),doc=JSON.parse(Buffer.from(bytes.subarray(20,20+size)).toString()),binary=bytes.subarray(28+size);doc.materials=doc.materials.map((m:{name:string})=>({name:m.name}));delete doc.images;delete doc.textures;delete doc.extensionsUsed;delete doc.extensionsRequired;doc.buffers=[{byteLength:binary.byteLength,uri:'data:application/octet-stream;base64,'+Buffer.from(binary).toString('base64')}];if(!globalThis.ProgressEvent)globalThis.ProgressEvent=class{constructor(type:string,data:object){Object.assign(this,{type},data);}}as unknown as typeof ProgressEvent;
 const gltf=await new GLTFLoader().parseAsync(JSON.stringify(doc),''),nodes=new Map<number,T.Object3D>();for(const[o,a]of gltf.parser.associations)if(a.nodes!==undefined)nodes.set(a.nodes,o as T.Object3D);return{folder,body,world,rig,index,reference,gltf,nodes};
}
describe('original complete AWP body+world graph and independent skins',()=>{
 it.each(profiles)('%s/%s matches independent Python original graph and mathutils bonemerge; actual Three skins retain every IBM',async(team,weapon)=>{
  const f=await awpCharacterFixture(team,weapon),C=new T.Matrix4().set(1,0,0,0,0,0,1,0,0,-1,0,0,0,0,0,1),one=new T.Vector3(1,1,1);let bodyError=0,weaponError=0,threeError=0,vertexError=0,vertexChecks=0;const ibms=new Map<T.SkinnedMesh,number[][]>();f.gltf.scene.traverse(o=>{if(o instanceof T.SkinnedMesh)ibms.set(o,o.skeleton.boneInverses.map(m=>m.elements.slice()));});
  for(const c of f.reference.cases){const got=sampleSourceAWPCharacterPose(f.index,c.input as SourceAWPCharacterPoseInput);expect(got.magazineVisible).toBe(c.magazineVisible);for(const role of ['body','world']as const){const defs=role==='body'?f.body.mainBones:f.world.bones,expected=role==='body'?c.bodyWorldMatrices:c.weaponWorldMatrices,actual=role==='body'?got.body.sourceWorldMatrices:got.sourceWeaponWorldMatrices;
   for(let i=0;i<defs.length;i++)for(let col=0;col<4;col++)for(let row=0;row<4;row++){const d=Math.abs(actual[i*16+col*4+row]-expected[i][row][col]);if(role==='body')bodyError=Math.max(bodyError,d);else weaponError=Math.max(weaponError,d);}
   for(const r of f.rig.mappings[role].joints){const b=f.nodes.get(r.gltfNode)!;if(role==='body'){b.position.fromArray(got.body.renderLocalPositions,r.bone*3);b.quaternion.fromArray(got.body.renderLocalQuaternions,r.bone*4);b.scale.copy(one);}else{b.matrixAutoUpdate=false;b.matrix.fromArray(got.weaponRenderLocalMatrices,r.bone*16);b.matrixWorldNeedsUpdate=true;}}
  }
  f.gltf.scene.updateMatrixWorld(true);
  for(const role of ['body','world']as const)for(const r of f.rig.mappings[role].joints){const gotMatrix=f.nodes.get(r.gltfNode)!.matrixWorld,expected=C.clone().multiply(new T.Matrix4().fromArray(role==='body'?got.body.sourceWorldMatrices:got.sourceWeaponWorldMatrices,r.bone*16));threeError=Math.max(threeError,...gotMatrix.elements.map((v,i)=>Math.abs(v-expected.elements[i])));}
  // Independent weighted skin calculation uses Python source worlds and the
  // original IBM; Three's actual applyBoneTransform is the observation.
  for(const [mesh]of ibms){const role=mesh.skeleton.bones.length===f.body.mainBones.length?'body':'world',mapping=f.rig.mappings[role],inverse=new Map<number,number>();for(const r of mapping.joints)inverse.set(r.skinJoint,r.bone);const pos=mesh.geometry.getAttribute('position'),ids=mesh.geometry.getAttribute('skinIndex'),weights=mesh.geometry.getAttribute('skinWeight');for(let v=0;v<pos.count;v+=Math.max(1,Math.floor(pos.count/13))){const original=new T.Vector3().fromBufferAttribute(pos,v),expected=new T.Vector3();for(let j=0;j<4;j++){const weight=weights.getComponent(v,j);if(!weight)continue;const id=ids.getComponent(v,j),b=inverse.get(id)!,rows=(role==='body'?c.bodyWorldMatrices:c.weaponWorldMatrices)[b],wm=new T.Matrix4().set(...rows.flat()as Parameters<T.Matrix4['set']>);expected.addScaledVector(original.clone().applyMatrix4(C.clone().multiply(wm).multiply(mesh.skeleton.boneInverses[id])),weight);}const actual=mesh.applyBoneTransform(v,original.clone());vertexError=Math.max(vertexError,actual.distanceTo(expected));vertexChecks++;}}
  }
  expect(bodyError).toBeLessThan(.00015);expect(weaponError).toBeLessThan(.00015);expect(threeError).toBeLessThan(1e-9);expect(vertexError).toBeLessThan(.0002);for(const[mesh,original]of ibms)expect(mesh.skeleton.boneInverses.map(m=>m.elements)).toEqual(original);
  writeFileSync(f.folder+'/pose-verification.json',JSON.stringify({status:'passed-complete-awp-character-graph',modelSHA256:sha(readFileSync(f.folder+'/character.glb')),bodyDataSHA256:f.reference.bodyDataSHA256,worldDataSHA256:f.reference.worldDataSHA256,maximumMathutilsFloat32DeviationSourceUnits:Math.max(...f.reference.cases.map((c:{maxMathutilsFloat32MatrixDeviation:number})=>c.maxMathutilsFloat32MatrixDeviation)),cases:f.reference.caseCount,bodyBones:f.body.mainBones.length,worldBones:f.world.bones.length,maxBodyPythonFloat64MatrixErrorSourceUnits:bodyError,maxWorldPythonFloat64MatrixErrorSourceUnits:weaponError,maxThreeMatrixErrorSourceUnits:threeError,maxThreeSkinVertexErrorSourceUnits:vertexError,independentVertexChecks:vertexChecks,exactOriginalIBM:true,originalAWPBodyAndWorldGraph:true},null,2)+'\n');
 });
});
