import {captureSourceRagdollPose,sourceRagdollRestWorldMatrices,computeSourceRagdollRest,bindSourceRagdoll,parseSourceRagdollData} from '../game/source-ragdoll';
import{describe,it,expect,vi}from'vitest';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{resolve}from'node:path';import*as T from'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';
import{loadSourceDeagleCharacter,type SourceDeagleCharacterLoadOptions}from'../game/source-deagle-character';import{createSourceWorldDeagleMaterial}from'../game/source-deagle-character-surfaces';
mkdirSync('output/fidelity-character',{recursive:true});
const profiles=[['t','deagle'],['ct','deagle']]as const;
async function fixture(team:'t'|'ct',weapon:'deagle'){
 const directory=resolve(`public/source/csgo-12426148/character-${team}-${weapon}`),buffers=new Map<string,Uint8Array>([['manifest.json',readFileSync(directory+'/manifest.json')]]),manifest=JSON.parse(Buffer.from(buffers.get('manifest.json')!).toString());for(const f of manifest.files)buffers.set(f.path,readFileSync(directory+'/'+f.path));buffers.set('../ragdoll/ragdoll-data.json',readFileSync('public/source/csgo-12426148/ragdoll/ragdoll-data.json'));
 const bytes=buffers.get(manifest.model)!,size=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(12,true),doc=JSON.parse(Buffer.from(bytes.subarray(20,20+size)).toString()),binary=bytes.subarray(28+size);doc.materials=doc.materials.map((m:{name:string})=>({name:m.name}));delete doc.images;delete doc.textures;delete doc.extensionsUsed;delete doc.extensionsRequired;doc.buffers=[{byteLength:binary.byteLength,uri:'data:application/octet-stream;base64,'+Buffer.from(binary).toString('base64')}];if(!globalThis.ProgressEvent)globalThis.ProgressEvent=class{constructor(type:string,data:object){Object.assign(this,{type},data);}}as unknown as typeof ProgressEvent;const gltf=await new GLTFLoader().parseAsync(JSON.stringify(doc),'');return{directory,buffers,manifest,gltf};
}
function mock(f:Awaited<ReturnType<typeof fixture>>,corrupt?:string,abort?:AbortController){const textures:T.Texture[]=[],disposed:T.Texture[]=[];vi.stubGlobal('crypto',undefined);vi.stubGlobal('fetch',vi.fn(async(url:string,o?:RequestInit)=>{expect(o?.cache).toBe('no-cache');const key=url.replace('/fixture/',''),b=Uint8Array.from(f.buffers.get(key)!);if(key===corrupt)b[b.length-1]^=1;return new Response(new Blob([b]));}));const parse=vi.spyOn(GLTFLoader.prototype,'parseAsync').mockResolvedValue(f.gltf),texture=vi.spyOn(T.TextureLoader.prototype,'loadAsync').mockImplementation(async()=>{const t=new T.Texture<HTMLImageElement>();textures.push(t);t.addEventListener('dispose',()=>disposed.push(t));abort?.abort();return t;});return{textures,disposed,restore(){parse.mockRestore();texture.mockRestore();vi.unstubAllGlobals();}};}
describe('complete original pistol character owners',()=>{
 it.each(profiles)('%s/%s keeps authoritative full graph, separate skins and shared immutable resources',async(team,weapon)=>{const f=await fixture(team,weapon),m=mock(f);try{const owner=await loadSourceDeagleCharacter({team,baseUrl:'/fixture'}),a=owner.createActor(),b=owner.createActor();expect(m.textures).toHaveLength(11);expect(Object.values(owner.hashVerified).every(Boolean)).toBe(true);expect(owner.hashVerified['manifest.json']).toBe(true);expect(a.bodyBones.length).toBe(team==='t'?71:74);expect(a.worldBones.length).toBe(93);expect(a.bodyBones[0]).not.toBe(b.bodyBones[0]);expect(a.worldBones[0]).not.toBe(b.worldBones[0]);owner.disposeActor(a);expect(b.status).toBe('awaiting-authority');expect(m.disposed).toHaveLength(0);
  const folder=resolve(`.reference-assets/source-exports/deagle-candidates/character-${team}-${weapon}`),refs=JSON.parse(readFileSync(folder+'/python-reference.json','utf8')),C=new T.Matrix4().set(1,0,0,0,0,0,1,0,0,-1,0,0,0,0,0,1);let maximum=0,samples=0;const originalIBMs=new Map<T.SkinnedMesh,number[][]>();b.model.traverse(o=>{if(o instanceof T.SkinnedMesh)originalIBMs.set(o,o.skeleton.boneInverses.map(v=>v.elements.slice()));});
  for(const c of refs.cases){const state={x:7,y:2,z:-31,yaw:.713,sourceContract:'csgo-player-12426148',sourcePoseVersion:owner.manifest.poseVersion,sourcePistolPose:c.input},got=owner.updateActor(b,state)!;expect(b.status).toBe('ready');expect(owner.updateActor(b,state)).toBe(got);const actor=new T.Matrix4().makeRotationY(state.yaw+Math.PI/2).setPosition(state.x,state.y,state.z).multiply(new T.Matrix4().makeScale(.0254,.0254,.0254)).multiply(C);
  for(const[role,bones,refs]of[['body',b.bodyBones,c.bodyWorldMatrices],['world',b.worldBones,c.weaponWorldMatrices]]as const){for(let i=0;i<bones.length;i++){const expected=actor.clone().multiply(new T.Matrix4().set(...refs[i].flat()as Parameters<T.Matrix4['set']>));maximum=Math.max(maximum,...expected.elements.map((v,k)=>Math.abs(v-bones[i].matrixWorld.elements[k])));}expect(role).toBeTruthy();}
  expect(b.bodygroups.magazine.every(o=>o.visible===c.input.magazineVisible)).toBe(true);expect(b.bodygroups.silencer.every(o=>o.visible===c.input.silencerVisible)).toBe(true);const attachment=owner.attachment(b,'weapon_hand_R');expect(attachment).not.toBeNull();expect(attachment!.elements.every(Number.isFinite)).toBe(true);samples++;}
  // The shipped owner must render the complete authority, including a death
  // during a reload, and keep the weapon merged to the corpse's hands.
  for(const c of refs.cases){
    const state={x:7,y:2,z:-31,yaw:.713,sourceContract:'csgo-player-12426148',sourcePoseVersion:owner.manifest.poseVersion,sourcePistolPose:c.input};
    owner.updateActor(b,state);const before=[...b.bodyBones,...b.worldBones].map(bone=>bone.getWorldPosition(new T.Vector3()));
    const ri=bindSourceRagdoll(parseSourceRagdollData(JSON.parse(readFileSync('public/source/csgo-12426148/ragdoll/ragdoll-data.json','utf8'))),owner.poseIndex.body);
    const restPose=captureSourceRagdollPose(owner.poseIndex.body,state),rest=computeSourceRagdollRest(ri,sourceRagdollRestWorldMatrices(ri,restPose));
    const corpse={positions:Array.from(rest.positions),quaternions:Array.from(rest.quaternions),restPose,settled:true};
    owner.updateActor(b,{...state,sourceRagdoll:corpse});
    for(const [i,bone]of [...b.bodyBones,...b.worldBones].entries())expect(bone.getWorldPosition(new T.Vector3()).distanceTo(before[i])).toBeLessThan(1e-6);
    corpse.positions=corpse.positions.map((v,i)=>v+(i%3===0?20:0));owner.updateActor(b,{...state,sourceRagdoll:corpse});
    for(const [i,bone]of b.bodyBones.entries())expect(bone.getWorldPosition(new T.Vector3()).distanceTo(before[i])).toBeCloseTo(.508,5);
  }
  expect(maximum).toBeLessThan(1e-9);for(const[mesh,original]of originalIBMs)expect(mesh.skeleton.boneInverses.map(m=>m.elements)).toEqual(original);expect(owner.updateActor(b,{x:0,y:0,z:0,yaw:0,sourceContract:'csgo-player-12426148',sourcePoseVersion:'rifle',sourcePistolPose:refs.cases[0].input})).toBeNull();expect(b.root.visible).toBe(false);
  // An actor with no authoritative pose reports no attachment rather than a point.
  expect(owner.attachment(b,'weapon_hand_R')).toBeNull();
  owner.dispose();owner.dispose();expect(b.status).toBe('disposed');expect(new Set(m.disposed)).toEqual(new Set(m.textures));expect(m.disposed.length).toBe(11);expect(()=>owner.createActor()).toThrow(/disposed/);writeFileSync(resolve('output/fidelity-character/'+team+'-'+weapon+'-owner-verification.json'),JSON.stringify({status:'passed-original-pistol-character-owner',poseVersion:owner.manifest.poseVersion,samples,maxIndependentPythonBrowserMatrixErrorMeters:maximum,bodyBones:b.bodyBones.length,worldBones:b.worldBones.length,originalIBMsUnchanged:true,independentClones:true,explicitFullGraph:true,shaVerifiedOnInsecureHTTP:true,ownedTexturesReleased:11,shaderGPUStatus:'pending'},null,2)+'\n');
 }finally{m.restore();}});
 it.each(['manifest.json','body-frames.f64.bin','textures/pist_deagle_exponent.png'])('rejects corrupt %s and reclaims all completed resources',async corrupt=>{const f=await fixture('ct','deagle'),m=mock(f,corrupt);try{await expect(loadSourceDeagleCharacter({team:'ct',baseUrl:'/fixture'})).rejects.toThrow(/SHA mismatch/);expect(new Set(m.disposed)).toEqual(new Set(m.textures));}finally{m.restore();}});
 it.each(profiles)('%s/%s drops the original magazine prop at the reload display event',async(team,weapon)=>{const f=await fixture(team,weapon),m=mock(f);try{const owner=await loadSourceDeagleCharacter({team,baseUrl:'/fixture'}),a=owner.createActor(),refs=JSON.parse(readFileSync(resolve(`.reference-assets/source-exports/deagle-candidates/character-${team}-${weapon}`)+'/python-reference.json','utf8')),base=refs.cases[0].input;
  const state=(magazineVisible:boolean)=>({x:7,y:2,z:-31,yaw:.713,grounded:true,sourceContract:'csgo-player-12426148',sourcePoseVersion:owner.manifest.poseVersion,sourcePistolPose:{...base,magazineVisible}});
  owner.updateActor(a,state(true));expect(owner.takeMagazineDrop(a)).toBeNull();
  owner.updateActor(a,state(false));
  const drop=owner.takeMagazineDrop(a)!;expect(drop).not.toBeNull();expect(drop.key).toBe(weapon);expect(drop.floorY).toBe(2);expect(drop.forward.y).toBe(0);
  // The prop matrix must put every bind-pose magazine vertex where the weapon draws it.
  const mesh=a.bodygroups.magazine[0]as T.SkinnedMesh,positions=mesh.geometry.getAttribute('position');
  for(const vertex of [0,positions.count-1]){const expected=new T.Vector3().fromBufferAttribute(positions,vertex);mesh.applyBoneTransform(vertex,expected).applyMatrix4(mesh.matrixWorld);const actual=new T.Vector3().fromBufferAttribute(positions,vertex).applyMatrix4(drop.matrix);expect(actual.distanceTo(expected)).toBeLessThan(1e-6);}
  expect(owner.takeMagazineDrop(a)).toBeNull();
  owner.updateActor(a,state(true));expect(owner.takeMagazineDrop(a)).toBeNull();
  owner.dispose();
 }finally{m.restore();}});
 it('aborted image decode does not leak late fulfilled textures',async()=>{const f=await fixture('t','deagle'),abort=new AbortController(),m=mock(f,undefined,abort);try{await expect(loadSourceDeagleCharacter({team:'t',baseUrl:'/fixture',signal:abort.signal})).rejects.toThrow();expect(m.textures.length).toBeGreaterThan(0);expect(new Set(m.disposed)).toEqual(new Set(m.textures));}finally{m.restore();}});
});
