import {describe,it,expect} from 'vitest';import {readFileSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';import {createHash} from 'node:crypto';
import {prepareSourceDeagleWorldPose,sampleSourceDeagleWorldPose,sourceDeagleWorldCycleRate,sourceDeagleAutoLayerRequests,type SourceDeagleWorldParameters,type SourceDeagleWorldPoseInput}from '../game/source-deagle-character-pose';
import {sampleSourceSequence}from '../game/source-character-pose';
function fixture(w:'deagle'){const folder=resolve(`.reference-assets/source-exports/deagle-candidates/${w}-world/continuous`),raw=readFileSync(folder+'/pose-data.json'),data=JSON.parse(raw.toString()),bytes=readFileSync(folder+'/frames.f64.bin'),reference=JSON.parse(readFileSync(folder+'/python-reference.json','utf8'));expect(createHash('sha256').update(raw).digest('hex')).toBe(reference.sourceDataSHA256);expect(createHash('sha256').update(bytes).digest('hex')).toBe(data.frames.sha256);return{folder,data,bytes,reference,index:prepareSourceDeagleWorldPose(data,bytes)};}
describe('original complete pistol world pose graph',()=>{
 it.each(['deagle']as const)('%s preserves original 9way corners and full ordered graph/overlays against independent Python',w=>{const f=fixture(w);let localError=0,worldError=0,corners=0;
  for(const c of f.reference.cases){const got=sampleSourceDeagleWorldPose(f.index,c.input as SourceDeagleWorldPoseInput);expect(got.autoLayers.map(l=>l.weight)).toEqual(c.layerWeights);for(let i=0;i<f.data.bones.length;i++){for(let a=0;a<3;a++)localError=Math.max(localError,Math.abs(got.positions[i*3+a]-c.positions[i][a]));for(let a=0;a<4;a++)localError=Math.max(localError,Math.abs(got.quaternions[i*4+a]-c.quaternions[i][a]));for(let col=0;col<4;col++)for(let row=0;row<4;row++)worldError=Math.max(worldError,Math.abs(got.sourceWorldMatrices[i*16+col*4+row]-c.sourceWorldMatrices[i][row][col]));}}
  for(const layer of f.index.named.get('pistol_aim_t')!.autoLayers){const s=f.index.sequences.get(layer.sequence_id)!;for(let y=0;y<3;y++)for(let x=0;x<3;x++){const got=sampleSourceSequence(f.index.core,s.index,0,{body_yaw:s.poseKeys[x],body_pitch:s.poseKeys[3+y]}),frame=f.index.core.frames.get(s.animationIndices[x+y*3])!;for(let b=0;b<f.index.core.boneCount;b++){for(let k=0;k<3;k++)expect(got.positions[b*3+k]).toBe(frame.positions[b*3+k]);const dot=[0,1,2,3].reduce((sum,k)=>sum+got.quaternions[b*4+k]*frame.quaternions[b*4+k],0);expect(Math.abs(Math.abs(dot)-1)).toBeLessThan(1e-12);}corners++;}}
  expect(localError).toBeLessThan(1e-10);expect(worldError).toBeLessThan(.0001);expect(corners).toBe(45);for(const s of f.data.sequences.filter((s:{groupSize:number[];autoLayers:unknown[]})=>s.groupSize.every(n=>n===1)&&s.autoLayers.length===0)){const d=f.index.core.frames.get(s.animationIndices[0])!.descriptor;expect(sourceDeagleWorldCycleRate(f.index,s.name,f.reference.cases[0].input.parameters)).toBe(d.frames>1?d.fps/(d.frames-1):0);}expect(()=>sourceDeagleWorldCycleRate(f.index,'pistol_aim_t',f.reference.cases[0].input.parameters)).toThrow(/ordinary/);writeFileSync(f.folder+'/verification.json',JSON.stringify({status:'passed-original-complete-world-graph',pythonCases:f.reference.caseCount,raw9wayCorners:corners,maximumLocalComponentError:localError,maximumPythonMathutilsWorldMatrixErrorSourceUnits:worldError,allFiveAutoLayersConsumed:true,originalOrderRetained:true},null,2)+'\n');
 });
 it('rejects unknown layer flags or broken references rather than dropping auto layers',()=>{const f=fixture('deagle');for(const mutation of [(d:typeof f.data)=>d.sequences.find((s:{name:string})=>s.name==='pistol_aim_t').autoLayers[0].flags=0,(d:typeof f.data)=>d.sequences.find((s:{name:string})=>s.name==='pistol_aim_t').autoLayers[0].sequence_id=999]){const d=structuredClone(f.data);mutation(d);expect(()=>prepareSourceDeagleWorldPose(d,f.bytes)).toThrow();}});
 it('requires all explicit world aim weights and preserves input/index during rejected samples',()=>{const f=fixture('deagle');expect(()=>sampleSourceDeagleWorldPose(f.index,{parameters:{body_yaw:0,body_pitch:0}as SourceDeagleWorldParameters})).toThrow(/Missing/);expect(f.index.named.get('pistol_aim_t')!.autoLayers).toHaveLength(5);});
});
