async page=>{
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const evidence={errors},read=()=>page.evaluate(()=>({handling:window.__BREACHLINE__.handlingAudit(),audit:window.__BREACHLINE__.assetAudit(),audio:window.__BREACHLINE__.audioAudit()}));
 const save=()=>page.evaluate(e=>window.__SOURCE_DEAGLE_GAMEPLAY_EVIDENCE__=e,evidence),own=r=>r.handling.authority.player;
 const ready=()=>page.waitForFunction(()=>{const p=window.__BREACHLINE__.handlingAudit().authority.player;return p?.weapon==='deagle'&&p.cooldown===0&&!p.sourceDeagle.command.reloading;});
 const tap=async()=>{await page.mouse.down();await page.waitForTimeout(60);await page.mouse.up();};
 await page.goto('http://192.168.1.100:27019/?map=de_dust2');const start=page.getByRole('button',{name:/^开始人机训练/});await start.waitFor({state:'visible',timeout:120000});await page.getByRole('textbox',{name:'呼号',exact:true}).fill('Deagle Proof');await start.click();await page.waitForFunction(()=>!!document.pointerLockElement);
 await page.keyboard.press('KeyB');const shop=page.getByRole('dialog').filter({hasText:'购买装备'});await shop.waitFor({state:'visible'});await shop.getByRole('button',{name:/^Desert Eagle/}).click();await page.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player?.weapon==='deagle'&&window.__BREACHLINE__.assetAudit().firstPerson?.detail?.weapon==='deagle');evidence.draw=await read();await save();
 await shop.getByRole('button',{name:'Close',exact:true}).click();await page.waitForFunction(()=>!!document.pointerLockElement);await ready();await page.screenshot({path:'output/playwright/source-r4-deagle-t-draw-live.png'});
 await page.mouse.down();await page.waitForTimeout(600);await page.mouse.up();evidence.single=await read();await save();if(own(evidence.single).ammo!==6)throw Error('Deagle held trigger fired more than once');
 await page.keyboard.press('KeyR');await page.waitForTimeout(300);evidence.reload=await read();await page.screenshot({path:'output/playwright/source-r4-deagle-t-reload-live.png'});
 await page.waitForFunction(()=>{const p=window.__BREACHLINE__.handlingAudit().authority.player;return p.ammo===7&&p.sourceDeagle.command.reloading;});evidence.earlyReload=await read();await tap();evidence.blocked=await read();await save();if(own(evidence.blocked).ammo!==7||own(evidence.earlyReload).cooldown<=0)throw Error('Deagle early reload unlocked attack');await ready();
 for(let n=0;n<7;n++){await ready();await tap();if(n===6){evidence.lastRound=await read();await save();await page.screenshot({path:'output/playwright/source-r4-deagle-t-last-round.png'});}}
 if(own(evidence.lastRound).ammo!==0||evidence.lastRound.audit.firstPerson.detail.sequence!=='shoot_empty')throw Error('Deagle last-round original sequence failed');
 await page.waitForFunction(()=>{const p=window.__BREACHLINE__.handlingAudit().authority.player;return p.ammo===7&&p.sourceDeagle.command.reloading;});evidence.autoReload=await read();await ready();
 await page.keyboard.press('KeyF');await page.waitForTimeout(750);evidence.inspect=await read();await page.screenshot({path:'output/playwright/source-r4-deagle-t-inspect-live.png'});await save();
 await page.keyboard.press('Digit1');await page.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player.weapon==='vandal');evidence.primary=await read();await page.keyboard.press('Digit2');await ready();evidence.redraw=await read();
 await page.keyboard.down('ShiftLeft');await page.keyboard.down('KeyW');await page.waitForTimeout(600);evidence.walk=await read();await page.keyboard.up('KeyW');await page.keyboard.down('ControlLeft');await page.waitForTimeout(300);evidence.crouch=await read();await page.keyboard.up('ControlLeft');await page.keyboard.up('ShiftLeft');await save();
 if(evidence.draw.audit.firstPerson.armsProfile!=='t_arms'||!evidence.draw.audit.firstPerson.hashVerified||evidence.draw.audit.firstPerson.detail.weapon!=='deagle')throw Error('Original T Deagle owner missing');
 if(evidence.reload.audit.firstPerson.detail.sequence!=='reload'||evidence.inspect.audit.firstPerson.detail.sequence!=='lookat01')throw Error('Original Deagle reload/inspect not sampled');
 if(own(evidence.earlyReload).reserve!==34||!own(evidence.earlyReload).sourceDeagle.command.reloadVisComplete||own(evidence.autoReload).reserve!==27)throw Error('Deagle original reload ammunition incorrect');
 if(own(evidence.primary).ammo!==30||own(evidence.redraw).ammo!==7||!own(evidence.walk).sourceWalking||!own(evidence.crouch).crouch)throw Error('Deagle inventory or movement failed');
 if(!evidence.single.handling.shots.some(e=>e.sourcePistolShot?.weapon==='deagle')||!evidence.single.audio.recentSourceEvents.some(e=>['source_deagle_13','source_deagle_14'].includes(e.key)))throw Error('Original Deagle bullet/audio missing');
 if(evidence.inspect.audit.sourcePistolFx?.muzzleAttachment!=='1'||evidence.inspect.audit.map.propLighting.totalAppliedMeshes!==2640)throw Error('Original attachment or map regression');
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'返回主菜单',exact:true}).waitFor({state:'visible'});await page.getByRole('button',{name:'返回主菜单',exact:true}).click();evidence.cleanup=await page.evaluate(()=>fetch('/api/rooms').then(r=>r.json()));evidence.status='passed';evidence.scope='Actual training UI purchase and T arms, semi-auto, original last round, early/manual/auto reload, separate inventory, inspection, walk/crouch and original WAV.';await save();if(errors.length)throw Error(errors.join('\n'));
}
