async (page) => {
  const errors=[], sockets=[];
  const observe = p => {
    p.on('pageerror', e=>errors.push(String(e)));
    p.on('console', m=>{if(m.type()==='error')errors.push(m.text());});
    p.on('websocket', ws=>sockets.push(ws.url()));
  };
  observe(page);
  const pause = async p => {
    await p.bringToFront();
    if (!(await p.getByRole('button',{name:'返回主菜单',exact:true}).isVisible())) await p.keyboard.press('Escape');
    await p.getByRole('button',{name:'返回主菜单',exact:true}).waitFor({state:'visible'});
  };
  await page.goto('http://192.168.1.100:27019/?map=de_dust2');
  await page.waitForFunction(()=>window.__BREACHLINE__?.assetAudit()?.counterTerrorist?.id?.startsWith('csgo-ct-ak-12426148')&&window.__BREACHLINE__?.assetAudit()?.map?.propLighting?.appliedMeshes===2325,null,{timeout:120000});
  await page.getByRole('textbox',{name:'呼号',exact:true}).fill('LAN Host');
  await page.getByRole('button',{name:'创建房间',exact:true}).click();
  await page.getByLabel('房间名称',{exact:true}).fill('Dust2 R4 双客户端验收');
  await page.getByRole('button',{name:'创建并进入房间',exact:true}).click();
  await page.waitForFunction(()=>window.__BREACHLINE__?.snapshot()?.players.some(p=>p.name==='LAN Host'));
  await pause(page);
  const hostInitial=await page.evaluate(()=>window.__BREACHLINE__.snapshot());
  const rooms=await page.evaluate(()=>fetch('/api/rooms').then(r=>r.json()));
  const peer=await page.context().newPage(); observe(peer);
  await peer.goto('http://192.168.1.100:27019/?map=de_dust2');
  await peer.waitForFunction(()=>window.__BREACHLINE__?.assetAudit()?.counterTerrorist?.id?.startsWith('csgo-ct-ak-12426148')&&window.__BREACHLINE__?.assetAudit()?.map?.propLighting?.appliedMeshes===2325,null,{timeout:120000});
  await peer.getByRole('textbox',{name:'呼号',exact:true}).fill('LAN Peer');
  await peer.getByRole('button',{name:'局域网房间',exact:true}).click();
  await peer.getByRole('listitem').filter({hasText:'Dust2 R4 双客户端验收'}).click();
  await peer.getByRole('button',{name:'加入所选房间',exact:true}).click();
  await peer.waitForFunction(()=>window.__BREACHLINE__?.snapshot()?.players.filter(p=>!p.bot).length===2);
  await peer.waitForFunction(()=>window.__BREACHLINE__.assetAudit().firstPerson?.armsProfile==='ct_arms_idf'&&window.__BREACHLINE__.assetAudit().firstPerson?.detail?.weapon==='m4a4');
  await peer.bringToFront();
  await peer.getByRole('button',{name:'继续行动',exact:true}).click();
  await peer.waitForFunction(()=>!!document.pointerLockElement);
  await peer.waitForTimeout(600);
  await peer.screenshot({path:'output/playwright/source-r4-m4-live.png'});
  const before=await peer.evaluate(()=>({snapshot:window.__BREACHLINE__.snapshot(),audit:window.__BREACHLINE__.assetAudit(),locked:!!document.pointerLockElement}));
  await peer.keyboard.down('ShiftLeft');await peer.keyboard.down('KeyW');await peer.waitForTimeout(1700);
  const walking=await peer.evaluate(()=>window.__BREACHLINE__.handlingAudit());
  await peer.keyboard.up('KeyW');
  await peer.keyboard.down('ControlLeft');await peer.waitForTimeout(350);
  const crouch=await peer.evaluate(()=>({snapshot:window.__BREACHLINE__.snapshot(),audit:window.__BREACHLINE__.assetAudit()}));await peer.keyboard.up('ControlLeft');await peer.waitForTimeout(500);
  const standing=await peer.evaluate(()=>window.__BREACHLINE__.handlingAudit());await peer.keyboard.up('ShiftLeft');
  await peer.mouse.down();await peer.waitForTimeout(160);await peer.mouse.up();await peer.keyboard.press('KeyR');await peer.waitForTimeout(750);
  const reload=await peer.evaluate(()=>({snapshot:window.__BREACHLINE__.snapshot(),audit:window.__BREACHLINE__.assetAudit()}));
  await peer.screenshot({path:'output/playwright/source-r4-m4-reload.png'});
  await peer.waitForTimeout(3000);await peer.keyboard.press('KeyF');await peer.waitForTimeout(1100);
  const inspect=await peer.evaluate(()=>window.__BREACHLINE__.assetAudit());await peer.screenshot({path:'output/playwright/source-r4-m4-inspect.png'});
  await peer.waitForTimeout(3000);const audio=await peer.evaluate(()=>window.__BREACHLINE__.audioAudit());
  if(Object.keys(audio.verifiedSourceSounds).length!==12||!Object.values(audio.verifiedSourceSounds).every(Boolean))throw Error('Original M4 sounds were not hash verified');
  const played=new Set(audio.recentSourceEvents.map(e=>e.key));
  for(const key of ['source_m4a4_6','source_m4a4_7','source_m4a4_8','source_m4a4_9','source_m4a4_2','source_m4a4_1','source_m4a4_0'])if(!played.has(key))throw Error('M4 animation sound event missing: '+key);
  const nativeShots=reload.snapshot.events.filter(e=>e.by===reload.snapshot.you&&e.sourceRifleShot);
  if(!nativeShots.length||nativeShots.some(e=>e.sourceRifleShot.weapon!=='m4a4'||e.sourceRifleShot.seedByte!==(e.sourceRifleShot.serverSeed&255)))throw Error('Authoritative M4 native bullet records missing');
  if(!reload.snapshot.players.find(p=>p.id===reload.snapshot.you).sourceRifleHandling)throw Error('Source handling missing from LAN snapshot');
  if(inspect.firstPerson.detail.pose!=='inspect')throw Error('Original M4 inspection clip is not playing');
  const own=s=>s.players.find(p=>p.name==='LAN Peer');
  await page.evaluate(e=>window.__CSGO_CT_ARMS_ACTION__=e,{before,crouch,reload,inspect,errors});
  if(!before.locked||!own(crouch.snapshot).crouch||Math.hypot(own(crouch.snapshot).x-own(before.snapshot).x,own(crouch.snapshot).z-own(before.snapshot).z)<.2)throw Error('LAN CT movement/duck or pointer lock failed');
  if(own(crouch.snapshot).ack<=own(before.snapshot).ack)throw Error('Source authority input acknowledgements did not advance');
  if(!walking.authority.player.sourceWalking||!walking.prediction.player.sourceWalking||standing.authority.player.crouch||standing.prediction.player.crouch)throw Error('LAN authority/prediction Shift walk or released standing failed');
  if(!walking.authority.player.sourcePoseVersion||!reload.snapshot.simulationVersion.includes('csgo-walking-12426148-r1:csgo-player-movement-12426148-r2'))throw Error('Walking movement identity was not sent');
  if(!(own(reload.snapshot).reload>0)||!reload.audit.firstPerson.hashVerified)throw Error('Original CT first-person reload/hash failed');
  await pause(peer);
  const joined=await peer.evaluate(()=>window.__BREACHLINE__.snapshot());
  const audits=await Promise.all([page,peer].map(p=>p.evaluate(()=>({audit:window.__BREACHLINE__.assetAudit(),secureContext:isSecureContext,subtle:!!globalThis.crypto?.subtle}))));
  for(const value of audits){if(value.secureContext||value.subtle)throw Error('LAN did not exercise fallback SHA');
    if(!value.audit.map.simulationVersion||value.audit.map.simulationVersion!==joined.simulationVersion)throw Error('Client/server simulation data differ');
    for(const files of [value.audit.map.hashVerified,value.audit.character.hashVerified,value.audit.counterTerrorist.hashVerified])if(!Object.values(files).every(Boolean))throw Error('Original LAN files did not hash verify');
  }
  if(!audits[1].audit.actors.some(a=>a.visible&&a.asset?.startsWith('csgo-ct-m4-12426148')))throw Error('No original CT teammate is rendered');
  for(const p of joined.players)if(!p.sourcePoseVersion.startsWith('csgo-'+(p.team==='blue'?'ct':'t')+'-'+(p.weapon==='m4a4'?'m4':'ak')+'-12426148'))throw Error('Team received wrong original pose');
  await peer.screenshot({path:'output/playwright/source-r4-m4-lan-peer.png'});
  const hostJoined=await page.evaluate(()=>window.__BREACHLINE__.snapshot());
  await page.screenshot({path:'output/playwright/source-r4-m4-lan-host.png'});
  await pause(peer);
  await peer.getByRole('button',{name:'返回主菜单',exact:true}).click();
  await page.waitForFunction(()=>window.__BREACHLINE__.snapshot().players.filter(p=>!p.bot).length===1);
  const peerLeft=await page.evaluate(()=>window.__BREACHLINE__.snapshot());
  await pause(page);
  await page.getByRole('button',{name:'返回主菜单',exact:true}).click();
  await page.waitForFunction(()=>fetch('/api/rooms').then(r=>r.json()).then(r=>r.rooms.every(x=>x.name!=='Dust2 R4 双客户端验收')));
  const cleanup=await page.evaluate(()=>fetch('/api/rooms').then(r=>r.json()));
  await peer.close();
  if(errors.length)throw Error(errors.join('\n'));
  for(const snapshot of [hostInitial,joined,hostJoined,peerLeft])if(snapshot.mapId!=='de_dust2-source-12426148'||snapshot.players.some(p=>!p.sourcePose||!p.sourcePoseVersion))throw Error('Authoritative Source map or pose missing');
  if(!sockets.every(url=>url.startsWith('ws://192.168.1.100:27019/')))throw Error('WebSocket did not use LAN endpoint');
  await page.evaluate(e=>{window.__CSGO_SOURCE_LAN_EVIDENCE__=e;},{hostInitial,rooms,joined,hostJoined,peerLeft,cleanup,sockets,errors,audits,before,walking,crouch,standing,reload,inspect,audio,physicalDevices:1,browserClients:2,scope:"Original Dust2, separate T/CT poses and first-person arms, M4A4 CT Shift walk/duck/standing/reload/inspect and original animation audio, VHV R5 diffuse/decal/tint/compound and mandatory SHA over HTTP LAN; combat separately tested"});
}
