async page=>{
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://192.168.1.100:27019/?map=de_dust2');
 const start=page.getByRole('button',{name:/^开始人机训练/});await start.waitFor({state:'visible',timeout:120000});await page.getByRole('textbox',{name:'呼号',exact:true}).fill('Glock Proof');await start.click();
 await page.waitForFunction(()=>!!document.pointerLockElement);await page.getByRole('button',{name:'返回主菜单',exact:true}).waitFor({state:'hidden'});
 await page.keyboard.press('Digit2');await page.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player?.weapon==='glock');
 await page.waitForTimeout(90);
 const read=()=>page.evaluate(()=>({handling:window.__BREACHLINE__.handlingAudit(),audit:window.__BREACHLINE__.assetAudit(),audio:window.__BREACHLINE__.audioAudit()}));
 const evidence={errors,draw:await read()};await page.screenshot({path:'output/playwright/source-r4-glock-draw-live.png'});
 await page.evaluate(()=>{window.__SOURCE_GLOCK_CAPTURE__={frames:[],shots:{},done:false};const sample=()=>{const c=window.__SOURCE_GLOCK_CAPTURE__;if(c.done)return;const h=window.__BREACHLINE__.handlingAudit(),p=h?.authority.player;if(p){c.frames.push({time:h.authority.time,weapon:p.weapon,ammo:p.ammo,reserve:p.reserve,reload:p.reload,slot:p.slot,walk:p.sourceWalking,crouch:p.crouch,speed:Math.hypot(p.vx,p.vz)/.0254,state:p.sourcePose?.state,command:p.sourceGlock?.command,action:p.sourceGlock?.action,poseClock:p.sourcePistolPose?.clock,firstPerson:((fp)=>({sequence:fp?.sequence,time:fp?.time,weapon:fp?.weapon}))(window.__BREACHLINE__.assetAudit().firstPerson?.detail)});for(const e of h.shots??[])c.shots[e.id]=e;}requestAnimationFrame(sample);};requestAnimationFrame(sample);});
 await page.waitForFunction(()=>{const p=window.__BREACHLINE__.handlingAudit().authority.player;return p?.weapon==='glock'&&p.cooldown===0;});
 await page.mouse.down();await page.waitForTimeout(520);evidence.semi=await read();await page.mouse.up();
 if(evidence.semi.handling.authority.player.ammo!==19)throw Error('Held semi-auto trigger did not fire exactly one round');
 if(evidence.semi.audit.firstPerson.detail.sequence!=='glock_firesingle'||evidence.semi.handling.authority.player.sourceGlock.animation.cycle!==1)throw Error('Completed fire pose was replaced before the original WeaponIdle gate');
 await page.mouse.down({button:'right'});await page.waitForTimeout(50);await page.mouse.up({button:'right'});await page.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player.sourceGlock.command.burstMode);
 await page.waitForTimeout(350);await page.mouse.down();await page.waitForTimeout(700);await page.mouse.up();evidence.burst=await read();
 if(evidence.burst.handling.authority.player.ammo!==16)throw Error('Held burst trigger did not fire exactly three rounds');
 await page.keyboard.press('KeyR');await page.waitForTimeout(550);evidence.reload=await read();await page.screenshot({path:'output/playwright/source-r4-glock-reload-live.png'});
 await page.waitForTimeout(600);evidence.reloadMiddle=await read();
 await page.waitForFunction(()=>{const h=window.__BREACHLINE__.handlingAudit(),p=h.authority.player;return p.ammo===20&&p.reload===0&&!p.sourceGlock.command.reloading&&Math.fround(h.authority.time)>=p.sourceGlock.command.ownerNextAttack;});
 evidence.inspectReady=await read();
 await page.keyboard.press('KeyF');await page.waitForTimeout(600);evidence.inspect=await read();await page.screenshot({path:'output/playwright/source-r4-glock-inspect-live.png'});
 await page.mouse.down();await page.waitForTimeout(70);await page.mouse.up();evidence.interrupted=await read();await page.waitForTimeout(600);
 await page.keyboard.down('ShiftLeft');await page.keyboard.down('KeyW');await page.waitForTimeout(1200);evidence.walk=await read();await page.keyboard.up('KeyW');
 await page.keyboard.down('ControlLeft');await page.waitForTimeout(350);evidence.crouch=await read();await page.keyboard.up('ControlLeft');await page.waitForTimeout(450);evidence.stand=await read();await page.keyboard.up('ShiftLeft');
 await page.keyboard.press('Digit1');await page.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player.weapon==='vandal');evidence.primary=await read();
 await page.keyboard.press('Digit2');await page.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player.weapon==='glock');await page.waitForTimeout(90);evidence.redraw=await read();
 await page.waitForTimeout(1250);evidence.final=await read();evidence.capture=await page.evaluate(()=>{window.__SOURCE_GLOCK_CAPTURE__.done=true;return window.__SOURCE_GLOCK_CAPTURE__;});
 await page.evaluate(e=>window.__SOURCE_GLOCK_GAMEPLAY_EVIDENCE__=e,evidence);
 if(evidence.draw.audit.firstPerson.detail.sequence!=='glock_draw'||evidence.draw.audit.firstPerson.armsProfile!=='t_arms')throw Error('Original T Glock draw did not render');
 if(evidence.reload.audit.firstPerson.detail.sequence!=='glock_reload'||evidence.inspect.audit.firstPerson.detail.sequence!=='lookat01'||evidence.interrupted.audit.firstPerson.detail.sequence==='lookat01')throw Error('Original Glock reload / inspect / fire interruption failed');
 if(!evidence.walk.handling.authority.player.sourceWalking||evidence.walk.handling.authority.player.sourcePose.state!=='Walk'||!evidence.crouch.handling.authority.player.crouch||evidence.stand.handling.authority.player.crouch)throw Error('Glock walk/crouch/stand pose failed');
 if(evidence.primary.handling.authority.player.ammo!==30||evidence.redraw.handling.authority.player.ammo!==17)throw Error('Primary/secondary ammo was not retained separately');
 if(Object.keys(evidence.final.audio.verifiedSourcePistolSounds).length!==34||Object.keys(evidence.final.audio.verifiedSourcePistolCommandSounds).length!==2)throw Error('Original pistol WAV SHA proof is incomplete');
 if(evidence.final.audit.map.olive?.meshes!==64||evidence.final.audit.map.olive.csm!==false||!evidence.final.audit.map.olive.verification.hashVerified)throw Error('Original no-CSM olive coverage missing');
 if(evidence.final.audit.map.propLighting.totalAppliedMeshes!==2459||!evidence.final.audit.map.wind?.thinkCalls)throw Error('Original foliage and wind were not active');
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'返回主菜单',exact:true}).waitFor({state:'visible'});await page.getByRole('button',{name:'返回主菜单',exact:true}).click();
 evidence.cleanup=await page.evaluate(()=>fetch('/api/rooms').then(r=>r.json()));evidence.scope='Actual UI training: original Glock team arms/actions/audio, semi/burst, separate slots, movement, authoritative shot metadata, original wind/foliage. Full AnimState, original effects and additional weapons remain open.';
 await page.evaluate(e=>window.__SOURCE_GLOCK_GAMEPLAY_EVIDENCE__=e,evidence);if(errors.length)throw Error(errors.join('\n'));
}
