async page=>{
 const errors=[],sockets=[],peer=await page.context().newPage(),name='原 USP 双客户端验收';
 const evidence={errors,sockets,physicalDevices:1,browserClients:2};for(const p of [page,peer]){p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('websocket',w=>sockets.push(w.url()));}
 const read=p=>p.evaluate(()=>({snapshot:window.__BREACHLINE__.snapshot(),handling:window.__BREACHLINE__.handlingAudit(),audit:window.__BREACHLINE__.assetAudit(),audio:window.__BREACHLINE__.audioAudit()}));const own=r=>r.handling.authority.player;const save=()=>page.evaluate(e=>window.__SOURCE_USP_LAN_EVIDENCE__=e,evidence);
 const pause=async p=>{await p.bringToFront();if(!await p.getByRole('button',{name:'返回主菜单',exact:true}).isVisible())await p.keyboard.press('Escape');await p.getByRole('button',{name:'返回主菜单',exact:true}).waitFor({state:'visible'});};
 const resume=async p=>{await p.bringToFront();await p.getByRole('button',{name:'继续行动',exact:true}).click();await p.waitForFunction(()=>!!document.pointerLockElement);await p.getByRole('button',{name:'返回主菜单',exact:true}).waitFor({state:'hidden'});};
 const ready=()=>peer.waitForFunction(()=>{const h=window.__BREACHLINE__.handlingAudit(),p=h.authority.player;return window.__BREACHLINE__.snapshot()?.phase==='live'&&p?.weapon==='usp'&&p.cooldown===0&&!p.sourceUSP.command.reloading;});
 const tap=async(button='left')=>{await peer.mouse.down({button});await peer.waitForTimeout(80);await peer.mouse.up({button});};
 try{
  for(const p of [page,peer]){await p.goto('http://192.168.1.100:27019/?map=de_dust2');await p.getByRole('button',{name:/^开始人机训练/}).waitFor({state:'visible',timeout:120000});}
  await page.getByRole('textbox',{name:'呼号',exact:true}).fill('USP host');await page.getByRole('button',{name:'创建房间',exact:true}).click();await page.getByLabel('房间名称',{exact:true}).fill(name);await page.getByRole('button',{name:'创建并进入房间',exact:true}).click();await page.waitForFunction(()=>window.__BREACHLINE__.snapshot()?.players.some(p=>p.name==='USP host'));await pause(page);
  await peer.getByRole('textbox',{name:'呼号',exact:true}).fill('USP CT');await peer.getByRole('button',{name:'局域网房间',exact:true}).click();await peer.getByRole('listitem').filter({hasText:name}).click();await peer.getByRole('button',{name:'加入所选房间',exact:true}).click();await peer.waitForFunction(()=>window.__BREACHLINE__.snapshot()?.players.filter(p=>!p.bot).length===2);await resume(peer);
  await peer.keyboard.press('Digit2');await peer.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player?.weapon==='usp');evidence.draw=await read(peer);await peer.screenshot({path:'output/playwright/source-r4-usp-ct-draw-lan.png'});await ready();await peer.mouse.down();await peer.waitForTimeout(500);await peer.mouse.up();evidence.silenced=await read(peer);await save();if(own(evidence.silenced).ammo!==11)throw Error('LAN USP held trigger consumed wrong ammunition');
  await peer.keyboard.press('KeyR');await peer.waitForTimeout(350);evidence.reload=await read(peer);await peer.waitForFunction(()=>{const p=window.__BREACHLINE__.handlingAudit().authority.player;return p.ammo===12&&p.sourceUSP.command.reloading;});evidence.earlyReload=await read(peer);await ready();await tap('right');await peer.waitForTimeout(400);evidence.detach=await read(peer);await peer.screenshot({path:'output/playwright/source-r4-usp-ct-detach-lan.png'});await save();
  await peer.waitForFunction(()=>!window.__BREACHLINE__.handlingAudit().authority.player.sourceUSP.command.silencerAttached);evidence.commit=await read(peer);await ready();await tap();await peer.waitForTimeout(220);evidence.unsilenced=await read(peer);await save();
  await peer.keyboard.press('KeyF');await peer.waitForTimeout(650);evidence.inspect=await read(peer);await peer.screenshot({path:'output/playwright/source-r4-usp-ct-inspect-lan.png'});
  await peer.keyboard.press('Digit1');await peer.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player.weapon==='m4a4');evidence.primary=await read(peer);await peer.keyboard.press('Digit2');await peer.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player.weapon==='usp');await ready();evidence.redraw=await read(peer);await pause(peer);
  await resume(page);await page.keyboard.press('Digit2');await page.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player.weapon==='glock');await page.waitForTimeout(1300);await page.mouse.down();await page.waitForTimeout(500);await page.mouse.up();evidence.hostShot=await read(page);await pause(page);
  evidence.both=await Promise.all([page,peer].map(read));await save();
  if(own(evidence.draw).team!=='blue'||own(evidence.draw).secondary!=='usp'||evidence.draw.audit.firstPerson.armsProfile!=='ct_arms_idf'||!evidence.draw.audit.firstPerson.hashVerified)throw Error('LAN default CT original USP owner failed');
  if(own(evidence.earlyReload).reserve!==23||!own(evidence.earlyReload).sourceUSP.command.reloadVisComplete||own(evidence.commit).cooldown<=0)throw Error('LAN original animation timing gates failed');
  if(own(evidence.unsilenced).ammo!==11||own(evidence.primary).ammo!==30||own(evidence.redraw).ammo!==11||own(evidence.redraw).sourceUSP.command.silencerAttached)throw Error('LAN USP state/slot persistence failed');
  if(evidence.inspect.audit.firstPerson.detail.sequence!=='lookat01'||own(evidence.hostShot).weapon!=='glock'||own(evidence.hostShot).ammo!==19)throw Error('LAN USP inspect or default T Glock regressed');
  for(const r of evidence.both){const ct=r.snapshot.players.find(p=>p.name==='USP CT');if(!ct.sourceUSP||ct.sourceUSP.command.mode!==0||!ct.sourcePistolPose||!ct.sourcePoseVersion.startsWith('csgo-ct-usp-12426148'))throw Error('Remote original USP state/pose missing');if(r.snapshot.simulationVersion!==r.audit.map.simulationVersion||!r.snapshot.simulationVersion.includes('csgo-usp-pose-driver-12426148-r1'))throw Error('USP client/server identity differs');}
  if(!evidence.unsilenced.handling.shots.some(e=>e.sourcePistolShot?.weapon==='usp-s'&&e.sourcePistolShot.mode===0))throw Error('Original USP unsilenced authority receipt missing');
  if(!sockets.length||!sockets.every(s=>s.startsWith('ws://192.168.1.100:27019/')))throw Error('Clients bypassed the LAN socket');
  if(errors.length)throw Error(errors.join('\n'));evidence.status='passed';
 }finally{
  for(const p of [peer,page])if(!p.isClosed())try{if(await p.getByRole('button',{name:'返回主菜单',exact:true}).isVisible()||await p.evaluate(()=>!!window.__BREACHLINE__?.snapshot())){await pause(p);await p.getByRole('button',{name:'返回主菜单',exact:true}).click();}}catch(e){errors.push('cleanup: '+String(e));}
  if(!peer.isClosed())await peer.close();evidence.cleanup=await page.evaluate(()=>fetch('/api/rooms').then(r=>r.json()));evidence.scope='One physical Mac, two actual LAN browser clients: CT default USP, T Glock, native attachment/early reload, separate inventories, authority/prediction, full serialized pistol poses and original mode-specific audio.';await save();
 }
}
