async page=>{
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://192.168.1.100:27019/?map=de_dust2');
 const start=page.getByRole('button',{name:/^开始人机训练/});await start.waitFor({state:'visible',timeout:120000});await page.getByRole('textbox',{name:'呼号',exact:true}).fill('AK Audio');await start.click();
 await page.waitForFunction(()=>!!document.pointerLockElement);await page.waitForTimeout(150);
 const draw=await page.evaluate(()=>({audit:window.__BREACHLINE__.assetAudit(),audio:window.__BREACHLINE__.audioAudit()}));
 await page.screenshot({path:'output/playwright/source-r4-ak-draw-live.png'});
 await page.waitForTimeout(950);
 await page.evaluate(()=>{window.__SOURCE_WALK_CAPTURE__={frames:[],done:false};const step=()=>{const out=window.__SOURCE_WALK_CAPTURE__;if(out.done)return;const a=window.__BREACHLINE__.handlingAudit();if(a?.authority.player)out.frames.push({time:a.authority.time,player:a.authority.player,prediction:a.prediction});requestAnimationFrame(step);};requestAnimationFrame(step);});
 await page.keyboard.down('ShiftLeft');await page.keyboard.down('KeyW');await page.waitForTimeout(1700);
 const walk=await page.evaluate(()=>window.__BREACHLINE__.handlingAudit());
 await page.keyboard.down('ControlLeft');await page.waitForTimeout(450);
 const crouch=await page.evaluate(()=>window.__BREACHLINE__.handlingAudit());
 await page.keyboard.up('ControlLeft');await page.waitForTimeout(550);
 const stand=await page.evaluate(()=>window.__BREACHLINE__.handlingAudit());
 await page.keyboard.up('ShiftLeft');await page.waitForTimeout(450);
 const run=await page.evaluate(()=>window.__BREACHLINE__.handlingAudit());
 await page.keyboard.up('KeyW');
 const movement=await page.evaluate(()=>{window.__SOURCE_WALK_CAPTURE__.done=true;return window.__SOURCE_WALK_CAPTURE__;});
 await page.mouse.down();await page.waitForTimeout(180);await page.mouse.up();await page.keyboard.press('KeyR');await page.waitForTimeout(550);
 const reload=await page.evaluate(()=>({snapshot:window.__BREACHLINE__.snapshot(),audit:window.__BREACHLINE__.assetAudit()}));
 await page.screenshot({path:'output/playwright/source-r4-ak-native-audio-reload.png'});
 await page.waitForTimeout(2800);await page.keyboard.press('KeyF');await page.waitForTimeout(1100);
 const inspect=await page.evaluate(()=>window.__BREACHLINE__.assetAudit());await page.screenshot({path:'output/playwright/source-r4-ak-native-audio-inspect.png'});await page.waitForTimeout(4000);
 const audio=await page.evaluate(()=>window.__BREACHLINE__.audioAudit());
 if(Object.keys(audio.verifiedSourceAKSounds).length!==9||!Object.values(audio.verifiedSourceAKSounds).every(Boolean))throw Error('Original AK event audio hashes are incomplete');
 const keys=new Set(audio.recentSourceEvents.map(e=>e.key));
 for(const suffix of ['draw','shot','clipout','clipin','boltpull','weaponmove1','weaponmove2','weaponmove3'])if(!keys.has('source_ak47_'+suffix))throw Error('Missing original AK audio event: '+suffix);
 for(const e of audio.recentSourceEvents.filter(e=>e.key.startsWith('source_ak47_weaponmove')))if(e.playbackRate<.98||e.playbackRate>1.01||e.volume<.0325||e.volume>.065)throw Error('AK inspection did not use original pitch/volume ranges');
 if(inspect.firstPerson.detail.pose!=='inspect'||reload.snapshot.players.find(p=>p.name==='AK Audio').reload<=0)throw Error('Actual original AK animations were not active');
 if(draw.audit.firstPerson.detail.pose!=='draw'||!draw.audit.firstPerson.detail.clips.some(c=>c.name==='draw'&&c.duration===1))throw Error('First-life original AK draw was not active');
 if(!walk.authority.player.sourceWalking||!crouch.authority.player.crouch||stand.authority.player.crouch||run.authority.player.sourceWalking)throw Error('Actual Shift / crouch / release state is incorrect');
 const speed=p=>Math.hypot(p.vx,p.vz)/.0254;
 if(!movement.frames.some(f=>f.player.sourceWalking&&!f.player.crouch&&speed(f.player)>110&&speed(f.player)<113))throw Error('Original AK walking speed was not reached');
 if(inspect.map.propLighting.appliedMeshes!==2325)throw Error('VHV compound tint was not integrated');
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'返回主菜单',exact:true}).waitFor({state:'visible'});await page.getByRole('button',{name:'返回主菜单',exact:true}).click();
 await page.evaluate(e=>window.__SOURCE_AK_NATIVE_AUDIO_EVIDENCE__=e,{draw,walk,crouch,stand,run,movement,reload,inspect,audio,errors,scope:'Actual original T AK first-life draw, Shift walk, moving crouch/stand, reload/inspection event sampling, 9 sound events SHA, original volume/pitch ranges, VHV compound tint R5. Original deploy unlock, complete movement physics and sound operators remain pending.'});
 if(errors.length)throw Error(errors.join('\n'));
}
