async(page)=>{
 const errors=[],results=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});await page.reload();await page.waitForFunction(()=>window.__AK_DRAW_PREVIEW__?.audit().loaded,null,{timeout:120000});
 for(const team of ['t','ct']){
  await page.evaluate(team=>window.__AK_DRAW_PREVIEW__.load(team),team);const frames=[];
  for(const time of [0,.1,.235,.3666666667,.6,1]){const audit=await page.evaluate(t=>window.__AK_DRAW_PREVIEW__.sample(t),time);if(!audit.loaded||!audit.hashVerified||audit.team!==team||audit.detail.pose!=='draw'||audit.draw.triangles<10000||audit.sameNameArmWorldErrorMeters>1e-5)throw Error('Candidate render/arm identity '+JSON.stringify(audit));const screenshot=`output/playwright/source-ak-draw-${team}-${String(time).replace('.','_')}.png`;await page.screenshot({path:screenshot});frames.push({time,audit,screenshot});}
  await page.getByRole('button',{name:'播放原拔枪与声音',exact:true}).click();await page.waitForFunction(()=>window.__AK_DRAW_PREVIEW__.audit().playing===false);const full=await page.evaluate(()=>window.__AK_DRAW_PREVIEW__.audit());const events=full.soundRecords.map(r=>r.event);if(JSON.stringify(events)!==JSON.stringify(['weapon_ak47.draw','weapon_ak47.boltpull'])||full.audio.state!=='running')throw Error('Original audio timeline '+JSON.stringify(full));if(full.soundRecords[0].sampledTime!==0||full.soundRecords[1].sampledTime<.36666667461395264||full.soundRecords[1].sampledTime>.467)throw Error('Original event threshold');const afterRepeat=await page.evaluate(()=>window.__AK_DRAW_PREVIEW__.repeatRead());if(afterRepeat.soundRecords.length!==2)throw Error('Audio duplicate');
  await page.getByRole('button',{name:'播放原拔枪与声音',exact:true}).click();await page.waitForTimeout(100);await page.getByRole('button',{name:'中断',exact:true}).click();await page.waitForTimeout(450);const cancelled=await page.evaluate(()=>window.__AK_DRAW_PREVIEW__.audit());if(cancelled.playback.pose!=='idle'||cancelled.soundRecords.length!==1||cancelled.soundRecords[0].event!=='weapon_ak47.draw'||cancelled.soundRecords[0].generation<=full.soundRecords[0].generation)throw Error('Original draw interrupt/restart');
  await page.evaluate(()=>window.__AK_DRAW_PREVIEW__.unload());await page.waitForTimeout(50);const empty=await page.evaluate(()=>window.__AK_DRAW_PREVIEW__.audit());if(empty.memory.geometries||empty.memory.textures||empty.memory.programs)throw Error('Candidate GPU leak '+JSON.stringify(empty.memory));results.push({team,frames,full,afterRepeat,cancelled,empty});
 }
 const evidence={results,errors,scope:'Private original AK T/CT append-only draw candidates. Actual WebGL, source-keyframes plus interior samples, actual WebAudio decode/start calls with production event-crossing helper. No deploy unlock or physical speaker measurement.'};await page.evaluate(e=>window.__AK_DRAW_GPU_EVIDENCE__=e,evidence);if(errors.length)throw Error(errors.join('\n'));return{profiles:results.length,screenshots:results.reduce((n,r)=>n+r.frames.length,0),errors,audio:results.map(r=>r.full.soundRecords),emptyResources:results.map(r=>r.empty.memory)};
}
