async page=>{
 const errors=[],sockets=[],peer=await page.context().newPage(),name='沙鹰双客户端验收',evidence={errors,sockets,physicalDevices:1,browserClients:2};
 for(const p of [page,peer]){p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('websocket',w=>sockets.push(w.url()));}
 const read=p=>p.evaluate(()=>({snapshot:window.__BREACHLINE__.snapshot(),handling:window.__BREACHLINE__.handlingAudit(),audit:window.__BREACHLINE__.assetAudit(),audio:window.__BREACHLINE__.audioAudit()})),own=r=>r.handling.authority.player,save=()=>page.evaluate(e=>window.__SOURCE_DEAGLE_LAN_EVIDENCE__=e,evidence);
 const pause=async p=>{await p.bringToFront();if(!await p.getByRole('button',{name:'返回主菜单',exact:true}).isVisible())await p.keyboard.press('Escape');await p.getByRole('button',{name:'返回主菜单',exact:true}).waitFor({state:'visible'});};
 const resume=async p=>{await p.bringToFront();await p.getByRole('button',{name:'继续行动',exact:true}).click();await p.waitForFunction(()=>!!document.pointerLockElement);await p.getByRole('button',{name:'返回主菜单',exact:true}).waitFor({state:'hidden'});};
 const ready=()=>peer.waitForFunction(()=>{const h=window.__BREACHLINE__.handlingAudit(),p=h.authority.player;return window.__BREACHLINE__.snapshot()?.phase==='live'&&p?.weapon==='deagle'&&p.cooldown===0&&!p.sourceDeagle.command.reloading;});
 try{
  for(const p of [page,peer]){await p.goto('http://192.168.1.100:27019/?map=de_dust2');await p.getByRole('button',{name:/^开始人机训练/}).waitFor({state:'visible',timeout:120000});}
  await page.getByRole('textbox',{name:'呼号',exact:true}).fill('Deagle host');await page.getByRole('button',{name:'创建房间',exact:true}).click();await page.getByLabel('房间名称',{exact:true}).fill(name);await page.getByRole('button',{name:'创建并进入房间',exact:true}).click();await page.waitForFunction(()=>window.__BREACHLINE__.snapshot()?.players.some(p=>p.name==='Deagle host'));await pause(page);
  await peer.getByRole('textbox',{name:'呼号',exact:true}).fill('Deagle CT');await peer.getByRole('button',{name:'局域网房间',exact:true}).click();await peer.getByRole('listitem').filter({hasText:name}).click();await peer.getByRole('button',{name:'加入所选房间',exact:true}).click();await peer.waitForFunction(()=>window.__BREACHLINE__.snapshot()?.players.filter(p=>!p.bot).length===2);await resume(peer);
  await peer.keyboard.press('KeyB');const shop=peer.getByRole('dialog').filter({hasText:'购买装备'});await shop.waitFor({state:'visible'});await shop.getByRole('button',{name:/^Desert Eagle/}).click();await peer.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player?.weapon==='deagle'&&window.__BREACHLINE__.assetAudit().firstPerson?.detail?.weapon==='deagle');evidence.draw=await read(peer);await shop.getByRole('button',{name:'Close',exact:true}).click();await peer.waitForFunction(()=>!!document.pointerLockElement);await peer.screenshot({path:'output/playwright/source-r4-deagle-ct-draw-lan.png'});await save();
  await ready();await peer.mouse.down();await peer.waitForTimeout(600);await peer.mouse.up();evidence.single=await read(peer);if(own(evidence.single).ammo!==6)throw Error('LAN Deagle semi-auto latch failed');
  await peer.keyboard.press('KeyR');await peer.waitForTimeout(300);evidence.reload=await read(peer);await peer.waitForFunction(()=>{const p=window.__BREACHLINE__.handlingAudit().authority.player;return p.ammo===7&&p.sourceDeagle.command.reloading;});evidence.earlyReload=await read(peer);await ready();
  await peer.keyboard.press('KeyF');await peer.waitForTimeout(750);evidence.inspect=await read(peer);await peer.screenshot({path:'output/playwright/source-r4-deagle-ct-inspect-lan.png'});await save();
  await peer.keyboard.press('Digit1');await peer.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player.weapon==='m4a4');evidence.primary=await read(peer);await peer.keyboard.press('Digit2');await ready();evidence.redraw=await read(peer);await pause(peer);
  await resume(page);await page.keyboard.press('Digit2');await page.waitForFunction(()=>window.__BREACHLINE__.handlingAudit().authority.player.weapon==='glock');await page.waitForTimeout(1300);await page.mouse.down();await page.waitForTimeout(500);await page.mouse.up();evidence.hostShot=await read(page);await pause(page);
  evidence.both=await Promise.all([page,peer].map(read));await save();
  if(own(evidence.draw).team!=='blue'||own(evidence.draw).secondary!=='deagle'||evidence.draw.audit.firstPerson.armsProfile!=='ct_arms_idf'||!evidence.draw.audit.firstPerson.hashVerified)throw Error('Original CT Deagle owner missing');
  if(own(evidence.earlyReload).reserve!==34||!own(evidence.earlyReload).sourceDeagle.command.reloadVisComplete||own(evidence.earlyReload).cooldown<=0)throw Error('LAN Deagle event54/gate failed');
  if(own(evidence.primary).ammo!==30||own(evidence.redraw).ammo!==7||evidence.inspect.audit.firstPerson.detail.sequence!=='lookat01')throw Error('LAN Deagle inventory/inspect failed');
  if(own(evidence.hostShot).weapon!=='glock'||own(evidence.hostShot).ammo!==19)throw Error('Default T Glock regressed');
  for(const r of evidence.both){const ct=r.snapshot.players.find(p=>p.name==='Deagle CT');if(!ct.sourceDeagle||ct.sourceDeagle.command.clip!==7||!ct.sourcePistolPose||!ct.sourcePoseVersion.startsWith('csgo-ct-deagle-12426148:'))throw Error('Remote Deagle state/pose missing');if(r.snapshot.simulationVersion!==r.audit.map.simulationVersion||!r.snapshot.simulationVersion.includes('csgo-deagle-runtime-12426148-r1'))throw Error('Deagle client/server identity differs');}
  if(!evidence.single.handling.shots.some(e=>e.sourcePistolShot?.weapon==='deagle')||!evidence.single.audio.recentSourceEvents.some(e=>['source_deagle_13','source_deagle_14'].includes(e.key)))throw Error('LAN Deagle accepted bullet/original WAV missing');
  if(evidence.single.audit.sourcePistolParticles.bursts!==evidence.draw.audit.sourcePistolParticles.bursts+1||evidence.single.audit.sourcePistolParticles.placeholderVisible)throw Error('LAN prediction/authority duplicated the original muzzle burst or retained the cone');
  if(!sockets.length||!sockets.every(s=>s.startsWith('ws://192.168.1.100:27019/')))throw Error('Clients bypassed LAN socket');
  if(errors.length)throw Error(errors.join('\n'));evidence.status='passed';
 }finally{
  for(const p of [peer,page])if(!p.isClosed())try{if(await p.getByRole('button',{name:'返回主菜单',exact:true}).isVisible()||await p.evaluate(()=>!!window.__BREACHLINE__?.snapshot())){await pause(p);await p.getByRole('button',{name:'返回主菜单',exact:true}).click();}}catch(e){errors.push('cleanup: '+String(e));}
  if(!peer.isClosed())await peer.close();evidence.cleanup=await page.evaluate(()=>fetch('/api/rooms').then(r=>r.json()));evidence.scope='One physical Mac, two real LAN browsers: CT Deagle purchase, native semi-auto/early reload, CT original arms, original WAV, snapshots/pose identity and T Glock regression.';await save();
 }
}
