async(page)=>{
 const errors=[],results=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
 await page.reload();await page.waitForFunction(()=>window.__PISTOL_CHARACTER_PREVIEW__?.audit().loaded,null,{timeout:120000});
 for(const team of ['t','ct'])for(const weapon of ['glock','usp']){
  await page.evaluate(async({team,weapon})=>await window.__PISTOL_CHARACTER_PREVIEW__.load(team,weapon),{team,weapon});const frames=[];
  const cases=[['idle','Idle','hold',.3,1,false,false],['fire','Idle','fire',.14,1,true,false],['reload-early','Idle','reload',.2,1,true,false],['reload-mid','Idle','reload',.5,1,true,false],['reload-end','Idle','reload',.85,1,true,false],['crouch-reload','Crouch_Walk','reload',.37,.7,false,false],['blended-aim','Walk','hold',.4,1,true,true]];
  if(weapon==='usp')cases.push(['attach-early','Idle','attach',.2,1,true,false],['attach-late','Idle','attach',.8,1,true,false],['detach-early','Idle','detach',.2,1,true,false],['detach-late','Idle','detach',.8,1,true,false]);
  for(const [id,state,action,cycle,weight,close,blended]of cases){const audit=await page.evaluate(({state,action,cycle,weight,close,blended})=>window.__PISTOL_CHARACTER_PREVIEW__.sample(state,action,cycle,weight,close,blended),{state,action,cycle,weight,close,blended});await page.waitForTimeout(40);if(!audit.loaded||!audit.hashVerified||audit.status!=='ready'||audit.team!==team||audit.weapon!==weapon||audit.draw.triangles<5000||audit.maxPureRendererBoneDifferenceMeters>1e-9||audit.autoLayers.length!==5)throw Error('Pistol character identity/draw/graph failed');if(blended&&audit.autoLayers.filter(l=>l.weight>0).length!==2)throw Error('Original blend layers missing');if(action==='reload'&&audit.input.bodyLayers.length!==1)throw Error('Reload body layer missing');const screenshot=`output/playwright/pistol-character-${team}-${weapon}-${id}.png`;await page.screenshot({path:screenshot});frames.push({id,audit,screenshot});}
  const rejected=await page.evaluate(()=>window.__PISTOL_CHARACTER_PREVIEW__.identityReject());if(rejected.visible||rejected.status!=='invalid-authority')throw Error('Pistol character allowed wrong pose identity');await page.evaluate(()=>window.__PISTOL_CHARACTER_PREVIEW__.unload());await page.waitForTimeout(40);const empty=await page.evaluate(()=>window.__PISTOL_CHARACTER_PREVIEW__.audit());if(empty.loaded||empty.memory.geometries!==0||empty.memory.textures!==0||empty.memory.programs!==0)throw Error('Pistol character GPU resource leak '+JSON.stringify(empty.memory));results.push({team,weapon,frames,rejected,empty});
 }
 const evidence={results,errors,scope:'Four actual WebGL original character+pistol owners; explicit original action and five aim layers; no closed AnimState/IK gameplay claim'};await page.evaluate(e=>window.__PISTOL_CHARACTER_GPU_EVIDENCE__=e,evidence);if(errors.length)throw Error(errors.join('\n'));return{profiles:results.length,screenshots:results.reduce((n,r)=>n+r.frames.length,0),errors,emptyResources:results.map(r=>r.empty.memory)};
}
