"""Deterministic bounded DX9 VS128 words338..700 -> GLSL scalar/vector ops.

No optimization, guessed trig, geometry writes or shader sampling. The independent
Python token interpreter and actual GPU transform-feedback check are separate.
"""
from pathlib import Path
import hashlib, importlib.util, struct, sys
ROOT=Path(__file__).resolve().parents[1]
spec=importlib.util.spec_from_file_location('treesway_encoding',ROOT/'scripts/inspect-source-vhv-encoding.py')
e=importlib.util.module_from_spec(spec);sys.modules[spec.name]=e;spec.loader.exec_module(e)
raw=(ROOT/'.reference-assets/source-exports/dust2-foliage-audit/treesway/vs30-static128-dynamic0.dx9').read_bytes()
sha=hashlib.sha256(raw).hexdigest();assert sha=='fd2c99952aeab40ff76657d19bba4140e9bb575061dafc3040b0b688670611e0'
words=e.instructions(raw)
def source(t):
    assert not t&(1<<13)
    s=e.register(t);modifier=(t>>24)&15
    assert modifier in(0,1,11,12)
    if modifier in(11,12):s=('abs('+s+')')
    if modifier==12:s='-'+s
    return '('+s+')'
lines=['vec3 sourceTreePosition(vec3 sourcePosition, vec4 c12, vec4 c58, vec4 c59, vec4 c60) {',
    '  // Original zero-wind output is exactly rest (1400 real-vertex oracle cases).',
    '  if (c12.z == 0.0 && c12.w == 0.0) return sourcePosition;',
    '  vec4 v0=vec4(sourcePosition,1.0),v5=vec4(0.0);',
    '  vec4 r0=vec4(0.0),r1=vec4(0.0),r2=vec4(0.0),r3=vec4(0.0),r4=vec4(0.0);',
    '  const vec4 c0=vec4(0.0,1.0,2.0,0.5),c13=vec4(0.0);',
    '  const vec4 c14=vec4(100.0,0.5,200.0,0.0),c15=vec4(0.20000000298023224,0.25,2.0,0.5);',
    '  const vec4 c51=vec4(0.0,3.0,2.0,1.2000000476837158),c52=vec4(200.0,600.0,0.0,0.0);']
for at,w in words.items():
    if w[0]&65535==81 and w[1]&2047 in(1,3,4,5):
        values=struct.unpack('<4f',struct.pack('<4I',*w[2:]));lines.append('  const vec4 c%d=vec4(%s);'%(w[1]&2047,','.join(repr(v) for v in values)))
for at,w in words.items():
    if not 338<=at<=700:continue
    op=w[0]&65535;dst=w[1];a=list(map(source,w[2:]));x=a[0];y=a[1] if len(a)>1 else ''
    if op==1:expr=x
    elif op==2:expr=x+'+'+y
    elif op==4:expr=x+'*'+y+'+'+a[2]
    elif op==5:expr=x+'*'+y
    elif op==6:expr='vec4(1.0/'+x+'.x)'
    elif op==7:expr='vec4(inversesqrt(abs('+x+'.x)))'
    elif op==8:expr='vec4(dot('+x+'.xyz,'+y+'.xyz))'
    elif op==10:expr='min('+x+','+y+')'
    elif op==11:expr='max('+x+','+y+')'
    elif op==13:expr='vec4(greaterThanEqual('+x+','+y+'))'
    elif op==18:expr=x+'*'+y+'+(vec4(1.0)-'+x+')*'+a[2]
    elif op==19:expr='fract('+x+')'
    elif op==32:expr='vec4(pow(abs('+x+'.x),'+y+'.x))'
    else:raise ValueError((at,op))
    if dst&(1<<20):expr='clamp('+expr+',0.0,1.0)'
    mask=''.join(c for i,c in enumerate('xyzw') if dst&(1<<(16+i)))
    lines.append('  '+e.register(dst,True)+'=('+expr+').'+mask+'; // word '+str(at))
lines.extend(['  return r0.xyz;','}'])
glsl='\n'.join(lines)+'\n'
out=ROOT/'game/source-treesway-glsl.ts'
out.write_text('/** Generated by scripts/build-source-treesway-glsl.py; original App740 VS128/dynamic0. */\nexport const SOURCE_TREESWAY_PROGRAM_SHA256='+repr(sha)+';\nexport const SOURCE_TREESWAY_GLSL=`\n'+glsl+'`;\n')
print(out.relative_to(ROOT),hashlib.sha256(out.read_bytes()).hexdigest())
