"""Emit only the frozen original model table from the independently read oracle."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
j=json.loads((ROOT/'output/tests/source-glock-animation-clock-native.json').read_text());assert j['sourceMdlSha256']=='48ab6740def0ad8d7d4a42476583a61c8aa7d9f9f784b2d2f167720f14875242'
rows=[]
for p in j['profiles']:
 events=[]
 for i,e in enumerate(p['events']):
  reg=j['registrations'].get(e['name'],{'id':e['event'],'type':e['type']})
  events.append(dict(record=i,recordEvent=reg['id'],type=reg['type'],cycle=e['cycle'],options=e['options'],name=e['name']))
 rows.append(dict(sequence=p['sequence'],name=p['name'],duration=p['duration'],fadeOut=p['fadeOut'],flags=p['flags'],events=events))
out=ROOT/'game/source-glock-animation-data.ts';out.write_text('/** Generated by scripts/export-source-glock-animation-data.py from original MDL and ELF registration. */\nexport const SOURCE_GLOCK_ANIMATION_DATA = '+json.dumps(rows,indent=2)+' as const;\n')
print(out)
