"""Export authored lower VTF mips for the three audited Dust2 stone/roof VMTs.

Factory-startup Blender provides the pinned native decoder. Original GLB, PNGs,
VTFs and base-mip identity remain unchanged; output is a separate owned sidecar.
"""
from pathlib import Path
import hashlib
import io
import json
import runpy
import struct
import zipfile

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'public/source/csgo-12426148/fidelity-world-20260913/prop-mips'
sha = lambda b: hashlib.sha256(b).hexdigest()


def main():
    h = runpy.run_path(str(ROOT / 'scripts/inventory-source-items.py'))
    context = h['initialize'](); sources = h['Sources']()
    import numpy as np
    from SourceIO.library.utils.pylib.vtf import load_vtf_texture
    from SourceIO.library.utils.pylib.image import encode_png
    base = ROOT / '.reference-assets/source-exports/dust2'
    props = json.loads((base / 'props-manifest.json').read_text())
    doc, _, raw_glb = runpy.run_path(str(ROOT / 'scripts/map-source-prop-vhv.py'))['glb'](base / 'props.glb')
    assert sha(raw_glb) == '55937fce28a53461520fa2c531384f65f0f8b69df1a8205245466b6064ab5232'
    bsp = (ROOT / '.reference-assets/csgo-legacy/csgo/maps/de_dust2.bsp').read_bytes()
    assert sha(bsp) == 'b91be410539fbbfc16300423f1e19c024f12addf1429c8cb2f72b53fe0fd6bcc'
    start, size = struct.unpack_from('<2I', bsp, 8 + 40 * 16)
    pak = zipfile.ZipFile(io.BytesIO(bsp[start:start + size])); members = {p.lower(): p for p in pak.namelist()}
    def read(path): return pak.read(members[path]) if path in members else sources.read(path)
    OUT.mkdir(parents=True, exist_ok=True)
    def save(file, data):
        (OUT / file).write_bytes(data)
        return dict(file=file, bytes=len(data), sha256=sha(data))
    names = ('hr_dust_stone_ground_01_color', 'hr_dust_stone_ground_02_color', 'dust_kasbah_rooftrim_01')
    textures = []
    for source in props['materials']:
        if source['source'].rsplit('/', 1)[-1] not in names: continue
        mi, material = next((i, m) for i, m in enumerate(doc['materials']) if m['name'] == source['name'])
        for slot, key in (('map', '$basetexture'), ('normalMap', '$bumpmap')):
            path = 'materials/' + source['parameters'][key].replace('\\', '/').lower().removesuffix('.vtf') + '.vtf'
            raw = read(path)
            frozen = next(t for t in props['textures'] if t['source'].replace('\\', '/').lower() == path)
            assert sha(raw) == frozen['sourceSha256']
            pixels, w, height, floating = load_vtf_texture(raw); assert not floating
            info = material['normalTexture'] if slot == 'normalMap' else material['pbrMetallicRoughness']['baseColorTexture']
            levels = []
            for mip in range(1, raw[56]):
                pixels, mw, mh, floating = load_vtf_texture(raw, 0, 0, mip); assert not floating
                rgba = np.frombuffer(pixels, np.uint8).reshape(mh, mw, 4).copy()
                # Match the immutable GLB normal convention; the existing VHV
                # shader already restores Source green exactly once.
                if frozen['normalGreenInverted']: rgba[:, :, 1] = 255 - rgba[:, :, 1]
                png = encode_png(rgba.tobytes(), mw, mh, 4)
                levels.append(dict(level=mip, width=mw, height=mh, rgbaSha256=sha(rgba.tobytes()),
                    **save(sha(raw)[:16] + '-' + str(mip) + '.png', png)))
            assert levels[-1]['width'] == levels[-1]['height'] == 1
            textures.append(dict(materialIndex=mi, material=source['source'], slot=slot, textureIndex=info['index'],
                source=path, sourceSha256=sha(raw), width=w, height=height, mipCount=raw[56],
                normalGreenInverted=frozen['normalGreenInverted'], levels=levels))
    assert len(textures) == 6
    manifest = dict(format='source-prop-authored-mips-v1', sourceBspSha256=sha(bsp), originalGLBSha256=sha(raw_glb),
        textures=textures, provenance=context, scope='Original authored mip1..last; immutable GLB supplies exact existing mip0.')
    receipt = save('manifest.json', (json.dumps(manifest, indent=2) + '\n').encode())
    (ROOT / 'game/source-map-prop-mips-data.ts').write_text('/** Original sidecar receipt; generated by export-source-prop-mips.py. */\nexport const SOURCE_PROP_MIPS_RECEIPT = ' + json.dumps(receipt) + ' as const;\n')
    print(json.dumps(dict(receipt=receipt, textures=len(textures), mipImages=sum(len(t['levels']) for t in textures),
        pngBytes=sum(l['bytes'] for t in textures for l in t['levels'])), indent=2))


if __name__ == '__main__': main()
