"""Embed the exact original read-only float table for synchronous browser use."""
import base64,hashlib
from pathlib import Path
root=Path(__file__).resolve().parents[1]
data=(root/'.reference-assets/source-exports/pistol-particles-r2/original-random-floats.bin').read_bytes()
assert len(data)==16384 and hashlib.sha256(data).hexdigest()=='355816ca0d97ac2d71ab5e710ad7b508a87c564a6f8772af460a6ea3ee5987c1'
b64=base64.b64encode(data).decode()
(root/'game/source-pistol-particles-random-data.ts').write_text('''// Generated by scripts/export-source-pistol-particle-random.py.
// Original client SHA256 21d2d652a3b2e07c44fa0a3b638886744af9d24ba0c91e64f97a0d8afc43d4cb.
// VA 0x14c7da0: 4096 little-endian float32 values, unchanged.
export const SOURCE_PISTOL_PARTICLE_RANDOM_TABLE_SHA256='355816ca0d97ac2d71ab5e710ad7b508a87c564a6f8772af460a6ea3ee5987c1';
export const SOURCE_PISTOL_PARTICLE_RANDOM_TABLE_BASE64=\n'''+ '\n'.join(" '"+b64[i:i+128]+"'"+(';'if i+128>=len(b64)else'+')for i in range(0,len(b64),128))+'\n')
