import*as T from'three';
import{loadSourcePistolCharacter,type SourcePistolCharacterActor}from'../game/source-pistol-character';
import{sampleSourcePistolCharacterPose,type SourcePistolCharacterPoseInput,type SourcePistolWorldParameters}from'../game/source-pistol-character-pose';
import type{SourceCharacterState}from'../game/source-character-pose';
const renderer=new T.WebGLRenderer({canvas:document.querySelector('canvas')!,antialias:true});renderer.setPixelRatio(1);renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;
const scene=new T.Scene();scene.background=new T.Color('#26333f');scene.add(new T.HemisphereLight('#dce8f0','#83735a',1.3));const sun=new T.DirectionalLight('#ffe1bb',3);sun.position.set(-2,4,-3);scene.add(sun);const fill=new T.DirectionalLight('#c7dbff',1.8);fill.position.set(3,2,2);scene.add(fill);const camera=new T.PerspectiveCamera(45,innerWidth/innerHeight,.01,30);
let owner:Awaited<ReturnType<typeof loadSourcePistolCharacter>>|null=null,actor:SourcePistolCharacterActor|null=null,token=0,input:SourcePistolCharacterPoseInput|null=null;
let lastWorldDelta=0,poseBoneDelta=0;const status=document.querySelector('#status')!;const values=(selector:string)=>(document.querySelector(selector)as HTMLInputElement).value;
function angle(close=false){camera.position.set(close?-.75:2.15,close?1.5:1.5,close?-1.65:-3.6);camera.lookAt(close?new T.Vector3(0,1.25,-.15):new T.Vector3(0,.92,0));camera.updateProjectionMatrix();render();}
function render(){renderer.render(scene,camera);}
function audit(){const p=actor?.lastPose;return{loaded:!!actor,team:owner?.manifest.team,weapon:owner?.manifest.weaponId,poseVersion:owner?.manifest.poseVersion,hashVerified:owner?Object.values(owner.hashVerified).every(Boolean):false,status:actor?.status,input,autoLayers:p?.world.autoLayers,bodyBones:actor?.bodyBones.length,worldBones:actor?.worldBones.length,bodygroups:actor?Object.fromEntries(Object.entries(actor.bodygroups).map(([k,v])=>[k,v.map(o=>o.visible)])):null,maxPureRendererBoneDifferenceMeters:poseBoneDelta,weaponWorldDifferenceFromPrevious:lastWorldDelta,memory:{...renderer.info.memory,programs:renderer.info.programs?.length},draw:{...renderer.info.render},materialAudit:owner?.surfaces.materials,boundary:'Explicit test-fixture state/action/weights, complete original graph sampling. No closed AnimState, player movement, combat timers or IK.'};}
function sample(state:SourceCharacterState='Idle',action='hold',cycle=.3,weight=1,close=false,blended=false){if(!owner||!actor)throw Error('Load pistol character first');const aimKeys=['aim_blend_stand_idle','aim_blend_stand_walk','aim_blend_stand_run','aim_blend_crouch_idle','aim_blend_crouch_walk']as const,stateIds=['Idle','Walk','Run','Crouch_Idle','Crouch_Walk'];const parameters:SourcePistolWorldParameters={body_yaw:17,body_pitch:-9,...Object.fromEntries(aimKeys.map((k,i)=>[k,stateIds[i]===state?1:0]))}as SourcePistolWorldParameters;if(blended){for(const k of aimKeys)parameters[k]=0;parameters.aim_blend_stand_idle=.35;parameters.aim_blend_stand_walk=.65;}
 const moving=state==='Walk'||state==='Run'||state==='Crouch_Walk',crouch=state.startsWith('Crouch'),bodyLayers=[],worldLayers=[];let silencerVisible=true,magazineVisible=true;
 if(action==='reload'){bodyLayers.push({sequence:'Reload_PISTOL',cycle,weight});worldLayers.push({sequence:'pistol_reload'+(crouch?'_crouch':'')+(moving?'_moving':''),cycle,weight});magazineVisible=cycle<.15||cycle>.65;}
 if(action==='attach'||action==='detach'){if(owner.manifest.weaponId!=='usp')throw Error('Glock has no silencer');bodyLayers.push({sequence:action==='attach'?'Silencer_Attach_Pistol':'Silencer_Detach_Pistol',cycle,weight});worldLayers.push({sequence:'pistol_silencer_'+(action==='attach'?'ON':'OFF')+(crouch?'_crouch':moving?'_moving':''),cycle,weight});silencerVisible=action==='attach'?cycle>=.5:cycle<.5;}
 if(action==='fire')worldLayers.push({sequence:crouch?'pistol_fire_crouch':'pistol_fire',cycle,weight});
 for(const[id,value]of [['state',state],['action',action],['cycle',String(cycle)],['weight',String(weight)]])(document.querySelector('#'+id)as HTMLInputElement).value=value;(document.querySelector('#close')as HTMLInputElement).checked=close;
 input={body:{state,cycle,upperCycle:cycle,parameters:{move_x:moving?.57:0,move_y:moving?-.42:0,body_yaw:17,body_pitch:-9},fireCycle:cycle,fireWeight:action==='fire'?weight:0},bodyLayers,world:{parameters,cycle,layers:worldLayers},silencerVisible,magazineVisible};const previous=actor.lastPose?.sourceWeaponWorldMatrices.slice();owner.updateActor(actor,{x:0,y:0,z:0,yaw:0,sourceContract:'csgo-player-12426148',sourcePoseVersion:owner.manifest.poseVersion,sourcePistolPose:input});angle(close);render();
 const pure=sampleSourcePistolCharacterPose(owner.poseIndex,input),C=new T.Matrix4().set(1,0,0,0,0,0,1,0,0,-1,0,0,0,0,0,1),outer=actor.root.matrixWorld.clone().multiply(new T.Matrix4().makeScale(.0254,.0254,.0254)).multiply(C);poseBoneDelta=0;
 for(const[bones,world]of[[actor.bodyBones,pure.body.sourceWorldMatrices],[actor.worldBones,pure.sourceWeaponWorldMatrices]]as const)for(let i=0;i<bones.length;i++){const expected=outer.clone().multiply(new T.Matrix4().fromArray(world,i*16));poseBoneDelta=Math.max(poseBoneDelta,...expected.elements.map((v,j)=>Math.abs(v-bones[i].matrixWorld.elements[j])));}
 lastWorldDelta=previous?Math.max(...pure.sourceWeaponWorldMatrices.map((v,i)=>Math.abs(v-previous[i]))):0;status.textContent=`${owner.manifest.team.toUpperCase()} / ${owner.manifest.weaponId} · ${state} / ${action} · cycle ${cycle.toFixed(2)} · weight ${weight.toFixed(2)}`;return audit();}
function unload(){++token;owner?.dispose();owner=null;actor=null;input=null;render();status.textContent='已卸载';return audit();}
async function load(team:'t'|'ct',weapon:'glock'|'usp'){unload();const generation=token;status.textContent='原文件 SHA 校验中…';const next=await loadSourcePistolCharacter({team,weapon});if(generation!==token){next.dispose();return;}owner=next;(document.querySelector('#team')as HTMLInputElement).value=team;(document.querySelector('#weapon')as HTMLInputElement).value=weapon;actor=next.createActor();scene.add(actor.root);return sample();}
function identityReject(){if(!actor||!owner||!input)throw Error('No actor');owner.updateActor(actor,{x:0,y:0,z:0,yaw:0,sourceContract:'csgo-player-12426148',sourcePoseVersion:'rifle-mismatch',sourcePistolPose:input});render();return{visible:actor.root.visible,status:actor.status};}
(document.querySelector('#load')as HTMLButtonElement).onclick=()=>void load(values('#team')as't'|'ct',values('#weapon')as'glock'|'usp').catch(e=>status.textContent=String(e));
(document.querySelector('#sample')as HTMLButtonElement).onclick=()=>{try{sample(values('#state')as SourceCharacterState,values('#action'),Number(values('#cycle')),Number(values('#weight')),(document.querySelector('#close')as HTMLInputElement).checked);}catch(e){status.textContent=String(e);}};(document.querySelector('#unload')as HTMLButtonElement).onclick=unload;
(window as unknown as Record<string,unknown>).__PISTOL_CHARACTER_PREVIEW__={load,sample,audit,unload,identityReject};angle();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);render();});void load('t','glock').catch(e=>status.textContent=String(e));
