import*as T from'three';import{loadAKDrawCandidate,type AKDrawTeam}from'./source-ak-draw-candidate';
import{sampleSourceViewmodel,startSourceDraw,sourceViewmodelPlayback,updateSourceViewmodel,inspectSourceViewmodel,sourceAttachment}from'../game/source-viewmodel';
import{advanceSourceSoundEvents,type SourceSoundCursor}from'../game/source-sound-timeline';
const renderer=new T.WebGLRenderer({canvas:document.querySelector('canvas')!,antialias:true});renderer.setPixelRatio(1);renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;
const scene=new T.Scene();scene.background=new T.Color('#26333f');scene.add(new T.HemisphereLight('#cfdef0','#6e634c',.35));const light=new T.DirectionalLight('#ffdfb3',3.1);light.position.set(-1,2,1);scene.add(light);const camera=new T.PerspectiveCamera(70,innerWidth/innerHeight,.01,20);
const status=document.querySelector('#status')!;let owner:Awaited<ReturnType<typeof loadAKDrawCandidate>>|null=null,gun:T.Group|null=null,token=0;let context:AudioContext|null=null,buffers:Record<string,AudioBuffer>={};let playing=false,clock=0,last=performance.now(),cursor:SourceSoundCursor|undefined,soundRecords:unknown[]=[],audioOrigin=0;
let scheduleOffset=0; // Each event starts when its original clip threshold is crossed.
function render(){renderer.render(scene,camera);}
function armDifference(){if(!gun)return 0;const weapon=new Map<string,T.Bone>(),arms:T.Bone[]=[];gun.traverse(o=>{if(o instanceof T.Bone){if(o.userData.sourceFPSkin==='weapon')weapon.set(o.userData.sourceFPBoneName,o);else if(o.userData.sourceFPSkin==='arms')arms.push(o);}});let max=0;for(const a of arms){const b=weapon.get(a.userData.sourceFPBoneName);if(b)max=Math.max(max,...a.matrixWorld.elements.map((x,i)=>Math.abs(x-b.matrixWorld.elements[i])));}return max;}
function audit(){return{loaded:!!gun,team:owner?.team,hashVerified:owner?.hashVerified,glbSHA:owner?.glbSHA,detail:gun?inspectSourceViewmodel(gun):null,playback:gun?sourceViewmodelPlayback(gun):null,sameNameArmWorldErrorMeters:armDifference(),attachment:gun?{muzzle:sourceAttachment(gun,'muzzle',camera).elements,ejection:sourceAttachment(gun,'ejection',camera).elements}:null,soundRecords,audio:context?{state:context.state,sampleRate:context.sampleRate,baseLatency:context.baseLatency,outputLatency:context.outputLatency,decoded:Object.fromEntries(Object.entries(buffers).map(([n,b])=>[n,{sampleRate:b.sampleRate,length:b.length,numberOfChannels:b.numberOfChannels,duration:b.duration}]))}:null,playing,memory:{...renderer.info.memory,programs:renderer.info.programs?.length},draw:{...renderer.info.render},scope:'Private candidate; neutral preview lights; no deploy timer or physical speaker capture claim'};}
function sample(time:number){if(!gun)throw Error('Candidate unavailable');playing=false;sampleSourceViewmodel(gun,'draw',time);render();status.textContent=`${owner!.team.toUpperCase()} 原 AK draw · ${time.toFixed(4)} s`;return audit();}
function emitSounds(){if(!gun||!owner||!context)throw Error('Candidate audio unavailable');const current=sourceViewmodelPlayback(gun),events=current.pose==='draw'?owner.manifest.drawSoundEvents.map(e=>({time:e.timeSeconds,event:e.options.toLowerCase()})):[];const next=advanceSourceSoundEvents(cursor,current,events);cursor=next.cursor;for(const event of next.events){const source=context.createBufferSource(),gain=context.createGain(),at=context.currentTime+scheduleOffset;source.buffer=buffers[event];if(!source.buffer)throw Error('Missing original WAV '+event);source.playbackRate.value=1;gain.gain.value=event==='weapon_ak47.draw'?.3:1;source.connect(gain).connect(context.destination);source.onended=()=>{source.disconnect();gain.disconnect();};source.start(at);soundRecords.push({event,generation:current.generation,sampledPose:current.pose,sampledTime:current.time,originalEventTime:events.find(e=>e.event===event)!.time,audioStartAt:at,audioStartRelativeToDraw:at-audioOrigin,volume:gain.gain.value,pitch:100,reason:'Original clip threshold via production advanceSourceSoundEvents; deterministic allowed original pitch100'});}}
async function play(){if(!gun||!context)throw Error('Load first');await context.resume();clock=0;cursor=undefined;soundRecords=[];audioOrigin=context.currentTime;startSourceDraw(gun);emitSounds();playing=true;last=performance.now();return audit();}
function cancel(){if(!gun)return;playing=false;updateSourceViewmodel(gun,undefined,0,true);emitSounds();render();return audit();}
function repeatRead(){emitSounds();return audit();}
function unload(){++token;playing=false;owner?.dispose();owner=null;gun=null;buffers={};soundRecords=[];void context?.close();context=null;render();status.textContent='已卸载';return audit();}
async function load(team:AKDrawTeam){unload();const at=token,next=await loadAKDrawCandidate(team);if(at!==token){next.dispose();return;}owner=next;context=new AudioContext({sampleRate:44100});const sounds=[['weapon_ak47.draw','ak47_draw.wav'],['weapon_ak47.boltpull','ak47_boltpull.wav']];buffers=Object.fromEntries(await Promise.all(sounds.map(async([event,file])=>[event,await context!.decodeAudioData((await next.bytes('sounds/'+file)).buffer as ArrayBuffer)])));gun=next.createViewmodel();scene.add(gun);(document.querySelector('#team')as HTMLInputElement).value=team;return sample(.6);}
(document.querySelector('#load')as HTMLButtonElement).onclick=()=>void load((document.querySelector('#team')as HTMLInputElement).value as AKDrawTeam).catch(e=>status.textContent=String(e));(document.querySelector('#play')as HTMLButtonElement).onclick=()=>void play();(document.querySelector('#cancel')as HTMLButtonElement).onclick=cancel;(document.querySelector('#unload')as HTMLButtonElement).onclick=unload;(document.querySelector('#sample')as HTMLButtonElement).onclick=()=>sample(Number((document.querySelector('#time')as HTMLInputElement).value));
function frame(now:number){const dt=Math.min(.1,(now-last)/1000);last=now;if(playing&&gun){clock+=dt;updateSourceViewmodel(gun,undefined,dt);emitSounds();status.textContent=`${owner!.team.toUpperCase()} 原 AK draw · ${Math.min(1,clock).toFixed(4)} s`;if(clock>1.1)playing=false;}render();requestAnimationFrame(frame);}requestAnimationFrame(frame);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});(window as unknown as Record<string,unknown>).__AK_DRAW_PREVIEW__={load,sample,audit,play,cancel,repeatRead,unload};void load('t').catch(e=>status.textContent=String(e));
