/** Generate the port's buy zones from the shipped map data, with the reader's own checks.
 *
 * The volumes are the collision artifact's `func_buyzone` sensors; the team of each comes
 * from the map's own entity list, matched by the hammer id both files carry. The generated
 * module is what the simulation reads, and the test that covers it compares it back to
 * these two files, so a re-export that moved a zone or changed a team is visible.
 *
 * Run: npx tsx scripts/probe-source-buy-zones.ts
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createSourceBuyZones } from '../game/source-buy-zone';

const root = resolve(import.meta.dirname, '..');
const collisionPath = resolve(root, 'public/source/csgo-12426148/dust2/collision.json');
const entitiesPath = resolve(root, '.reference-assets/source-exports/dust2/source-metadata/entities.json');
const collisionText = readFileSync(collisionPath, 'utf8');
const entityText = readFileSync(entitiesPath, 'utf8');
const collisionBytes = Buffer.from(collisionText, 'utf8');
const entityBytes = Buffer.from(entityText, 'utf8');
const collisionDocument: unknown = JSON.parse(collisionText);
const entityList: unknown = JSON.parse(entityText);
const zones = createSourceBuyZones(collisionDocument, entityList);
const sha256 = (bytes: Buffer) => createHash('sha256').update(bytes).digest('hex');
const round = (value: number) => Number(value.toFixed(6));
const rows = zones.map((zone) => `  { hammerId: '${zone.hammerId}', team: ${zone.team}, `
  + `min: [${zone.min.map(round).join(', ')}], max: [${zone.max.map(round).join(', ')}] },`).join('\n');
writeFileSync(resolve(root, 'game/source-buy-zone-data.ts'), `/** The original Dust2 buy zones, generated from the shipped map data.
 *
 * Generated by \`scripts/probe-source-buy-zones.ts\` from the collision artifact's
 * \`func_buyzone\` sensor brushes and the map's own entity list, matched by hammer id.
 * Each is a box in the collision artifact's own frame; the test that covers them reads both
 * files back and compares, so this table cannot drift from them silently.
 *
 * Source hashes at generation:
 *   collision.json  ${sha256(collisionBytes)}
 *   entities.json   ${sha256(entityBytes)}
 */
import type { SourceBuyZone } from './source-buy-zone.js';

export const SOURCE_BUY_ZONES: readonly SourceBuyZone[] = [
${rows}
];

export const SOURCE_BUY_ZONE_SOURCES = {
  collisionJsonSha256: '${sha256(collisionBytes)}', entitiesJsonSha256: '${sha256(entityBytes)}',
} as const;
`);
process.stdout.write(`buy zones: ${zones.map((zone) => `${zone.hammerId} team ${zone.team} `
  + `[${zone.min.map(round).join(',')}]..[${zone.max.map(round).join(',')}]`).join(' | ')}\n`);
