"""Stage the original per-weapon kill award as build data.

Reads `research/source-kill-awards.json` (written by
`scripts/export-source-kill-awards.py` from the shipped `items_game.txt`) and writes:

  game/source-kill-award-table.ts        what both the client and the authority read
  public/source/csgo-12426148/economy/kill-awards.json   the same table, for other tools
  game/source-kill-award-resources.json   byte count and SHA-256 of the staged table

The port's own weapon ids are not invented here either: the weapon -> original item
mapping is the one the shipped file's `prefab` rows already gave, and the mapping this
build ships (port id -> original prefab) is read out of the staged weapon-effect map so
there is one place that says which original weapon each port weapon is. Every port
weapon the table maps is cross-checked against the export: the exported weapon item must
carry exactly that prefab, or this refuses to write a table.

Run: python3 scripts/stage-source-kill-awards.py
"""
from __future__ import annotations
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPORT = ROOT / 'research/source-kill-awards.json'
EFFECT_MAP = ROOT / 'public/source/csgo-12426148/weapon-effects/effect-map.json'
STAGED = ROOT / 'public/source/csgo-12426148/economy/kill-awards.json'
TABLE = ROOT / 'game/source-kill-award-table.ts'
RECEIPT = ROOT / 'game/source-kill-award-resources.json'

export = json.loads(EXPORT.read_text(encoding='utf-8'))
effect_map = json.loads(EFFECT_MAP.read_text(encoding='utf-8'))

if export.get('format') != 'source-kill-awards-v1':
    raise ValueError('Unexpected kill-award export format')
weapons: dict[str, dict] = export['weapons']
prefab_awards: dict[str, int] = export['prefabAwards']
default_award = int(export['defaultAward']['award'])
default_owner = export['defaultAward']['owner']

# The port's weapons, from the one place that already says which original weapon each
# one is: the staged weapon-effect map's own `prefabs` block.
port_prefabs: dict[str, str] = effect_map['prefabs']
mapped: dict[str, dict] = {}
for port_id, prefab in sorted(port_prefabs.items()):
    matches = [name for name, row in weapons.items() if row['prefab'] == prefab]
    if len(matches) != 1:
        raise ValueError(f'{port_id}: the export does not give exactly one weapon for {prefab}: {matches}')
    name = matches[0]
    row = weapons[name]
    mapped[port_id] = {'originalWeapon': name, 'prefab': prefab, 'award': int(row['award']),
                       'owner': row['owner'], 'chain': list(row['chain'])}

# The utilities this build can kill with. The shipped file gives the HE grenade the base
# award through its own prefab chain; the smoke and the flash deal no damage.
utility_rows = {}
for utility, original in (('he', 'weapon_hegrenade'), ('smoke', 'weapon_smokegrenade'), ('flash', 'weapon_flashbang')):
    row = weapons.get(original)
    if row is None:
        raise ValueError(f'The export no longer carries {original}')
    utility_rows[utility] = {'originalWeapon': original, 'award': int(row['award']),
                             'owner': row['owner'], 'chain': list(row['chain'])}

staged = {
    'format': 'source-kill-award-table-v1',
    'source': export['source'],
    'sourceSha256': export['receipt']['sha256'],
    'default': {'owner': default_owner, 'award': default_award},
    'prefabAwards': prefab_awards,
    'portWeapons': mapped,
    'portUtilities': utility_rows,
    'weapons': weapons,
    'modeConfigCrossCheck': export['modeConfigCrossCheck'],
}
STAGED.parent.mkdir(parents=True, exist_ok=True)
STAGED.write_text(json.dumps(staged, indent=1, ensure_ascii=False) + '\n', encoding='utf-8')
staged_bytes = STAGED.read_bytes()


lines = [
    '/** Generated by `scripts/stage-source-kill-awards.py` from the shipped',
    ' * `scripts/items/items_game.txt`. Do not edit by hand; run the script instead.',
    ' *',
    ' * The original states the cash a kill pays as the `kill award` attribute of a weapon or',
    ' * of a prefab it inherits from. Fifteen prefabs state one of their own; every other',
    f' * weapon inherits `{default_owner}`\'s {default_award}, which is also what both shipped',
    ' * competitive configs set `cash_player_killed_enemy_default` to. Each weapon below',
    ' * carries the owner and the chain its award was resolved through, so the value can be',
    ' * traced back to one row of the shipped file.',
    ' */',
    "export const SOURCE_KILL_AWARD_FORMAT = 'source-kill-award-table-v1';",
    f"export const SOURCE_KILL_AWARD_SOURCE_SHA256 = '{export['receipt']['sha256']}';",
    f'export const SOURCE_KILL_AWARD_DEFAULT = {default_award};',
    f"export const SOURCE_KILL_AWARD_DEFAULT_OWNER = '{default_owner}';",
    '',
    '/** The prefabs that state an award of their own, exactly as the file writes them. */',
    'export const SOURCE_KILL_AWARD_PREFABS: Record<string, number> = {',
]
for name, award in sorted(prefab_awards.items()):
    lines.append(f'  "{name}": {award},')
lines += ['};', '',
          '/** Every weapon the shipped file defines, with the award it resolves to. */',
          'export const SOURCE_KILL_AWARD_ORIGINAL_WEAPONS: Record<string, { award: number; owner: string; chain: readonly string[] }> = {',
          ]
for name, row in sorted(weapons.items()):
    chain = ', '.join(f'"{step}"' for step in row['chain'])
    lines.append(f'  "{name}": {{ award: {row["award"]}, owner: "{row["owner"]}", chain: [{chain}] }},')
lines += ['};', '',
          '/** The weapons this build ships, each with the original item it is. The mapping is',
          ' * the staged weapon-effect map\'s own `prefabs` block, cross-checked here against the',
          ' * `prefab` the shipped file gives that weapon item. */',
          'export const SOURCE_KILL_AWARD_PORT_WEAPONS: Record<string, { originalWeapon: string; award: number; owner: string }> = {',
          ]
for port_id, row in sorted(mapped.items()):
    lines.append(f'  "{port_id}": {{ originalWeapon: "{row["originalWeapon"]}", award: {row["award"]}, owner: "{row["owner"]}" }},')
lines += ['};', '',
          '/** The utilities this build can kill with. */',
          'export const SOURCE_KILL_AWARD_PORT_UTILITIES: Record<string, { originalWeapon: string; award: number; owner: string }> = {',
          ]
for utility, row in sorted(utility_rows.items()):
    lines.append(f'  "{utility}": {{ originalWeapon: "{row["originalWeapon"]}", award: {row["award"]}, owner: "{row["owner"]}" }},')
lines += ['};', '',
          '/** The staged table as one value, so the reader can validate it and so a test can',
          ' * hand it a broken one and watch it refuse. */',
          'export const SOURCE_KILL_AWARD_TABLE = {',
          '  format: SOURCE_KILL_AWARD_FORMAT,',
          '  sourceSha256: SOURCE_KILL_AWARD_SOURCE_SHA256,',
          f'  default: {{ owner: SOURCE_KILL_AWARD_DEFAULT_OWNER, award: SOURCE_KILL_AWARD_DEFAULT }},',
          '  prefabAwards: SOURCE_KILL_AWARD_PREFABS,',
          '  weapons: SOURCE_KILL_AWARD_ORIGINAL_WEAPONS,',
          '  portWeapons: SOURCE_KILL_AWARD_PORT_WEAPONS,',
          '  portUtilities: SOURCE_KILL_AWARD_PORT_UTILITIES,',
          '} as const;', '',
          'export const SOURCE_KILL_AWARD_LIMITATIONS = [']
# Written out as single-quoted TypeScript strings, so an apostrophe in the prose has to be
# escaped rather than closing the literal.
for limitation in (
    "The shipped file gives the weapon's own award; the mode config scales it by "
    "`cash_player_killed_enemy_factor`, which both shipped competitive formats set to 1. A "
    "factor other than 1 is not documented by any shipped file, so this build applies the "
    "factor the same way it already applied it to the default award.",
    "A weapon this build ships that is not one of the original's own (its own VX-9 / FALCON "
    "placeholders) keeps the original base award: the shipped file gives no award for a weapon "
    "it does not define, and borrowing another class's award would be an invented mapping.",
    "The four weapon classes the file distinguishes beyond the default - melee 1500, SMGs 600, "
    "shotguns 900, the AWP and CZ75 100, the taser 0 - are staged whole, so a weapon added "
    "later resolves without touching this table.",
):
    lines.append("  '" + limitation.replace('\\', '\\\\').replace("'", "\\'") + "',")
lines += ['  ] as const;',
          '']
TABLE.write_text('\n'.join(lines), encoding='utf-8')
receipt = {'format': 'source-kill-award-resources-v1', 'source': export['source'],
           'sourceReceipt': export['receipt'],
           'staged': {'path': 'economy/kill-awards.json', 'bytes': len(staged_bytes),
                      'sha256': hashlib.sha256(staged_bytes).hexdigest()},
           'table': 'game/source-kill-award-table.ts'}
RECEIPT.write_text(json.dumps(receipt, indent=1, ensure_ascii=False, default=str) + '\n', encoding='utf-8')

print('port weapons', {k: (v['originalWeapon'], v['award']) for k, v in sorted(mapped.items())})
print('utilities', {k: v['award'] for k, v in sorted(utility_rows.items())})
print('prefab awards', prefab_awards)
print('staged', STAGED.relative_to(ROOT), len(staged_bytes), 'bytes')
print('table rows', len(weapons), 'weapons')
