"""Stage the original competitive mode's economy and round timing as build data.

The shipped dedicated-server install carries the effective mode config in
`csgo/cfg/gamemode_competitive.cfg` (and `gamemode_competitive_short.cfg`, which
overrides two keys of it). Those are the values the original server actually
applies, so they are read directly rather than inferred: every staged number
keeps the line it came from and the file keeps its byte count and SHA-256.

Run: python3 scripts/stage-source-gamemode.py
"""
from __future__ import annotations
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GAME = ROOT / '.reference-assets/csgo-legacy/csgo/cfg'
BASE = 'gamemode_competitive.cfg'
SHORT = 'gamemode_competitive_short.cfg'
DEST = ROOT / 'game/source-gamemode-competitive.ts'

# Only the keys this build's authority actually applies. A key that the original
# no longer ships must fail here rather than quietly keep a local default.
KEYS = (
    # player cash
    'cash_player_bomb_defused', 'cash_player_bomb_planted', 'cash_player_killed_enemy_default',
    'cash_player_killed_enemy_factor', 'cash_player_killed_teammate',
    # friendly-fire and observer rules
    'ff_damage_reduction_bullets', 'ff_damage_reduction_grenade',
    'ff_damage_reduction_grenade_self', 'ff_damage_reduction_other',
    # team cash
    'cash_team_elimination_bomb_map', 'cash_team_terrorist_win_bomb', 'cash_team_win_by_defusing_bomb',
    'cash_team_win_by_time_running_out_bomb', 'cash_team_planted_bomb_but_defused',
    'cash_team_loser_bonus', 'cash_team_loser_bonus_consecutive_rounds', 'mp_starting_losses',
    # Staged because it is shipped data (competitive sets it to 1000, the other modes to 0);
    # it stays unapplied because no shipped file defines what triggers it.
    'cash_team_bonus_shorthanded',
    # money
    'mp_startmoney', 'mp_maxmoney', 'mp_afterroundmoney',
    # round and match timing
    'mp_freezetime', 'mp_friendlyfire', 'mp_forcecamera', 'mp_buytime', 'mp_roundtime_defuse', 'mp_win_panel_display_time',
    'mp_maxrounds', 'mp_halftime', 'mp_match_can_clinch',
)
# Keys the staged file is expected to carry a value for, but that the shipped
# config does not define. Recorded explicitly so the runtime declares the adapter
# instead of inventing a default.
ABSENT = ('mp_consecutive_loss_max',)


def parse(path: Path) -> dict[str, dict[str, object]]:
    values: dict[str, dict[str, object]] = {}
    for number, raw in enumerate(path.read_text(encoding='utf-8', errors='replace').splitlines(), start=1):
        code = raw.split('//', 1)[0].strip()
        if not code:
            continue
        parts = code.split()
        if len(parts) == 2:
            values[parts[0]] = {'value': parts[1], 'line': number}
    return values


def block(name: str, path: Path, complete: bool = True) -> dict[str, object]:
    data = path.read_bytes()
    values = parse(path)
    selected = {key: values[key] for key in KEYS if key in values}
    missing = [key for key in KEYS if key not in values]
    if complete and missing:
        raise ValueError(f'{path.name} is missing original keys: {missing}')
    return {'mode': name, 'source': path.name, 'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest(),
            'lineCount': data.count(b'\n') + 1, 'values': selected, 'absent': missing}


base = block('competitive', GAME / BASE)
# The short config is an override layer over the same mode, not a complete mode:
# it names only the keys it changes, so it is staged as the diff it actually is.
short = block('competitiveShort', GAME / SHORT, complete=False)
overrides = {key: short['values'][key] for key in short['values']
             if short['values'][key]['value'] != base['values'][key]['value']}
absent = {key: {'absentIn': [BASE, SHORT],
                'reason': 'not present in the shipped mode configs; the runtime declares this adapter'}
          for key in ABSENT}

payload = {'format': 'source-gamemode-competitive-v1', 'build': 12426148, 'application': 740,
           'sourceApp': 740, 'keys': list(KEYS), 'base': base, 'short': short,
           'shortOverrides': overrides, 'absent': absent,
           'boundaries': ['Values are the strings the original config ships, with the line they came from.',
                          'The short mode is this file plus the keys its own config overrides.',
                          'Per-weapon kill awards, the consecutive-loss cap and the hostage-map cash are not '
                          'defined by these files and are declared absent rather than guessed.']}
# Staged as a TypeScript module, like the original random table: both the browser
# bundle and the server's NodeNext compile read it without JSON import attributes.
DEST.write_text('/** Generated by scripts/stage-source-gamemode.py - do not edit by hand. */\n'
                'export const SOURCE_GAMEMODE_COMPETITIVE_STAGED = '
                + json.dumps(payload, indent=1, ensure_ascii=False) + ' as const;\n')

for mode, row in (('competitive', base), ('competitiveShort', short)):
    print(f"{mode}: {row['source']} {row['bytes']:,} bytes sha256 {str(row['sha256'])[:16]}… lines {row['lineCount']:,}")
    present = list(row['values'])
    print('   ' + ' '.join(f"{key}={row['values'][key]['value']}" for key in present[:6])
          + (f" (+{len(present) - 6} more)" if len(present) > 6 else ''))
print('short overrides:', json.dumps({k: v['value'] for k, v in overrides.items()}, ensure_ascii=False))
print('declared absent:', list(absent))
print(f'wrote {DEST.relative_to(ROOT)}')
