import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import assert from'node:assert/strict';import*as T from'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import{createRequire}from'node:module';
const{validateBytes}=createRequire(import.meta.url)('gltf-validator')as{validateBytes:(bytes:Uint8Array,options:{maxIssues:number})=>Promise<{issues:{numErrors:number;numWarnings:number;messages:unknown[]}}>};
import{AK_DRAW_CANDIDATES,AK_DRAW_TEXTURES,createAKDrawCandidate,type AKDrawTeam}from'./source-ak-draw-candidate';import{sampleSourceViewmodel,sourceAttachment,disposeSourceViewmodel,startSourceDraw,updateSourceViewmodel,sourceViewmodelPlayback}from'../game/source-viewmodel';
const dir='.reference-assets/source-exports/ak47-draw-candidates/',sha=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
function raw(path:string){const b=readFileSync(path),n=new DataView(b.buffer,b.byteOffset,b.byteLength).getUint32(12,true);return{b,doc:JSON.parse(b.subarray(20,20+n).toString()),bin:b.subarray(28+n)};}
async function load(path:string){const r=raw(path),d=structuredClone(r.doc);d.materials=d.materials.map((m:{name:string})=>({name:m.name}));delete d.images;delete d.textures;delete d.extensionsUsed;delete d.extensionsRequired;d.buffers=[{byteLength:r.bin.length,uri:'data:application/octet-stream;base64,'+Buffer.from(r.bin).toString('base64')}];return new GLTFLoader().parseAsync(JSON.stringify(d),'');}
if(!globalThis.ProgressEvent)globalThis.ProgressEvent=class{constructor(type:string,data:object){Object.assign(this,{type},data);}}as unknown as typeof ProgressEvent;
const C=new T.Matrix4().makeRotationX(-Math.PI/2),Ci=C.clone().invert(),unit=new T.Vector3(1,1,1),receipt=[];
const difference=(a:number[],b:number[])=>Math.max(...a.map((v,i)=>Math.abs(v-b[i])));
for(const team of ['t','ct']as AKDrawTeam[]){
 const old=raw('public/source/csgo-12426148/'+(team==='t'?'ak47':'ak47-ct')+'/viewmodel.glb'),candidate=raw(dir+team+'/viewmodel.glb');assert.equal(sha(candidate.b),AK_DRAW_CANDIDATES[team].glbSHA);assert.deepEqual(candidate.bin.subarray(0,old.bin.length),old.bin);
 for(const key of ['nodes','skins','meshes','materials','images','textures','samplers','scenes','scene','asset','extensionsUsed','extensionsRequired','extensions'])assert.deepEqual(candidate.doc[key],old.doc[key]);for(const key of ['animations','accessors','bufferViews'])assert.deepEqual(candidate.doc[key].slice(0,old.doc[key].length),old.doc[key]);
 const validator=await validateBytes(candidate.b,{maxIssues:30});assert.equal(validator.issues.numErrors,0,JSON.stringify(validator.issues));
 const [g,o]=await Promise.all([load(dir+team+'/viewmodel.glb'),load('public/source/csgo-12426148/'+(team==='t'?'ak47':'ak47-ct')+'/viewmodel.glb')]);const maps=Object.fromEntries(AK_DRAW_TEXTURES[team].map(n=>[n,new T.DataTexture(new Uint8Array([60,60,60,128]),1,1)]));const model=createAKDrawCandidate(g,team,maps),previous=createAKDrawCandidate(o,team,maps,false);
 const bones=(root:T.Object3D)=>{const out=new Map<string,T.Bone>();root.traverse(o=>{if(o instanceof T.Bone)out.set(o.userData.sourceFPSkin+':'+o.userData.sourceFPBoneName,o);});return out;},currentBones=bones(model),oldBones=bones(previous);const ibms=(root:T.Object3D)=>{const out:number[][][]=[];root.traverse(o=>{if(o instanceof T.SkinnedMesh)out.push(o.skeleton.boneInverses.map(m=>m.elements.slice()));});return out;},bindBefore=ibms(model);
 let oldClipSamples=0,oldDelta=0;for(const [pose,name]of Object.entries({idle:'idle__ak47_idle',fire:'fire__ak47_fire1',reload:'reload__ak47_reload',inspect:'inspect__lookat01'})){const clip=o.animations.find(a=>a.name===name)!;for(const time of new Set(Array.from(clip.tracks[0].times))){sampleSourceViewmodel(model,pose as 'idle',time);sampleSourceViewmodel(previous,pose as 'idle',time);for(const[key,b]of currentBones)oldDelta=Math.max(oldDelta,difference(b.matrixWorld.elements,oldBones.get(key)!.matrixWorld.elements));oldClipSamples++;}}assert.equal(oldDelta,0);
 const f=JSON.parse(readFileSync(dir+team+'/draw-source-frames.json','utf8'));let boneError=0,armsError=0,attachmentError=0,vertexError=0,vertexSamples=0;const outer=model.matrixWorld.clone().multiply(C);
 for(let frame=0;frame<31;frame++){
  sampleSourceViewmodel(model,'draw',frame/30);const world:T.Matrix4[]=[];for(let i=0;i<58;i++){const b=f.bones[i],local=new T.Matrix4().compose(new T.Vector3().fromArray(f.positions[frame][i]),new T.Quaternion().fromArray(f.quaternions[frame][i]),unit);world.push(b.parent<0?local:world[b.parent].clone().multiply(local));const actual=currentBones.get('weapon:'+b.name)!;boneError=Math.max(boneError,difference(actual.matrixWorld.elements,outer.clone().multiply(world[i]).elements));}
  for(const name of f.matchingBoneNames)armsError=Math.max(armsError,difference(currentBones.get('arms:'+name)!.matrixWorld.elements,currentBones.get('weapon:'+name)!.matrixWorld.elements));
  for(const [i,kind]of ['muzzle','ejection'].entries()){const a=f.attachments[i],m=new T.Matrix4().set(...[...a.matrix,0,0,0,1]as Parameters<T.Matrix4['set']>);const expect=C.clone().multiply(world[a.parent_bone]).multiply(m).multiply(Ci);attachmentError=Math.max(attachmentError,new T.Vector3().setFromMatrixPosition(sourceAttachment(model,kind as 'muzzle',model)).distanceTo(new T.Vector3().setFromMatrixPosition(expect)));}
  // Original source arm IBM independently skins actual GLB vertices; neither
  // this reference nor original raw matrices come from appended draw tracks.
  model.traverse(o=>{if(!(o instanceof T.SkinnedMesh)||o.skeleton.bones.length!==48)return;const refs=o.skeleton.bones.map(b=>{const i=f.bones.findIndex((r:{name:string})=>r.name===b.userData.sourceFPBoneName),raw=f.armsBones.find((r:{name:string})=>r.name===b.userData.sourceFPBoneName);return i<0?null:outer.clone().multiply(world[i]).multiply(new T.Matrix4().set(...raw.inverseBind.flat()as Parameters<T.Matrix4['set']>)).multiply(Ci);});const pos=o.geometry.attributes.position,weights=o.geometry.attributes.skinWeight,joints=o.geometry.attributes.skinIndex;
   for(let i=0;i<pos.count;i+=37){const point=new T.Vector3().fromBufferAttribute(pos,i);o.applyBoneTransform(i,point);o.localToWorld(point);const ref=new T.Vector3();let valid=true;for(let k=0;k<4;k++){const w=weights.getComponent(i,k);if(w){const m=refs[joints.getComponent(i,k)];if(!m){valid=false;break;}ref.addScaledVector(new T.Vector3().fromBufferAttribute(pos,i).applyMatrix4(m),w);}}if(valid){vertexError=Math.max(vertexError,point.distanceTo(ref));vertexSamples++;}}
  });
 }
 assert.ok(boneError<2e-6,'source bone meters '+boneError);assert.ok(armsError<2e-6,'arms meters '+armsError);assert.ok(attachmentError<.0001,'attachment source units '+attachmentError);assert.ok(vertexError<3e-6,'source IBM vertices meters '+vertexError);assert.deepEqual(ibms(model),bindBefore);
 startSourceDraw(model);const generation=sourceViewmodelPlayback(model).generation;assert.equal(sourceViewmodelPlayback(model).pose,'draw');updateSourceViewmodel(model,undefined,.1);assert.equal(sourceViewmodelPlayback(model).time,.1);updateSourceViewmodel(model,undefined,0,true);assert.equal(sourceViewmodelPlayback(model).pose,'idle');assert.equal(sourceViewmodelPlayback(model).generation,generation);
 const result={team,status:'passed',sourceHash:sha(old.b),candidateHash:sha(candidate.b),originalBinaryPrefixBytes:old.bin.length,originalFourClipSamples:oldClipSamples,originalBoneWorldDelta:oldDelta,drawFrames:31,drawFPS:30,drawBoneSamples:31*58,maxOriginalBoneErrorMeters:boneError,maxSameNameArmErrorMeters:armsError,maxAttachmentPositionErrorSourceUnits:attachmentError,independentOriginalIBMVertexSamples:vertexSamples,maxOriginalIBMVertexErrorMeters:vertexError,originalIBMPreserved:true,drawStartAndInterrupt:true,validator:validator.issues};receipt.push(result);disposeSourceViewmodel(model);disposeSourceViewmodel(previous);Object.values(maps).forEach(t=>t.dispose());
}
writeFileSync('output/tests/source-ak-draw-candidates.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));
