/** CPU-only original GLB hand continuity and original Dust II contacts. Does not
 * start services, use a browser, or alter any game simulation session. */
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import RAPIER from '@dimforge/rapier3d-compat';
import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {loadCharacterCpuFixture} from './validate-source-character-actor.js';
import {createSourceCharacterActors} from '../game/source-character.js';
import {createSourcePistolCharacterActors} from '../game/source-pistol-character.js';
import {createSourceDeagleCharacterActors} from '../game/source-deagle-character.js';
import {createSourceAWPCharacterActors} from '../game/source-awp-character.js';
import {loadServerSourcePistol} from '../server/source-pistol-data.js';
import {loadServerSourceDeagle} from '../server/source-deagle-data.js';
import {loadServerSourceAWP} from '../server/source-awp-data.js';
import {loadServerSourceMap} from '../server/source-map-data.js';
import {createSourceLevel,type SourceSpawn} from '../game/source-level.js';
import {createSourcePoseDriver} from '../game/source-player-contract.js';
import {bindSourceRagdoll,createSourceRagdollPoseDriver,parseSourceRagdollData,type SourceRagdollPosePlayer} from '../game/source-ragdoll.js';
import {createSourceDroppedWeaponPhysics,SOURCE_DROPPED_WEAPONS,SOURCE_DROPPED_WEAPON_MAX_PHYSICS_STEP,sourceDroppedWeaponPoseFromRest,type SourceDroppedWeaponId,type SourceDroppedWeaponSpawn} from '../game/source-dropped-weapons.js';
import type {SourceCharacterPoseIndex,SourceCharacterPoseInput} from '../game/source-character-pose.js';
import {setSourceHeldWeaponVisible} from '../game/source-dropped-weapon-renderer.js';
await RAPIER.init();
const base='public/source/csgo-12426148',read=(path:string)=>JSON.parse(readFileSync(path,'utf8')),data=parseSourceRagdollData(read(`${base}/ragdoll/ragdoll-data.json`));
async function cpuGltf(path:string,sha:string){const bytes=readFileSync(path);assert.equal(createHash('sha256').update(bytes).digest('hex'),sha);const length=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(12,true),doc=JSON.parse(bytes.subarray(20,20+length).toString()),binary=bytes.subarray(28+length);doc.materials=doc.materials.map((m:{name:string})=>({name:m.name}));delete doc.textures;delete doc.images;delete doc.extensionsUsed;delete doc.extensionsRequired;doc.buffers=[{byteLength:binary.length,uri:'data:application/octet-stream;base64,'+Buffer.from(binary).toString('base64')}];if(!globalThis.ProgressEvent)globalThis.ProgressEvent=class{constructor(type:string,value:object){Object.assign(this,{type},value);}}as unknown as typeof ProgressEvent;return new GLTFLoader().parseAsync(JSON.stringify(doc),'');}
function input(state:'Idle'|'Run'|'Crouch_Idle',weapon:SourceDroppedWeaponId,poseVersion:string){const body:SourceCharacterPoseInput={state,cycle:.45,parameters:{move_x:state==='Run'?1:0,move_y:0,body_yaw:20,body_pitch:-15},blendMode:'sdk-3way'},world={cycle:.45,parameters:{body_yaw:20,body_pitch:-15,aim_blend_stand_idle:state==='Idle'?1:0,aim_blend_stand_walk:0,aim_blend_stand_run:state==='Run'?1:0,aim_blend_crouch_idle:state==='Crouch_Idle'?1:0,aim_blend_crouch_walk:0},blendMode:'sdk-3way'as const};return{id:'victim',weapon,x:3.2,y:.7,z:-5.7,yaw:.831,sourceContract:'csgo-player-12426148'as const,sourcePoseVersion:poseVersion,sourcePose:body,sourcePistolPose:{body,world,silencerVisible:true},sourceAWPPose:{body,world:{cycle:.45,blendMode:'sdk-3way'as const}}};}
type Input=ReturnType<typeof input>;
type Profile={team:'t'|'ct';weapon:SourceDroppedWeaponId;index:SourceCharacterPoseIndex;poseVersion:string;update:(p:Input)=>void;hand:()=>T.Matrix4;hide:()=>number;dispose:()=>void;driver:ReturnType<typeof createSourceRagdollPoseDriver>};
const profiles:Profile[]=[];
for(const team of ['t','ct']as const)for(const weapon of SOURCE_DROPPED_WEAPONS){
 let index:SourceCharacterPoseIndex,poseVersion:string,update:(p:Input)=>void,hand:()=>T.Matrix4,hide:()=>number,dispose:()=>void;
 if(weapon==='vandal'||weapon==='m4a4'){
  const folder=weapon==='vandal'?(team==='t'?'character-ak':'character-ct-ak'):`character-${team}-m4`,f=await loadCharacterCpuFixture(`${base}/${folder}`),owner=createSourceCharacterActors(f.gltf,f.poseIndex,f.weapon,f.weaponBytes,f.manifest),actor=owner.createActor(),handId=f.weapon.bones.findIndex(b=>b.name==='weapon_hand_R');
  index=f.poseIndex;poseVersion=f.manifest.poseVersion;update=p=>{owner.updateActor(actor,p);assert.equal(actor.status,'ready');};hand=()=>actor.weaponBones[handId].matrixWorld;hide=()=>setSourceHeldWeaponVisible(actor,false);dispose=owner.dispose;
 }else{
  const folder=`${base}/character-${team}-${weapon}`,manifest=read(`${folder}/manifest.json`),gltf=await cpuGltf(`${folder}/${manifest.model}`,manifest.files.find((f:{path:string})=>f.path===manifest.model).sha256),rig=read(`${folder}/${manifest.rig}`);
  if(weapon==='awp'){const loaded=await loadServerSourceAWP(`${folder}/manifest.json`,team),owner=createSourceAWPCharacterActors(gltf,loaded.poseIndex,rig,manifest),actor=owner.createActor(),handId=loaded.poseIndex.world.data.bones.findIndex(b=>b.name==='weapon_hand_R');index=loaded.poseIndex.body;poseVersion=loaded.poseVersion;update=p=>{owner.updateActor(actor,p);assert.equal(actor.status,'ready');};hand=()=>actor.worldBones[handId].matrixWorld;hide=()=>setSourceHeldWeaponVisible(actor,false);dispose=owner.dispose;}
  else if(weapon==='deagle'){const loaded=await loadServerSourceDeagle(`${folder}/manifest.json`,team),owner=createSourceDeagleCharacterActors(gltf,loaded.poseIndex,rig,manifest),actor=owner.createActor(),handId=loaded.poseIndex.world.data.bones.findIndex(b=>b.name==='weapon_hand_R');index=loaded.poseIndex.body;poseVersion=loaded.poseVersion;update=p=>{owner.updateActor(actor,p);assert.equal(actor.status,'ready');};hand=()=>actor.worldBones[handId].matrixWorld;hide=()=>setSourceHeldWeaponVisible(actor,false);dispose=owner.dispose;}
  else{const loaded=await loadServerSourcePistol(`${folder}/manifest.json`,team,weapon),owner=createSourcePistolCharacterActors(gltf,loaded.poseIndex,rig,manifest),actor=owner.createActor(),handId=loaded.poseIndex.world.data.bones.findIndex(b=>b.name==='weapon_hand_R');index=loaded.poseIndex.body;poseVersion=loaded.poseVersion;update=p=>{owner.updateActor(actor,p);assert.equal(actor.status,'ready');};hand=()=>actor.worldBones[handId].matrixWorld;hide=()=>setSourceHeldWeaponVisible(actor,false);dispose=owner.dispose;}
 }
 const driver=createSourceRagdollPoseDriver(createSourcePoseDriver(index,poseVersion),index,data);profiles.push({team,weapon,index,poseVersion,update,hand,hide,dispose,driver});
}
const rows=[];
for(const profile of profiles){const bound=bindSourceRagdoll(data,profile.index);for(const state of ['Idle','Run','Crouch_Idle']as const){const player=input(state,profile.weapon,profile.poseVersion);profile.update(player);const rest=profile.driver.ragdoll!.capturePose(player),pose=sourceDroppedWeaponPoseFromRest(bound,rest,player),transform=new T.Matrix4().compose(new T.Vector3().fromArray(pose.position),new T.Quaternion().fromArray(pose.quaternion),new T.Vector3(1,1,1)).multiply(new T.Matrix4().makeRotationX(-Math.PI/2)).multiply(new T.Matrix4().makeScale(.0254,.0254,.0254));let error=0;for(const point of [[0,0,0],[23,-1,6],[-13,2,-5]])error=Math.max(error,new T.Vector3().fromArray(point).applyMatrix4(transform).distanceTo(new T.Vector3().fromArray(point).applyMatrix4(profile.hand())));assert(error<1e-6,`${profile.team} ${profile.weapon} ${state} hand mismatch ${error}`);rows.push({team:profile.team,weapon:profile.weapon,state,maxHandPointErrorMetres:error,pose});}assert(profile.hide()>0);}
const map=await loadServerSourceMap(`${base}/dust2/manifest.json`),world=new RAPIER.World({x:0,y:-20.32,z:0}),level=createSourceLevel(world,map.level,map.collision);world.timestep=SOURCE_DROPPED_WEAPON_MAX_PHYSICS_STEP;world.step();const baseline={bodies:world.bodies.len(),colliders:world.colliders.len()},drops=createSourceDroppedWeaponPhysics(world),spawns=map.level.spawns as SourceSpawn[],initial:SourceDroppedWeaponSpawn[]=[];
for(const [i,p]of profiles.entries()){const spawn=spawns.filter(s=>s.team===(p.team==='t'?'amber':'blue'))[i%5],ground=level.groundHeight(spawn.x,spawn.z,spawn.y+.25);assert(ground!==null);const player={...input('Idle',p.weapon,p.poseVersion),id:`drop-${i}`,x:spawn.x,y:ground+.02,z:spawn.z,yaw:spawn.yaw},rest=p.driver.ragdoll!.capturePose(player),pose=sourceDroppedWeaponPoseFromRest(bindSourceRagdoll(data,p.index),rest,player),entry={...pose,id:player.id,weapon:p.weapon,ownerId:player.id,createdAt:0,velocity:[.7,.4,0]as[number,number,number]};initial.push(entry);drops.create(entry);}
const times:number[]=[],settled=new Map<string,number>();
for(let tick=0;tick<1800;tick++){const start=performance.now();world.step();for(const state of drops.afterStep(world.timestep))if(state.sleeping&&!settled.has(state.id))settled.set(state.id,tick);times.push(performance.now()-start);}
const states=drops.read();mkdirSync('output/fidelity-character',{recursive:true});writeFileSync('output/fidelity-character/dropped-map-diagnostic.json',JSON.stringify({initial,states,settled:Object.fromEntries(settled),contacts:states.map(s=>{const b=drops.body(s.id)!,rows:unknown[]=[];for(let i=0;i<b.numColliders();i++){const c=b.collider(i);world.contactPairsWith(c,o=>world.contactPair(c,o,m=>rows.push({count:m.numContacts(),solver:m.numSolverContacts(),distance:Array.from({length:m.numContacts()},(_,i)=>m.contactDist(i))})));}return{id:s.id,rows};})},null,2));assert.equal(states.length,12);for(const state of states){assert(state.sleeping,`${state.id} did not settle`);const first=initial.find(i=>i.id===state.id)!;assert(state.position[1]>first.position[1]-4,`${state.id} fell through original spawn floor`);}
drops.dispose();assert.equal(world.bodies.len(),baseline.bodies);assert.equal(world.colliders.len(),baseline.colliders);level.dispose();world.free();for(const p of profiles)p.dispose();times.sort((a,b)=>a-b);
const report={scope:'CPU-only original GLB weapon_hand_R continuity and original Dust II convex contacts; no browser, LAN or native VPhysics parity claim.',profiles:profiles.length,poseCases:rows.length,rows,map:{stepSeconds:SOURCE_DROPPED_WEAPON_MAX_PHYSICS_STEP,initial,states,firstSleepTick:Object.fromEntries(settled),ownedBodiesAndCollidersReleased:true,stepAndReadMilliseconds:{p50:times[Math.floor(times.length*.5)],p95:times[Math.floor(times.length*.95)],max:times.at(-1)}}};mkdirSync('output/fidelity-character',{recursive:true});const output=resolve('output/fidelity-character/dropped-weapons-verification.json');writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({profiles:report.profiles,poseCases:report.poseCases,maxHandPointErrorMetres:Math.max(...rows.map(r=>r.maxHandPointErrorMetres)),map:{stepSeconds:report.map.stepSeconds,settled:states.filter(s=>s.sleeping).length,cleanup:true,stepAndReadMilliseconds:report.map.stepAndReadMilliseconds},output}));
